/**
 * Swarm Studio — the centerpiece masterpiece screen.
 *
 * Pass A scaffold + Pass B finishing touches:
 *   • Cosmic backdrop + ambient firefly layer
 *   • Header with the video title + dismiss control
 *   • Top constellation: 4 agent avatars in elliptical orbit around the
 *     Hive Core, with thin neural threads that brighten on the active agent
 *   • Cinematic preview with 9:16 safe-zone overlays + film burn edges
 *   • Reasoning bubble — surfaces the active agent's thought
 *   • Lily-pad input bar with rising suggestion fireflies
 *   • "Let the Hive Publish" portal CTA — triggers a 4-agent walkthrough
 *     then a full-screen light explosion that fades into the publisher
 *
 * Phase 5 wiring: the four reasoning bubbles are now generated by live
 * orchestrator calls (Ideator → Director → Editor → Monetizer) against
 * the user's StyleTwin, with deterministic seeded fallbacks so the
 * cinematic choreography never has nothing to say. Each agent's bubble
 * text is hydrated as soon as that step in the chain resolves; the
 * idle cycler then rotates through whatever's been populated.
 */

import { Feather } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { StatusBar } from "expo-status-bar";

import { flags } from "@/lib/featureFlags";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { CosmicBackdrop } from "@/components/foundation/CosmicBackdrop";
import { FireflyParticles } from "@/components/foundation/FireflyParticles";
import { GlassSurface } from "@/components/foundation/GlassSurface";
import { PortalButton } from "@/components/foundation/PortalButton";
import { AgentConstellation } from "@/components/studio/AgentConstellation";
import { LightExplosion } from "@/components/studio/LightExplosion";
import { LilyPadInput } from "@/components/studio/LilyPadInput";
import { ReasoningBubble } from "@/components/studio/ReasoningBubble";
import { type AgentKey } from "@/constants/colors";
import { type } from "@/constants/typography";
import { getImage } from "@/lib/imageRegistry";
import { useStyleTwin } from "@/hooks/useStyleTwin";
import {
  ensureSeededVectors,
  getOrchestrator,
  makeContext,
} from "@/lib/swarmFactory";
import {
  useListVideos,
  useListVideoPublications,
  getListVideoPublicationsQueryKey,
  useUpdatePublicationMetrics,
} from "@workspace/api-client-react";
import { refreshAllMetricsForVideo } from "@/lib/metricsRefresher";

type ReasoningMap = Record<AgentKey, string>;

// Seeded fallbacks so the bubble + cycler always have something cinematic
// to say even before the orchestrator chain resolves (or if the StyleTwin
// hasn't been trained yet on this device). Each line gets overwritten by
// the live agent output as soon as the corresponding step finishes.
const SEED_REASONING: ReasoningMap = {
  ideator:
    "Scanning today's regional trend feed for hooks that match your timbre fingerprint…",
  director:
    "Sketching a 9:16 storyboard with safe-zone-aware framing…",
  editor:
    "Pacing the middle beats against your retention-curve memory…",
  monetizer:
    "Matching your audience to brand pools — drafting a respectful DM…",
};

const AGENT_ORDER: AgentKey[] = ["ideator", "director", "editor", "monetizer"];

const SUGGESTIONS = [
  "Make the hook punchier",
  "Add a B-roll sweep",
  "Caption in PT/BR too",
];

export default function SwarmStudioScreen() {
  const { id } = useLocalSearchParams();
  const router = useRouter();
  const insets = useSafeAreaInsets();

  const isWeb = Platform.OS === "web";
  const topInset = isWeb ? 24 : insets.top;
  const bottomInset = insets.bottom + 16;

  const { data: videosData } = useListVideos();
  const videos = videosData?.videos ?? [];
  const video = videos.find((v) => v.id === id) ?? videos[0];

  // Live orchestrator-derived reasoning. Each agent's slot is overwritten
  // as soon as that step in the swarm chain resolves; until then the
  // seeded text keeps the bubble cinematic.
  const [reasoning, setReasoning] = useState<ReasoningMap>(SEED_REASONING);

  // Idle cycling: rotate through the four agents so the constellation
  // feels alive whenever the user isn't actively prompting or publishing.
  const [idleStep, setIdleStep] = useState(0);
  useEffect(() => {
    const t = setInterval(() => {
      setIdleStep((s) => (s + 1) % AGENT_ORDER.length);
    }, 3600);
    return () => clearInterval(t);
  }, []);

  // ── Live swarm wiring ────────────────────────────────────────────────
  // Run Ideator → Director → Editor → Monetizer once per Twin. Each
  // resolved step hydrates its bubble text. The runId guard prevents a
  // late-resolving older run from overwriting fresher state if the user
  // re-submits via the lily-pad input.
  const { twin } = useStyleTwin();
  const runIdRef = useRef(0);
  const runSwarmChain = useCallback(
    async (opts?: { preserveIdeatorAck?: boolean; creativeOverride?: string }) => {
      if (!twin) return;
      const myRun = ++runIdRef.current;
      const isLive = () => runIdRef.current === myRun;

      // Reset to seeds so a re-run visibly restarts the chain. When the
      // user just submitted a prompt we keep the freshly-set Ideator
      // acknowledgement visible until the live brief replaces it.
      setReasoning((prev) =>
        opts?.preserveIdeatorAck
          ? { ...SEED_REASONING, ideator: prev.ideator }
          : SEED_REASONING,
      );

      const { orchestrator } = getOrchestrator();
      const ctx = makeContext(twin, "us");
      try {
        await ensureSeededVectors(twin);
        if (!isLive()) return;

        const briefs = await orchestrator.dailyBriefs(ctx, {
          creativeOverride: opts?.creativeOverride,
        });
        if (!isLive() || briefs.length === 0) return;
        const brief = briefs[0]!;
        const affinity = Math.round(brief.twinAffinity.overall * 100);
        setReasoning((r) => ({
          ...r,
          ideator: `Hook: "${brief.hook}" — ${brief.culturalTag}, ${affinity}% twin affinity.`,
        }));

        const sb = await orchestrator.storyboard(ctx, brief.id);
        if (!isLive()) return;
        const opener = sb.shots[0]?.description ?? "opening shot";
        setReasoning((r) => ({
          ...r,
          director: `${sb.shots.length}-shot vertical board. Opening on: ${opener}`,
        }));

        const v = await orchestrator.produce(ctx, sb.id);
        if (!isLive()) return;
        setReasoning((r) => ({ ...r, editor: v.reasoning }));

        const drafts = await orchestrator.monetize(ctx, v.id);
        if (!isLive() || drafts.length === 0) return;
        const d = drafts[0]!;
        setReasoning((r) => ({
          ...r,
          monetizer: `Brand fit: ${d.brandHandle} via ${d.channel} — ~$${d.estimatedCreatorTakeUsd.toFixed(0)} creator take. Drafting DM.`,
        }));
      } catch (err) {
        // Swallow at the UX layer — seeded fallbacks remain visible so the
        // cinematic flow is never blocked by a missing twin or a transient
        // orchestrator error. We still surface the failure to the dev
        // console so problems are diagnosable.
        if (__DEV__) console.warn("[studio] swarm chain failed", err);
      }
    },
    [twin],
  );

  useEffect(() => {
    void runSwarmChain();
  }, [runSwarmChain]);

  // Prompt input
  const [prompt, setPrompt] = useState("");
  // Sticky override: the most recent non-empty prompt the user submitted
  // through the lily-pad. We pass this to the Publisher so the variants
  // it generates actually reflect what the user just typed in Studio
  // (otherwise the Publisher silently re-runs ideation from scratch).
  const [stickyOverride, setStickyOverride] = useState<string | undefined>(undefined);

  // Publish flow state machine: idle → walking → exploding → done(navigate)
  const [phase, setPhase] = useState<"idle" | "walking" | "exploding">("idle");
  const [walkAgent, setWalkAgent] = useState<AgentKey | null>(null);
  const walkTimers = useRef<Array<ReturnType<typeof setTimeout>>>([]);

  const clearWalkTimers = useCallback(() => {
    walkTimers.current.forEach(clearTimeout);
    walkTimers.current = [];
  }, []);

  useEffect(() => () => clearWalkTimers(), [clearWalkTimers]);

  const handlePublish = useCallback(() => {
    // PHASE UX3.3 — defense in depth. The button is hidden when the
    // flag is false; this guard keeps any programmatic invocation
    // (e.g. a future deep-link handler) from navigating into the
    // gated publisher route.
    if (!flags.SHOW_POST_BETA_SURFACES) return;
    setPhase("walking");
    clearWalkTimers();
    AGENT_ORDER.forEach((agent, i) => {
      const t = setTimeout(() => setWalkAgent(agent), i * 700);
      walkTimers.current.push(t);
    });
    // After the four-agent walkthrough, ignite the light explosion.
    const ignite = setTimeout(() => {
      setPhase("exploding");
    }, AGENT_ORDER.length * 700);
    walkTimers.current.push(ignite);
  }, [clearWalkTimers]);

  const handleExplosionComplete = useCallback(() => {
    // Reset state in case the user navigates back to /studio later.
    setPhase("idle");
    setWalkAgent(null);
    // Carry the user's lily-pad prompt forward so the Publisher's plan
    // is built around the override they just typed, not a fresh ideation.
    // Carry both the freeform override (if any) and the swarm-produced
    // videoId. The Publisher uses the videoId to persist per-platform
    // outcomes against this exact video so the badges below the preview
    // hydrate correctly on return.
    const params: Record<string, string> = {};
    if (stickyOverride) params.override = stickyOverride;
    if (video?.id) params.videoId = video.id;
    router.push(
      Object.keys(params).length > 0
        ? { pathname: "/publisher", params }
        : "/publisher",
    );
  }, [router, stickyOverride, video?.id]);

  // Live published-to set for the badges row under the preview.
  // Only meaningful for swarm-produced videos (real DB rows); for
  // demo seed rows the query simply returns no publications and the
  // row collapses.
  // Use the orval-generated query key so the publisher's post-launch
  // invalidation (which targets the same generated key) actually wakes
  // this query and refreshes the badges without a manual refresh.
  const { data: pubsData } = useListVideoPublications(video?.id ?? "", {
    query: {
      queryKey: getListVideoPublicationsQueryKey(video?.id ?? ""),
      enabled: !!video?.id,
    },
  });
  const publishedPlatforms = useMemo(() => {
    const set = new Set<string>();
    for (const p of pubsData?.publications ?? []) {
      if (p.status === "published") set.add(p.platform);
    }
    return set;
  }, [pubsData]);

  // Aggregate metrics by platform for the badge row. We pick the latest
  // published row per platform; mock-mode rows simply have no metrics and
  // the badge falls back to its bare ✓ rendering.
  const metricsByPlatform = useMemo(() => {
    const out = new Map<string, { views: number; likes: number }>();
    for (const p of pubsData?.publications ?? []) {
      if (p.status !== "published") continue;
      const m = (p as { metrics?: { views?: number; likes?: number } | null })
        .metrics;
      if (m && typeof m === "object") {
        out.set(p.platform, {
          views: Number(m.views ?? 0) || 0,
          likes: Number(m.likes ?? 0) || 0,
        });
      }
    }
    return out;
  }, [pubsData]);

  const updateMetrics = useUpdatePublicationMetrics();
  const [refreshingMetrics, setRefreshingMetrics] = useState(false);
  const handleRefreshMetrics = useCallback(async () => {
    if (!video?.id || refreshingMetrics) return;
    const pubs = pubsData?.publications ?? [];
    if (pubs.length === 0) return;
    setRefreshingMetrics(true);
    try {
      await refreshAllMetricsForVideo(
        pubs.map((p) => ({
          id: p.id,
          platform: p.platform,
          status: p.status,
          platformPostId: (p as { platformPostId?: string | null })
            .platformPostId,
        })),
        async ({ pubId, data }) => {
          await updateMetrics.mutateAsync({ id: video.id, pubId, data });
        },
      );
    } catch {
      // Refresh failures are silent — the next manual or 5-min foreground
      // tick will retry. Keeping the studio choreography uninterrupted is
      // more important than surfacing transient platform errors here.
    } finally {
      setRefreshingMetrics(false);
    }
  }, [video?.id, pubsData, updateMetrics, refreshingMetrics]);

  const compact = (n: number): string => {
    if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
    if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
    return String(n);
  };

  const handleSubmit = useCallback(
    (text: string) => {
      // The orchestrator API doesn't currently accept a free-form override;
      // re-running the chain is the closest faithful effect — it surfaces
      // a fresh brief/storyboard/video/deal sequence in the bubbles. We
      // also surge the Ideator so the constellation visibly responds.
      const trimmed = text.trim();
      if (trimmed) {
        setReasoning((r) => ({
          ...r,
          ideator: `Heard: "${trimmed}". Re-running the swarm with this in mind…`,
        }));
      }
      if (trimmed) setStickyOverride(trimmed);
      setPrompt("");
      setIdleStep(0);
      void runSwarmChain({
        preserveIdeatorAck: trimmed.length > 0,
        creativeOverride: trimmed || undefined,
      });
    },
    [runSwarmChain],
  );

  // Active agent + reasoning text. During walking, the publish walkthrough
  // takes over; otherwise the idle cycler drives the bubble.
  const activeAgent: AgentKey =
    phase === "walking" && walkAgent ? walkAgent : AGENT_ORDER[idleStep]!;
  const activeBubbleText = useMemo(
    () => reasoning[activeAgent],
    [reasoning, activeAgent],
  );

  return (
    <View style={styles.root}>
      <StatusBar style="light" />

      <CosmicBackdrop bloom>
        <FireflyParticles count={14} ambient />
      </CosmicBackdrop>

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        keyboardVerticalOffset={topInset}
      >
        <View style={[styles.header, { paddingTop: topInset + 8 }]}>
          <Pressable
            onPress={() => router.back()}
            style={styles.iconBtn}
            hitSlop={12}
            accessibilityRole="button"
            accessibilityLabel="Close swarm studio"
          >
            <Feather name="chevron-down" size={24} color="#FFFFFF" />
          </Pressable>
          <View style={styles.headerCentre}>
            <Text style={[type.label, styles.headerEyebrow]}>swarm studio</Text>
            <Text
              style={[type.subheadSm, styles.headerTitle]}
              numberOfLines={1}
            >
              {video?.title ?? "Untitled"}
            </Text>
          </View>
          <View style={styles.iconBtn} />
        </View>

        {/* Constellation centrepiece */}
        <View style={styles.constellation}>
          <AgentConstellation
            size={300}
            active={activeAgent}
            agreeing={
              phase === "walking" && walkAgent === "monetizer"
                ? AGENT_ORDER
                : []
            }
          />
        </View>

        {/* Reasoning bubble */}
        <View style={styles.bubbleSlot}>
          <ReasoningBubble
            key={`${activeAgent}-${phase === "walking" ? "walk" : idleStep}`}
            agent={activeAgent}
            text={activeBubbleText}
          />
        </View>

        {/* Cinematic preview with 9:16 safe-zone — fixed height so the
            input bar + publish CTA always sit in the bottom third. */}
        <View style={styles.previewWrap}>
          <GlassSurface radius={20} agent={activeAgent}>
            <View style={styles.previewInner}>
              {video?.thumbnailKey ? (
                <Image
                  source={getImage(video.thumbnailKey)}
                  style={styles.previewImage}
                />
              ) : (
                <View
                  style={[styles.previewImage, { backgroundColor: "#15123A" }]}
                />
              )}
              <View pointerEvents="none" style={styles.safeZone}>
                <View style={styles.safeTop} />
                <View style={styles.safeBottom} />
                <View style={styles.safeRight} />
              </View>
              <View pointerEvents="none" style={styles.filmBurn} />
              <View style={styles.previewMeta}>
                <Text style={[type.microDelight, styles.previewLabel]}>
                  ✦ live preview · safe-zone honoured
                </Text>
              </View>
            </View>
          </GlassSurface>
          {publishedPlatforms.size > 0 && (
            <View style={styles.publishedBadges}>
              {(["tiktok", "reels", "shorts"] as const).map((p) => {
                if (!publishedPlatforms.has(p)) return null;
                const m = metricsByPlatform.get(p);
                return (
                  <View key={p} style={styles.publishedBadge}>
                    <Feather name="check" size={11} color="#00FFCC" />
                    <Text style={styles.publishedBadgeText}>{p}</Text>
                    {m && (m.views > 0 || m.likes > 0) && (
                      <Text style={styles.publishedBadgeText}>
                        · {compact(m.views)} ▶
                      </Text>
                    )}
                  </View>
                );
              })}
              <Pressable
                onPress={handleRefreshMetrics}
                hitSlop={8}
                accessibilityRole="button"
                accessibilityLabel="Refresh platform metrics"
                style={styles.metricsRefreshBtn}
              >
                <Feather
                  name={refreshingMetrics ? "loader" : "refresh-cw"}
                  size={11}
                  color="#00FFCC"
                />
              </Pressable>
            </View>
          )}
        </View>

        {/* Publish portal CTA — PHASE UX3.3: the publisher route is
            off-vision for the closed beta. Hide the entire wrap so
            the saved-idea detail screen reads as "review only". The
            handlePublish callback is also guarded defensively so any
            programmatic call no-ops. */}
        {flags.SHOW_POST_BETA_SURFACES && (
          <View style={styles.publishWrap}>
            <PortalButton
              label={phase === "walking" ? "the hive is publishing…" : "let the hive publish"}
              onPress={handlePublish}
              width={260}
              subtle
              disabled={phase !== "idle"}
            />
          </View>
        )}

        {/* Lily-pad input bar */}
        <View style={{ paddingBottom: bottomInset }}>
          <LilyPadInput
            value={prompt}
            onChangeText={setPrompt}
            onSubmit={handleSubmit}
            suggestions={SUGGESTIONS}
            disabled={phase !== "idle"}
          />
        </View>
      </KeyboardAvoidingView>

      {/* Light-explosion overlay */}
      <LightExplosion
        active={phase === "exploding"}
        onComplete={handleExplosionComplete}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#0A0824",
  },
  flex: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  headerCentre: {
    flex: 1,
    alignItems: "center",
  },
  headerEyebrow: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 11,
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  headerTitle: {
    color: "#FFFFFF",
    marginTop: 2,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  constellation: {
    alignItems: "center",
    justifyContent: "center",
    height: 300,
  },
  bubbleSlot: {
    paddingHorizontal: 22,
    minHeight: 96,
    justifyContent: "center",
  },
  previewWrap: {
    paddingHorizontal: 80,
    paddingTop: 4,
  },
  previewInner: {
    width: "100%",
    height: 180,
    overflow: "hidden",
    position: "relative",
  },
  previewImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  safeZone: { ...StyleSheet.absoluteFillObject },
  safeTop: {
    position: "absolute",
    top: "12%",
    left: 12,
    right: 12,
    height: 1,
    borderStyle: "dashed",
    borderWidth: 0.5,
    borderColor: "rgba(0,255,204,0.35)",
  },
  safeBottom: {
    position: "absolute",
    bottom: "22%",
    left: 12,
    right: 12,
    height: 1,
    backgroundColor: "rgba(0,255,204,0.35)",
  },
  safeRight: {
    position: "absolute",
    top: 12,
    bottom: 12,
    right: "18%",
    width: 1,
    backgroundColor: "rgba(0,255,204,0.35)",
  },
  filmBurn: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 12,
    borderColor: "rgba(10,8,36,0.6)",
    shadowColor: "#000000",
    shadowOpacity: 0.65,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 18,
  },
  publishedBadges: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginTop: 10,
  },
  publishedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(0,255,204,0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,255,204,0.35)",
  },
  publishedBadgeText: {
    color: "#00FFCC",
    fontSize: 11,
    letterSpacing: 0.6,
    textTransform: "lowercase",
  },
  metricsRefreshBtn: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(0,255,204,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  previewMeta: {
    position: "absolute",
    bottom: 14,
    left: 16,
    right: 16,
  },
  previewLabel: {
    color: "rgba(0,255,204,0.85)",
  },
  publishWrap: {
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 6,
    marginTop: "auto",
  },
});
