/**
 * Swarm Studio — the centerpiece masterpiece screen.
 *
 * Pass A scaffold + Pass B finishing touches:
 *   • Cosmic backdrop + ambient firefly layer
 *   • Header with the video title + dismiss control
 *   • Top constellation: 4 agent avatars in elliptical orbit around the
 *     Hive Core, with thin neural threads that brighten on the active agent
 *   • Cinematic preview with 9:16 safe-zone overlays + film burn edges
 *   • Reasoning bubble — surfaces the active agent's thought
 *   • Lily-pad input bar with rising suggestion fireflies
 *   • "Let the Hive Publish" portal CTA — triggers a 4-agent walkthrough
 *     then a full-screen light explosion that fades into the publisher
 *
 * Phase 5 wiring: the four reasoning bubbles are now generated by live
 * orchestrator calls (Ideator → Director → Editor → Monetizer) against
 * the user's StyleTwin, with deterministic seeded fallbacks so the
 * cinematic choreography never has nothing to say. Each agent's bubble
 * text is hydrated as soon as that step in the chain resolves; the
 * idle cycler then rotates through whatever's been populated.
 */

import { Feather } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { StatusBar } from "expo-status-bar";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Image,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  View,
} from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { CosmicBackdrop } from "@/components/foundation/CosmicBackdrop";
import { FireflyParticles } from "@/components/foundation/FireflyParticles";
import { GlassSurface } from "@/components/foundation/GlassSurface";
import { PortalButton } from "@/components/foundation/PortalButton";
import { AgentConstellation } from "@/components/studio/AgentConstellation";
import { LightExplosion } from "@/components/studio/LightExplosion";
import { LilyPadInput } from "@/components/studio/LilyPadInput";
import { ReasoningBubble } from "@/components/studio/ReasoningBubble";
import { type AgentKey } from "@/constants/colors";
import { type } from "@/constants/typography";
import { getImage } from "@/lib/imageRegistry";
import { useStyleTwin } from "@/hooks/useStyleTwin";
import {
  ensureSeededVectors,
  getOrchestrator,
  makeContext,
} from "@/lib/swarmFactory";
import { useListVideos } from "@workspace/api-client-react";

type ReasoningMap = Record<AgentKey, string>;

// Seeded fallbacks so the bubble + cycler always have something cinematic
// to say even before the orchestrator chain resolves (or if the StyleTwin
// hasn't been trained yet on this device). Each line gets overwritten by
// the live agent output as soon as the corresponding step finishes.
const SEED_REASONING: ReasoningMap = {
  ideator:
    "Scanning today's regional trend feed for hooks that match your timbre fingerprint…",
  director:
    "Sketching a 9:16 storyboard with safe-zone-aware framing…",
  editor:
    "Pacing the middle beats against your retention-curve memory…",
  monetizer:
    "Matching your audience to brand pools — drafting a respectful DM…",
};

const AGENT_ORDER: AgentKey[] = ["ideator", "director", "editor", "monetizer"];

const SUGGESTIONS = [
  "Make the hook punchier",
  "Add a B-roll sweep",
  "Caption in PT/BR too",
];

export default function SwarmStudioScreen() {
  const { id } = useLocalSearchParams();
  const router = useRouter();
  const insets = useSafeAreaInsets();

  const isWeb = Platform.OS === "web";
  const topInset = isWeb ? 24 : insets.top;
  const bottomInset = insets.bottom + 16;

  const { data: videosData } = useListVideos();
  const videos = videosData?.videos ?? [];
  const video = videos.find((v) => v.id === id) ?? videos[0];

  // Live orchestrator-derived reasoning. Each agent's slot is overwritten
  // as soon as that step in the swarm chain resolves; until then the
  // seeded text keeps the bubble cinematic.
  const [reasoning, setReasoning] = useState<ReasoningMap>(SEED_REASONING);

  // Idle cycling: rotate through the four agents so the constellation
  // feels alive whenever the user isn't actively prompting or publishing.
  const [idleStep, setIdleStep] = useState(0);
  useEffect(() => {
    const t = setInterval(() => {
      setIdleStep((s) => (s + 1) % AGENT_ORDER.length);
    }, 3600);
    return () => clearInterval(t);
  }, []);

  // ── Live swarm wiring ────────────────────────────────────────────────
  // Run Ideator → Director → Editor → Monetizer once per Twin. Each
  // resolved step hydrates its bubble text. The runId guard prevents a
  // late-resolving older run from overwriting fresher state if the user
  // re-submits via the lily-pad input.
  const { twin } = useStyleTwin();
  const runIdRef = useRef(0);
  const runSwarmChain = useCallback(
    async (opts?: { preserveIdeatorAck?: boolean }) => {
      if (!twin) return;
      const myRun = ++runIdRef.current;
      const isLive = () => runIdRef.current === myRun;

      // Reset to seeds so a re-run visibly restarts the chain. When the
      // user just submitted a prompt we keep the freshly-set Ideator
      // acknowledgement visible until the live brief replaces it.
      setReasoning((prev) =>
        opts?.preserveIdeatorAck
          ? { ...SEED_REASONING, ideator: prev.ideator }
          : SEED_REASONING,
      );

      const { orchestrator } = getOrchestrator();
      const ctx = makeContext(twin, "us");
      try {
        await ensureSeededVectors(twin);
        if (!isLive()) return;

        const briefs = await orchestrator.dailyBriefs(ctx);
        if (!isLive() || briefs.length === 0) return;
        const brief = briefs[0]!;
        const affinity = Math.round(brief.twinAffinity.overall * 100);
        setReasoning((r) => ({
          ...r,
          ideator: `Hook: "${brief.hook}" — ${brief.culturalTag}, ${affinity}% twin affinity.`,
        }));

        const sb = await orchestrator.storyboard(ctx, brief.id);
        if (!isLive()) return;
        const opener = sb.shots[0]?.description ?? "opening shot";
        setReasoning((r) => ({
          ...r,
          director: `${sb.shots.length}-shot vertical board. Opening on: ${opener}`,
        }));

        const v = await orchestrator.produce(ctx, sb.id);
        if (!isLive()) return;
        setReasoning((r) => ({ ...r, editor: v.reasoning }));

        const drafts = await orchestrator.monetize(ctx, v.id);
        if (!isLive() || drafts.length === 0) return;
        const d = drafts[0]!;
        setReasoning((r) => ({
          ...r,
          monetizer: `Brand fit: ${d.brandHandle} via ${d.channel} — ~$${d.estimatedCreatorTakeUsd.toFixed(0)} creator take. Drafting DM.`,
        }));
      } catch (err) {
        // Swallow at the UX layer — seeded fallbacks remain visible so the
        // cinematic flow is never blocked by a missing twin or a transient
        // orchestrator error. We still surface the failure to the dev
        // console so problems are diagnosable.
        if (__DEV__) console.warn("[studio] swarm chain failed", err);
      }
    },
    [twin],
  );

  useEffect(() => {
    void runSwarmChain();
  }, [runSwarmChain]);

  // Prompt input
  const [prompt, setPrompt] = useState("");

  // Publish flow state machine: idle → walking → exploding → done(navigate)
  const [phase, setPhase] = useState<"idle" | "walking" | "exploding">("idle");
  const [walkAgent, setWalkAgent] = useState<AgentKey | null>(null);
  const walkTimers = useRef<Array<ReturnType<typeof setTimeout>>>([]);

  const clearWalkTimers = useCallback(() => {
    walkTimers.current.forEach(clearTimeout);
    walkTimers.current = [];
  }, []);

  useEffect(() => () => clearWalkTimers(), [clearWalkTimers]);

  const handlePublish = useCallback(() => {
    setPhase("walking");
    clearWalkTimers();
    AGENT_ORDER.forEach((agent, i) => {
      const t = setTimeout(() => setWalkAgent(agent), i * 700);
      walkTimers.current.push(t);
    });
    // After the four-agent walkthrough, ignite the light explosion.
    const ignite = setTimeout(() => {
      setPhase("exploding");
    }, AGENT_ORDER.length * 700);
    walkTimers.current.push(ignite);
  }, [clearWalkTimers]);

  const handleExplosionComplete = useCallback(() => {
    // Reset state in case the user navigates back to /studio later.
    setPhase("idle");
    setWalkAgent(null);
    router.push("/publisher");
  }, [router]);

  const handleSubmit = useCallback(
    (text: string) => {
      // The orchestrator API doesn't currently accept a free-form override;
      // re-running the chain is the closest faithful effect — it surfaces
      // a fresh brief/storyboard/video/deal sequence in the bubbles. We
      // also surge the Ideator so the constellation visibly responds.
      const trimmed = text.trim();
      if (trimmed) {
        setReasoning((r) => ({
          ...r,
          ideator: `Heard: "${trimmed}". Re-running the swarm with this in mind…`,
        }));
      }
      setPrompt("");
      setIdleStep(0);
      void runSwarmChain({ preserveIdeatorAck: trimmed.length > 0 });
    },
    [runSwarmChain],
  );

  // Active agent + reasoning text. During walking, the publish walkthrough
  // takes over; otherwise the idle cycler drives the bubble.
  const activeAgent: AgentKey =
    phase === "walking" && walkAgent ? walkAgent : AGENT_ORDER[idleStep]!;
  const activeBubbleText = useMemo(
    () => reasoning[activeAgent],
    [reasoning, activeAgent],
  );

  return (
    <View style={styles.root}>
      <StatusBar style="light" />

      <CosmicBackdrop bloom>
        <FireflyParticles count={14} ambient />
      </CosmicBackdrop>

      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        keyboardVerticalOffset={topInset}
      >
        <View style={[styles.header, { paddingTop: topInset + 8 }]}>
          <Pressable
            onPress={() => router.back()}
            style={styles.iconBtn}
            hitSlop={12}
            accessibilityRole="button"
            accessibilityLabel="Close swarm studio"
          >
            <Feather name="chevron-down" size={24} color="#FFFFFF" />
          </Pressable>
          <View style={styles.headerCentre}>
            <Text style={[type.label, styles.headerEyebrow]}>swarm studio</Text>
            <Text
              style={[type.subheadSm, styles.headerTitle]}
              numberOfLines={1}
            >
              {video?.title ?? "Untitled"}
            </Text>
          </View>
          <View style={styles.iconBtn} />
        </View>

        {/* Constellation centrepiece */}
        <View style={styles.constellation}>
          <AgentConstellation
            size={300}
            active={activeAgent}
            agreeing={
              phase === "walking" && walkAgent === "monetizer"
                ? AGENT_ORDER
                : []
            }
          />
        </View>

        {/* Reasoning bubble */}
        <View style={styles.bubbleSlot}>
          <ReasoningBubble
            key={`${activeAgent}-${phase === "walking" ? "walk" : idleStep}`}
            agent={activeAgent}
            text={activeBubbleText}
          />
        </View>

        {/* Cinematic preview with 9:16 safe-zone — fixed height so the
            input bar + publish CTA always sit in the bottom third. */}
        <View style={styles.previewWrap}>
          <GlassSurface radius={20} agent={activeAgent}>
            <View style={styles.previewInner}>
              {video?.thumbnailKey ? (
                <Image
                  source={getImage(video.thumbnailKey)}
                  style={styles.previewImage}
                />
              ) : (
                <View
                  style={[styles.previewImage, { backgroundColor: "#15123A" }]}
                />
              )}
              <View pointerEvents="none" style={styles.safeZone}>
                <View style={styles.safeTop} />
                <View style={styles.safeBottom} />
                <View style={styles.safeRight} />
              </View>
              <View pointerEvents="none" style={styles.filmBurn} />
              <View style={styles.previewMeta}>
                <Text style={[type.microDelight, styles.previewLabel]}>
                  ✦ live preview · safe-zone honoured
                </Text>
              </View>
            </View>
          </GlassSurface>
        </View>

        {/* Publish portal CTA */}
        <View style={styles.publishWrap}>
          <PortalButton
            label={phase === "walking" ? "the hive is publishing…" : "let the hive publish"}
            onPress={handlePublish}
            width={260}
            subtle
            disabled={phase !== "idle"}
          />
        </View>

        {/* Lily-pad input bar */}
        <View style={{ paddingBottom: bottomInset }}>
          <LilyPadInput
            value={prompt}
            onChangeText={setPrompt}
            onSubmit={handleSubmit}
            suggestions={SUGGESTIONS}
            disabled={phase !== "idle"}
          />
        </View>
      </KeyboardAvoidingView>

      {/* Light-explosion overlay */}
      <LightExplosion
        active={phase === "exploding"}
        onComplete={handleExplosionComplete}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#0A0824",
  },
  flex: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  headerCentre: {
    flex: 1,
    alignItems: "center",
  },
  headerEyebrow: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 11,
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },
  headerTitle: {
    color: "#FFFFFF",
    marginTop: 2,
  },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  constellation: {
    alignItems: "center",
    justifyContent: "center",
    height: 300,
  },
  bubbleSlot: {
    paddingHorizontal: 22,
    minHeight: 96,
    justifyContent: "center",
  },
  previewWrap: {
    paddingHorizontal: 80,
    paddingTop: 4,
  },
  previewInner: {
    width: "100%",
    height: 180,
    overflow: "hidden",
    position: "relative",
  },
  previewImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  safeZone: { ...StyleSheet.absoluteFillObject },
  safeTop: {
    position: "absolute",
    top: "12%",
    left: 12,
    right: 12,
    height: 1,
    borderStyle: "dashed",
    borderWidth: 0.5,
    borderColor: "rgba(0,255,204,0.35)",
  },
  safeBottom: {
    position: "absolute",
    bottom: "22%",
    left: 12,
    right: 12,
    height: 1,
    backgroundColor: "rgba(0,255,204,0.35)",
  },
  safeRight: {
    position: "absolute",
    top: 12,
    bottom: 12,
    right: "18%",
    width: 1,
    backgroundColor: "rgba(0,255,204,0.35)",
  },
  filmBurn: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 12,
    borderColor: "rgba(10,8,36,0.6)",
    shadowColor: "#000000",
    shadowOpacity: 0.65,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 18,
  },
  previewMeta: {
    position: "absolute",
    bottom: 14,
    left: 16,
    right: 16,
  },
  previewLabel: {
    color: "rgba(0,255,204,0.85)",
  },
  publishWrap: {
    alignItems: "center",
    paddingTop: 18,
    paddingBottom: 6,
    marginTop: "auto",
  },
});
