/**
 * REGIONAL N1 — APPROVED Nigerian promotion candidates.
 *
 * AUTO-GENERATED by `qa/buildApprovedNigerianPack.ts`. Do NOT edit by hand.
 * Re-run the generator to refresh after a new reviewer pass.
 *
 * STATUS: INERT. This array is NOT `NIGERIAN_HOOK_PACK`. The live pool
 * remains empty (DARK). A separate, explicit promotion step is required
 * to copy entries into the live pack, AND `LUMINA_NG_PACK_ENABLED=true`
 * must be set, before `canActivateNigerianPack` can return true.
 *
 * Cross-region leak remains impossible by construction: the central
 * activation guard still requires region === "nigeria" + non-clean
 * languageStyle even after promotion.
 *
 * Every entry below was re-validated against EVERY production rule:
 *   • reviewedBy non-empty AND not PENDING_NATIVE_REVIEW
 *   • pidginLevel ∈ {light_pidgin, pidgin}
 *   • hook/whatToShow/howToFilm/caption length bounds (PACK_FIELD_BOUNDS)
 *   • anchor (lowercase) present in BOTH hook AND whatToShow
 *   • no PIDGIN_MOCKING_PATTERNS hit on hook/whatToShow/caption
 *   • validateScenarioCoherence(idea) === null
 *   • scoreNigerianPackEntry(entry) >= 40  (Pidgin-aware additive scorer; floor unchanged)
 *
 * INGEST SUMMARY: 63 approved · 74 rejected
 *
 * REJECTED ROWS (kept here for the reviewer audit trail; NOT in the
 * exported array — the generator does not silently fix anything):
 *   • DRAFT-003 → scoreNigerianPackEntry 20 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=5 filmable=10 brevity=5)
 *   • DRAFT-005 → anchor 'message' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 34 < floor 40 (visceral=7 naturalness=-5 contradiction=0 anchor=10 filmable=5 brevity=17)
 *   • DRAFT-013 → anchor 'danfo' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 27 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=5 filmable=5 brevity=17)
 *   • DRAFT-015 → anchor 'outfit' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 30 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=0 filmable=10 brevity=20)
 *   • DRAFT-019 → anchor 'keys' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 29 < floor 40 (visceral=7 naturalness=4 contradiction=0 anchor=0 filmable=5 brevity=13)
 *   • DRAFT-021 → scoreNigerianPackEntry 39 < floor 40 (visceral=7 naturalness=-5 contradiction=0 anchor=10 filmable=10 brevity=17)
 *   • DRAFT-025 → scoreNigerianPackEntry 24 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=5 filmable=10 brevity=9)
 *   • DRAFT-027 → anchor 'light' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 26 < floor 40 (visceral=5 naturalness=-5 contradiction=3 anchor=5 filmable=5 brevity=13)
 *   • DRAFT-029 → anchor 'socket' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 28 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=10 filmable=5 brevity=13)
 *   • DRAFT-033 → anchor 'jollof' not found in whatToShow; scoreNigerianPackEntry 29 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=5 brevity=9)
 *   • DRAFT-037 → anchor 'pot' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 29 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=0 filmable=10 brevity=13)
 *   • DRAFT-039 → anchor 'snacks' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 26 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=10 filmable=5 brevity=5)
 *   • DRAFT-043 → anchor 'notes' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 19 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=0 filmable=10 brevity=9)
 *   • DRAFT-045 → anchor 'later' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 19 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=5 filmable=5 brevity=9)
 *   • DRAFT-047 → anchor 'meeting' not found in whatToShow; scoreNigerianPackEntry 37 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=5 brevity=17)
 *   • DRAFT-049 → anchor 'notebook' not found in hook; scoreNigerianPackEntry 28 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=0 filmable=10 brevity=13)
 *   • DRAFT-051 → validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 34 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=10 brevity=9)
 *   • DRAFT-055 → scoreNigerianPackEntry 31 < floor 40 (visceral=7 naturalness=-5 contradiction=0 anchor=10 filmable=10 brevity=9)
 *   • DRAFT-057 → anchor 'room' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 34 < floor 40 (visceral=7 naturalness=-5 contradiction=0 anchor=10 filmable=5 brevity=17)
 *   • DRAFT-075 → anchor 'post' not found in hook; scoreNigerianPackEntry 15 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=0 filmable=10 brevity=5)
 *   • DRAFT-077 → anchor 'clip' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 39 < floor 40 (visceral=25 naturalness=-5 contradiction=0 anchor=0 filmable=10 brevity=9)
 *   • DRAFT-079 → anchor 'views' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 30 < floor 40 (visceral=7 naturalness=0 contradiction=0 anchor=10 filmable=0 brevity=13)
 *   • DRAFT-081 → anchor 'mirror' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-087 → anchor 'plan' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 32 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=10 filmable=5 brevity=17)
 *   • DRAFT-089 → anchor 'kettle' not found in hook; scoreNigerianPackEntry 30 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=0 filmable=10 brevity=20)
 *   • DRAFT-097 → anchor 'hair' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-099 → anchor 'task' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 19 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=0 filmable=10 brevity=9)
 *   • DRAFT-102 → anchor 'typing' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 33 < floor 40 (visceral=5 naturalness=0 contradiction=9 anchor=0 filmable=10 brevity=9)
 *   • DRAFT-104 → anchor 'seen' not found in hook; scoreNigerianPackEntry 24 < floor 40 (visceral=5 naturalness=-5 contradiction=9 anchor=0 filmable=10 brevity=5)
 *   • DRAFT-106 → anchor 'voice' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 24 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=0 filmable=10 brevity=9)
 *   • DRAFT-109 → validateScenarioCoherence: hook_topic_noun_drift
 *   • DRAFT-121 → anchor 'keke' not found in whatToShow; scoreNigerianPackEntry 33 < floor 40 (visceral=7 naturalness=4 contradiction=3 anchor=10 filmable=0 brevity=9)
 *   • DRAFT-127 → anchor 'data' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 38 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=10 filmable=5 brevity=17)
 *   • DRAFT-131 → anchor 'charger' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 29 < floor 40 (visceral=7 naturalness=0 contradiction=0 anchor=0 filmable=5 brevity=17)
 *   • DRAFT-135 → scoreNigerianPackEntry 37 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=5 filmable=10 brevity=17)
 *   • DRAFT-139 → anchor 'indomie' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-141 → scoreNigerianPackEntry 30 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=10 filmable=5 brevity=9)
 *   • DRAFT-143 → anchor 'maggi' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-145 → anchor 'rice' not found in whatToShow; scoreNigerianPackEntry 34 < floor 40 (visceral=7 naturalness=4 contradiction=0 anchor=10 filmable=0 brevity=13)
 *   • DRAFT-148 → anchor 'snack' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 25 < floor 40 (visceral=7 naturalness=8 contradiction=0 anchor=0 filmable=5 brevity=5)
 *   • DRAFT-156 → anchor 'zoom' not found in hook; scoreNigerianPackEntry 33 < floor 40 (visceral=5 naturalness=0 contradiction=9 anchor=0 filmable=10 brevity=9)
 *   • DRAFT-168 → anchor 'change' not found in whatToShow; scoreNigerianPackEntry 32 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=0 brevity=17)
 *   • DRAFT-175 → scoreNigerianPackEntry 20 < floor 40 (visceral=5 naturalness=-5 contradiction=0 anchor=5 filmable=10 brevity=5)
 *   • DRAFT-179 → scoreNigerianPackEntry 26 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=5 filmable=10 brevity=5)
 *   • DRAFT-183 → anchor 'edit' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 37 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=5 brevity=17)
 *   • DRAFT-189 → anchor 'lost' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 29 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=10 filmable=0 brevity=13)
 *   • DRAFT-197 → anchor 'shoe' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 29 < floor 40 (visceral=7 naturalness=0 contradiction=3 anchor=10 filmable=0 brevity=9)
 *   • DRAFT-208 → anchor 'deleted' not found in hook; scoreNigerianPackEntry 39 < floor 40 (visceral=5 naturalness=4 contradiction=0 anchor=0 filmable=10 brevity=20)
 *   • DRAFT-214 → anchor 'reply' not found in hook; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-216 → anchor 'emoji' not found in hook; scoreNigerianPackEntry 28 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=0 filmable=5 brevity=17)
 *   • DRAFT-225 → anchor 'keke' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-230 → anchor 'passenger' not found in hook; scoreNigerianPackEntry 35 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=0 filmable=10 brevity=20)
 *   • DRAFT-232 → anchor 'bike' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-235 → anchor 'data' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-239 → anchor 'light' not found in hook; anchor 'light' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 36 < floor 40 (visceral=5 naturalness=0 contradiction=6 anchor=0 filmable=5 brevity=20)
 *   • DRAFT-242 → scoreNigerianPackEntry 35 < floor 40 (visceral=5 naturalness=0 contradiction=3 anchor=5 filmable=5 brevity=17)
 *   • DRAFT-246 → anchor 'battery' not found in hook
 *   • DRAFT-249 → anchor 'indomie' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-253 → anchor 'maggi' not found in whatToShow
 *   • DRAFT-256 → anchor 'freezer' not found in hook; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-258 → anchor 'snack' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 32 < floor 40 (visceral=7 naturalness=4 contradiction=3 anchor=0 filmable=5 brevity=13)
 *   • DRAFT-263 → anchor 'submission' not found in whatToShow; scoreNigerianPackEntry 28 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=0 brevity=13)
 *   • DRAFT-267 → anchor 'presentation' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-272 → anchor 'aunty' not found in hook; anchor 'aunty' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 31 < floor 40 (visceral=7 naturalness=4 contradiction=0 anchor=0 filmable=0 brevity=20)
 *   • DRAFT-274 → anchor 'cousin' not found in hook; scoreNigerianPackEntry 39 < floor 40 (visceral=5 naturalness=4 contradiction=0 anchor=0 filmable=10 brevity=20)
 *   • DRAFT-280 → anchor 'cart' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 34 < floor 40 (visceral=5 naturalness=-5 contradiction=9 anchor=0 filmable=5 brevity=20)
 *   • DRAFT-282 → anchor 'salary' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 36 < floor 40 (visceral=5 naturalness=0 contradiction=6 anchor=5 filmable=0 brevity=20)
 *   • DRAFT-283 → anchor 'wishlist' not found in hook; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 35 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=0 filmable=10 brevity=20)
 *   • DRAFT-287 → anchor 'budget' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-288 → anchor 'salary' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor; scoreNigerianPackEntry 33 < floor 40 (visceral=5 naturalness=0 contradiction=0 anchor=10 filmable=5 brevity=13)
 *   • DRAFT-290 → anchor 'views' not found in hook; anchor 'views' not found in whatToShow; scoreNigerianPackEntry 21 < floor 40 (visceral=5 naturalness=-5 contradiction=3 anchor=0 filmable=5 brevity=13)
 *   • DRAFT-294 → anchor 'post' not found in hook; scoreNigerianPackEntry 36 < floor 40 (visceral=5 naturalness=4 contradiction=0 anchor=0 filmable=10 brevity=17)
 *   • DRAFT-296 → anchor 'camera' not found in whatToShow; validateScenarioCoherence: show_missing_hook_anchor
 *   • DRAFT-300 → scoreNigerianPackEntry 39 < floor 40 (visceral=5 naturalness=-5 contradiction=6 anchor=10 filmable=10 brevity=13)
 */

import { type NigerianPackEntry } from "./nigerianHookPack.js";

export const APPROVED_NIGERIAN_PROMOTION_CANDIDATES: readonly NigerianPackEntry[] =
  Object.freeze([
    Object.freeze({
      // source: DRAFT-001 · cluster: whatsapp · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "who send me make I tell them say I dey come?",
      whatToShow: "Show a fake WhatsApp group plan from yesterday. Someone texts 'you don dey road?' while you are still under the blanket. Your hand hovers over the keyboard, types 'almost there,' then deletes it.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "yesterday me too get mind.",
      anchor: "dey",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-006 [REWRITE] · cluster: group_chat · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "group chat don hijack my whole peace",
      whatToShow: "Fake group chat shows five people tagging you. You type one reply, delete it, then just send a thumbs-up emoji and look away like that solved governance.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "leadership by emoji.",
      anchor: "group",
      domain: "messaging",
      pidginLevel: "pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-008 · cluster: whatsapp · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "I said \"no wahala\" before I understood the wahala",
      whatToShow: "Show a fake chat where someone explains the plan in detail after you already replied 'no wahala.' You stare, then scroll back to your own message like you betrayed yourself.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "reading before replying is self-care.",
      anchor: "wahala",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-010 [REWRITE] · cluster: messages · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "phone expose my almost-there lie",
      whatToShow: "Show a fake message typed: 'almost there.' Cut to your hand plugging in the phone while you are clearly still at home.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "location: emotionally on the way.",
      anchor: "phone",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-011 [REWRITE] · cluster: transport
      hook: "transport fare expose my outside courage",
      whatToShow: "Show notes app with a fake transport budget. You add the transport numbers, pause, then slowly change your clothes back to house clothes.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "outside is now a subscription.",
      anchor: "transport",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-017 [REWRITE] · cluster: social_plan · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "small visit expose transport bill immediately",
      whatToShow: "Fake chat says 'just come small.' You show your wallet, your shoes, then the bed. The bed wins.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "\"small\" has transport cost.",
      anchor: "small",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-023 [REWRITE] · cluster: power
      hook: "one light blink killed my whole productivity",
      whatToShow: "Laptop open. The room light flickers. You freeze, save the document aggressively, then stare at the socket like it owes you stability.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "productivity needs electricity and emotional support.",
      anchor: "light",
      domain: "phone",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-031 [REWRITE] · cluster: food
      hook: "pot don expose my cooking lie",
      whatToShow: "Open a pot, look inside, close it slowly, then open a snack cupboard like you are switching departments.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "kitchen update: faith required.",
      anchor: "pot",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-035 [REWRITE] · cluster: home
      hook: "room expose the mess I tried to respect",
      whatToShow: "Show one item on the floor. You pick it up and reveal a bigger mess underneath. You put it back like the room has structure.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "organization by denial.",
      anchor: "room",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-041 · cluster: school
      hook: "I opened the assignment and my brain said \"abeg\"",
      whatToShow: "Show laptop or notebook with assignment. You read one line, scroll down, then slowly close the laptop halfway.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "academic courage loading.",
      anchor: "assignment",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-053 [REWRITE] · cluster: social_pressure
      hook: "bed save me before outside finish me",
      whatToShow: "Show you in bed receiving a fake call/message. You look at your blanket, then the phone, then pull the blanket higher.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "my bed has authority.",
      anchor: "bed",
      domain: "family",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-059 [REWRITE] · cluster: family_group · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "family chat beat mute and entered my peace",
      whatToShow: "Show fake family group chat muted. Notifications still pile up visually. You stare at the mute icon like it lied.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "mute button needs backup.",
      anchor: "chat",
      domain: "family",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-061 [REWRITE] · cluster: money · privacyNote: Use fake bank-alert mock; never a real account screen.
      hook: "balance slap my cart confidence back to reality",
      whatToShow: "Show a fake budget or fake bank-alert overlay. You open shopping cart, add one item, then look back at the fake balance like it will change.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "financial courage is not evidence.",
      anchor: "balance",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-063 [REWRITE] · cluster: bank_alert · privacyNote: Use fake bank-alert mock; never a real account screen.
      hook: "one debit alert exposed every bad decision",
      whatToShow: "Fake bank-alert overlay pops up. You freeze, open calculator, then close it because the math is disrespectful.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "fake alert, real emotion.",
      anchor: "alert",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-065 [REWRITE] · cluster: shopping
      hook: "checkout opened before my budget could defend itself",
      whatToShow: "Fake shopping app. You scroll, add to cart 'just to see,' then hover over checkout like your thumb has separate plans.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "window shopping with consequences.",
      anchor: "checkout",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-067 [REWRITE] · cluster: market
      hook: "list enter market and lose home training",
      whatToShow: "Show a shopping list with three items. Cut to bags with extras. You check the list like it betrayed you.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "the list lost control.",
      anchor: "list",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-069 · cluster: data_money
      hook: "data subscription humbled my enjoyment plan",
      whatToShow: "Fake data purchase screen. You choose the smaller plan, then open video app and immediately regret it.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "entertainment now has budget committee.",
      anchor: "data",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-071 [REWRITE] · cluster: creator
      hook: "post don go live, my peace don collapse",
      whatToShow: "Show fake post analytics. You refresh, wait, refresh again, then lock the screen like you are above it. Immediately unlock.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "peace after posting is a myth.",
      anchor: "post",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-073 [REWRITE] · cluster: comments
      hook: "one comment scatter my posting confidence live",
      whatToShow: "Show fake comment preview. You type a reply, delete it, type again, then close the app dramatically.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "mental press briefing.",
      anchor: "comment",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-083 [REWRITE] · cluster: bed
      hook: "bed disgrace my one-minute rest plan",
      whatToShow: "You sit on the bed 'for one minute.' Cut to you lying down with phone still in hand.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "meeting adjourned by sleep.",
      anchor: "bed",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-085 [REWRITE] · cluster: shoes
      hook: "shoes expose my leaving-house lie",
      whatToShow: "Show shoes on your feet while you sit on bed/couch scrolling. Cut to later, shoes still on, no movement.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "readiness without results.",
      anchor: "shoes",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-091 [REWRITE] · cluster: slippers
      hook: "slippers expose mission wey no even start",
      whatToShow: "Camera on slippers. You stand up, take two steps, then sit back down with slippers still ready.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "mission cancelled at launch.",
      anchor: "slippers",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-093 [REWRITE] · cluster: towel
      hook: "towel don expose my almost-ready lie",
      whatToShow: "Show towel/robe, phone message asking 'ready?' You type 'almost' while clearly nowhere near ready.",
      howToFilm: "Mirror lock-off, face out of frame, one take.",
      caption: "readiness is spiritual.",
      anchor: "towel",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-095 [REWRITE] · cluster: queue
      hook: "queue don humble my errand spirit",
      whatToShow: "Show a fake queue/line situation or text overlay. You look at the line, look at your phone, then turn around slowly.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "patience did not follow me.",
      anchor: "queue",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-108 [REWRITE] · cluster: group_admin · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "admin punish my greeting like spam get immunity",
      whatToShow: "You post one harmless 'good morning.' A fake admin warning pops up. Meanwhile, three people are posting forwarded prayers and nobody touches them.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "admin power is not democracy.",
      anchor: "admin",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-111 [REWRITE] · cluster: mute_unmute · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "mute betrayed me before the group even started",
      whatToShow: "Mute a noisy fake group. Five minutes later, open it yourself. Laugh at your lack of discipline and unmute like the problem is you.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "mute button could not save me.",
      anchor: "mute",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-114 [REWRITE] · cluster: poll_wahala · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "this poll betrayed my weekend in public",
      whatToShow: "Fake group poll about weekend plans. You vote yes. Everyone else votes no. You stare, then type 'una no get joy' and delete it.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "democracy hurt my feelings.",
      anchor: "poll",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-117 [REWRITE] · cluster: okada_promise
      hook: "bike shortcut turn my confidence to prayer",
      whatToShow: "On a bike POV-style shot, show the rider taking a wrong turn while your hand checks the map in panic.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "quick route, long testimony.",
      anchor: "bike",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-119 [REWRITE] · cluster: im_coming
      hook: "ironing exposed my 'I dey come' lie",
      whatToShow: "Type 'I'm coming now.' Cut to you still ironing or looking for socks while the time on your phone keeps moving.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "coming soon. allegedly.",
      anchor: "ironing",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-129 [REWRITE] · cluster: generator_noise
      hook: "generator drag sleep outside and disgrace am",
      whatToShow: "Try to sleep while generator hum plays. Pull pillow over your head, then remove it because it is somehow hotter.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "rest with soundtrack.",
      anchor: "generator",
      domain: "phone",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-146 [REWRITE] · cluster: generator_food
      hook: "freezer expose blackout before my chicken survived",
      whatToShow: "Open freezer during outage. Food is thawing. You check the clock, then the freezer, then the ceiling.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "chicken under pressure.",
      anchor: "freezer",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-151 · cluster: boss_email
      hook: "oga sent email at 11:59 p.m. like sleep is illegal",
      whatToShow: "You are about to sleep. Fake work email lands. You sit up slowly, open laptop, and stare at the screen.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "bedtime became office hours.",
      anchor: "email",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-153 [REWRITE] · cluster: submission_closed
      hook: "portal bury my courage with one closed page",
      whatToShow: "Keep postponing the upload. Refresh the portal and see closed status. Your hand freezes on the mouse.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "later has consequences.",
      anchor: "portal",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-165 · cluster: aunty_setup · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "aunty has one \"fine person\" for everybody",
      whatToShow: "Aunty shows a random profile or photo on fake WhatsApp. You lean back like the phone is too close to your destiny.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "matchmaking without consent.",
      anchor: "aunty",
      domain: "family",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-171 [REWRITE] · cluster: pay_back · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "pay don disgrace me before next month",
      whatToShow: "Open fake chat with old repayment promise. Next message is a meme instead of money.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "debt with comedy timing.",
      anchor: "pay",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-172 · cluster: airtime_data
      hook: "airtime finished, but somehow data is also judging me",
      whatToShow: "Try to buy airtime with slow network. App loads forever. You stare like even the phone is tired.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "connection without cooperation.",
      anchor: "airtime",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-177 [REWRITE] · cluster: caption
      hook: "caption fight me after video don finish",
      whatToShow: "Finished video ready. You type one caption, delete it, type another, then stare at blank space like it is an exam.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "caption humbled the creator.",
      anchor: "caption",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-181 [REWRITE] · cluster: no_content
      hook: "camera expose my brain wey resign live",
      whatToShow: "Sit in front of camera ready to film. Smile fades as you realize there is no idea. You slowly stop recording.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "camera ready. brain absent.",
      anchor: "camera",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-184 · cluster: tag_friends
      hook: "I tagged everybody and nobody reposted",
      whatToShow: "Fake post screen shows many tagged friends. No shares. You stare at the activity tab like it owes you loyalty.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "tag list without results.",
      anchor: "tag",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-187 [REWRITE] · cluster: pos_fee · privacyNote: Use fake bank-alert mock; never a real account screen.
      hook: "POS expose my no-cash shame instantly",
      whatToShow: "At a shop counter setup, you check your wallet, then see the POS extra charge. Your face drops slowly.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "payment method with plot twist.",
      anchor: "pos",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-191 [REWRITE] · cluster: market_bargain
      hook: "seller laugh scatter my price confidence",
      whatToShow: "At a market-style setup, seller gives price. You bargain too low. Seller laughs. You laugh too like it was a joke.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "bargaining as performance.",
      anchor: "seller",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-193 [REWRITE] · cluster: food_refusal
      hook: "my stomach exposed the 'I don chop' lie",
      whatToShow: "Someone offers food. You politely refuse. Your stomach makes noise while you look at the food too long.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "pride versus hunger.",
      anchor: "stomach",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-195 [REWRITE] · cluster: rain
      hook: "rain disgrace me before I even cross door",
      whatToShow: "Step outside. Rain hits. You run back in soaked, holding your phone like the only survivor.",
      howToFilm: "Door-side handheld, mid-shot, one take.",
      caption: "weather had agenda.",
      anchor: "rain",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-199 [REWRITE] · cluster: i_dey_fine
      hook: "fine leave my mouth, chaos expose my body",
      whatToShow: "Someone asks how you are. You say 'fine' while clearly tired, holding too many things, or sitting in chaos.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "fine, according to official statement.",
      anchor: "fine",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-202 [REWRITE] · cluster: gif_war · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "one GIF hijack the whole group question",
      whatToShow: "You ask 'who's free this weekend?' in a fake group chat. Friends reply with a running-away GIF and laughing reactions instead of answering.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "simple question, cinema reply.",
      anchor: "gif",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-204 · cluster: status_view_ghost · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "you viewed my status but still no reply?",
      whatToShow: "Check your fake status viewers list. The same friend who ignored your message is at the top. You open the chat and zoom into their profile picture like it owes you explanation.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "viewer, not responder.",
      anchor: "status",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-206 [REWRITE] · cluster: blue_tick · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "blue ticks expose reply wey disappear",
      whatToShow: "You send a long fake message. Blue ticks appear immediately. You keep checking the chat while doing chores, pretending you are not checking.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "read receipt with pain.",
      anchor: "ticks",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-210 [REWRITE] · cluster: forwarded_madness · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "one forward nearly make me public evidence",
      whatToShow: "You receive a dramatic fake forwarded message. You hesitate, shake your head, then almost forward it before stopping yourself.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "forwarding requires self-control.",
      anchor: "forward",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-212 [REWRITE] · cluster: muted_group · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "mute fail me, curiosity carry first position",
      whatToShow: "You mute a noisy fake group. Five minutes later, you open it yourself, laugh at your own lack of discipline, then keep scrolling.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "mute could not save me.",
      anchor: "mute",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-219 [REWRITE] · cluster: online_no_reply · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "online dey expose the reply wey japa",
      whatToShow: "Friend is online for 30 minutes but still has not replied. You watch the status like live sports.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "online without responsibility.",
      anchor: "online",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-221 [REWRITE] · cluster: okada_shortcut
      hook: "shortcut don disgrace my okada confidence",
      whatToShow: "On an okada-style POV, the rider takes a rough shortcut. You hold tight and check your map like prayer has entered the journey.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "shortcut with consequences.",
      anchor: "shortcut",
      domain: "transport",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-223 [REWRITE] · cluster: gate_lie · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "gate don expose me, keys still dey hide",
      whatToShow: "You type 'I'm at the gate' while still tying your shoe and looking for keys inside the house.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "location by confidence.",
      anchor: "gate",
      domain: "transport",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-228 [REWRITE] · cluster: last_bus
      hook: "last bus turn my body to emergency evidence",
      whatToShow: "You sprint toward a bus at night. You enter just as it starts moving and sit down breathing like you escaped destiny.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "cardio by transport.",
      anchor: "bus",
      domain: "transport",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-237 [REWRITE] · cluster: generator_noise
      hook: "generator carry my sleep enter street concert",
      whatToShow: "Neighbor's generator roars while you try to sleep. You cover your head with a pillow, then remove it because heat has joined the matter.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "sleep with soundtrack.",
      anchor: "generator",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-244 · cluster: background_data
      hook: "who dey use my data like this?",
      whatToShow: "Fake data usage screen shows one app used too much. You look at the phone like somebody must confess.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "data investigation unit.",
      anchor: "data",
      domain: "phone",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-251 · cluster: garri
      hook: "I left small garri this morning...",
      whatToShow: "Reach for the garri bag. It is empty. You shake it once like more might appear.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "garri betrayed me.",
      anchor: "garri",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-255 [REWRITE] · cluster: share_rice
      hook: "one spoon rob my plate in broad daylight",
      whatToShow: "You sit with food. Roommate enters and starts negotiating for one spoon. You pull the plate closer.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "one spoon has agenda.",
      anchor: "spoon",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-261 · cluster: boss_email · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "oga sent email at 11:58 p.m.",
      whatToShow: "You are about to sleep. Fake work email lands. You sit up slowly and open your laptop again.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "bedtime became office hours.",
      anchor: "email",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-266 [REWRITE] · cluster: zoom_camera_off
      hook: "camera off hide breakfast meeting evidence",
      whatToShow: "Join a fake Zoom meeting. Camera off, mic muted. You are quietly eating breakfast.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "attendance without presence.",
      anchor: "camera",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-269 [REWRITE] · cluster: traffic_work_lie · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "traffic expose my already-seated work lie",
      whatToShow: "You reply work messages professionally while clearly stuck in traffic.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "remote presence by faith.",
      anchor: "traffic",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-278 · cluster: matchmaking · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "aunty has one fine person for everybody",
      whatToShow: "Aunty shows a random profile on fake WhatsApp. You lean back like the phone is too close to destiny.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "matchmaking without consent.",
      anchor: "aunty",
      domain: "family",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-292 · cluster: caption_struggle
      hook: "caption dey harder than the video itself",
      whatToShow: "Finished video ready. You type, delete, and retype captions while the post screen stays open.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "caption humbled me.",
      anchor: "caption",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
    Object.freeze({
      // source: DRAFT-298 · cluster: tag_friends
      hook: "I tagged everybody and got zero shares",
      whatToShow: "Fake post shows many tagged friends. Activity stays empty. You stare at the screen like loyalty is under review.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "tag list without results.",
      anchor: "tag",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-06",
    }),
  ]);

// NOTE: A self-`assertNigerianPackIntegrity(...)` call was previously
// emitted here as a defense-in-depth boot check. It was REMOVED because
// `nigerianHookPack.ts` imports this file at module-top, creating a
// circular import. When the flag is ON the self-call would execute
// before `PACK_FIELD_BOUNDS` (declared LATER in `nigerianHookPack.ts`)
// finishes initializing → TDZ → `Cannot read properties of undefined`.
// Defense is preserved by:
//   (1) `validateRow` in `qa/buildApprovedNigerianPack.ts` running ALL
//       the same checks per-row at codegen time before this file is
//       written, and
//   (2) `assertNigerianPackIntegrity(NIGERIAN_HOOK_PACK)` in
//       `nigerianHookPack.ts` (run after PACK_FIELD_BOUNDS is
//       initialized), which validates the live pool when flag is ON.

// NOTE: The PHASE N1-Q `registerApprovedPoolReference(...)` self-call
// was REMOVED here for the same circular-import TDZ reason as the
// integrity assert above (`APPROVED_POOL_REF` lives in
// `nigerianHookQuality.ts` and is in TDZ when this module loads via
// the cycle from `nigerianHookPack.ts`). Registration of the live
// pool happens in `nigerianHookPack.ts` after `NIGERIAN_HOOK_PACK`
// is assigned (it's the same array reference when the flag is ON).
// Tests that need to grade the approved pool while the flag is OFF
// must register it explicitly via `registerApprovedPoolReference`.
