/**
 * REGIONAL N1 — APPROVED Nigerian promotion candidates.
 *
 * AUTO-GENERATED by `qa/buildApprovedNigerianPack.ts`. Do NOT edit by hand.
 * Re-run the generator to refresh after a new reviewer pass.
 *
 * STATUS: INERT. This array is NOT `NIGERIAN_HOOK_PACK`. The live pool
 * remains empty (DARK). A separate, explicit promotion step is required
 * to copy entries into the live pack, AND `LUMINA_NG_PACK_ENABLED=true`
 * must be set, before `canActivateNigerianPack` can return true.
 *
 * Cross-region leak remains impossible by construction: the central
 * activation guard still requires region === "nigeria" + non-clean
 * languageStyle even after promotion.
 *
 * Every entry below was re-validated against EVERY production rule:
 *   • reviewedBy non-empty AND not PENDING_NATIVE_REVIEW
 *   • pidginLevel ∈ {light_pidgin, pidgin}
 *   • hook/whatToShow/howToFilm/caption length bounds (PACK_FIELD_BOUNDS)
 *   • anchor (lowercase) present in BOTH hook AND whatToShow
 *   • no PIDGIN_MOCKING_PATTERNS hit on hook/whatToShow/caption
 *   • validateScenarioCoherence(idea) === null
 *   • scoreHookQuality(hook) >= 40
 *
 * INGEST SUMMARY: 34 approved · 16 rejected
 *
 * REJECTED ROWS (kept here for the reviewer audit trail; NOT in the
 * exported array — the generator does not silently fix anything):
 *   • DRAFT-053 [REWRITE] → scoreHookQuality 35 < floor 40
 *   • DRAFT-061 [REWRITE] → scoreHookQuality 35 < floor 40
 *   • DRAFT-073 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-108 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-117 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-129 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-153 [REWRITE] → scoreHookQuality 28 < floor 40
 *   • DRAFT-171 [REWRITE] → scoreHookQuality 22 < floor 40
 *   • DRAFT-177 [REWRITE] → scoreHookQuality 35 < floor 40
 *   • DRAFT-191 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-195 [REWRITE] → scoreHookQuality 38 < floor 40
 *   • DRAFT-210 [REWRITE] → scoreHookQuality 35 < floor 40
 *   • DRAFT-212 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-228 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-237 [REWRITE] → scoreHookQuality 25 < floor 40
 *   • DRAFT-255 [REWRITE] → scoreHookQuality 35 < floor 40
 */

import {
  assertNigerianPackIntegrity,
  type NigerianPackEntry,
} from "./nigerianHookPack.js";

export const APPROVED_NIGERIAN_PROMOTION_CANDIDATES: readonly NigerianPackEntry[] =
  Object.freeze([
    Object.freeze({
      // source: DRAFT-006 [REWRITE] · cluster: group_chat · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "group chat don hijack my whole peace",
      whatToShow: "Fake group chat shows five people tagging you. You type one reply, delete it, then just send a thumbs-up emoji and look away like that solved governance.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "leadership by emoji.",
      anchor: "group",
      domain: "messaging",
      pidginLevel: "pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-010 [REWRITE] · cluster: messages · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "phone expose my almost-there lie",
      whatToShow: "Show a fake message typed: 'almost there.' Cut to your hand plugging in the phone while you are clearly still at home.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "location: emotionally on the way.",
      anchor: "phone",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-011 [REWRITE] · cluster: transport
      hook: "transport fare expose my outside courage",
      whatToShow: "Show notes app with a fake transport budget. You add the transport numbers, pause, then slowly change your clothes back to house clothes.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "outside is now a subscription.",
      anchor: "transport",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-017 [REWRITE] · cluster: social_plan · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "small visit expose transport bill immediately",
      whatToShow: "Fake chat says 'just come small.' You show your wallet, your shoes, then the bed. The bed wins.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "\"small\" has transport cost.",
      anchor: "small",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-031 [REWRITE] · cluster: food
      hook: "the pot opened and hope left the kitchen",
      whatToShow: "Open a pot, look inside, close it slowly, then open a snack cupboard like you are switching departments.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "kitchen update: faith required.",
      anchor: "pot",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-035 [REWRITE] · cluster: home
      hook: "room expose the mess I tried to respect",
      whatToShow: "Show one item on the floor. You pick it up and reveal a bigger mess underneath. You put it back like the room has structure.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "organization by denial.",
      anchor: "room",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-059 [REWRITE] · cluster: family_group · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "family chat beat mute and entered my peace",
      whatToShow: "Show fake family group chat muted. Notifications still pile up visually. You stare at the mute icon like it lied.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "mute button needs backup.",
      anchor: "chat",
      domain: "family",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-063 [REWRITE] · cluster: bank_alert · privacyNote: Use fake bank-alert mock; never a real account screen.
      hook: "one debit alert exposed every bad decision",
      whatToShow: "Fake bank-alert overlay pops up. You freeze, open calculator, then close it because the math is disrespectful.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "fake alert, real emotion.",
      anchor: "alert",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-065 [REWRITE] · cluster: shopping
      hook: "checkout opened before my budget could defend itself",
      whatToShow: "Fake shopping app. You scroll, add to cart 'just to see,' then hover over checkout like your thumb has separate plans.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "window shopping with consequences.",
      anchor: "checkout",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-067 [REWRITE] · cluster: market
      hook: "list enter market and lose home training",
      whatToShow: "Show a shopping list with three items. Cut to bags with extras. You check the list like it betrayed you.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "the list lost control.",
      anchor: "list",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-083 [REWRITE] · cluster: bed
      hook: "bed disgrace my one-minute rest plan",
      whatToShow: "You sit on the bed 'for one minute.' Cut to you lying down with phone still in hand.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "meeting adjourned by sleep.",
      anchor: "bed",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-085 [REWRITE] · cluster: shoes
      hook: "shoes expose my leaving-house lie",
      whatToShow: "Show shoes on your feet while you sit on bed/couch scrolling. Cut to later, shoes still on, no movement.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "readiness without results.",
      anchor: "shoes",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-091 [REWRITE] · cluster: slippers
      hook: "slippers expose mission wey no even start",
      whatToShow: "Camera on slippers. You stand up, take two steps, then sit back down with slippers still ready.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "mission cancelled at launch.",
      anchor: "slippers",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-093 · cluster: towel
      hook: "I said \"almost ready\" while still negotiating with towel",
      whatToShow: "Show towel/robe, phone message asking 'ready?' You type 'almost' while clearly nowhere near ready.",
      howToFilm: "Mirror lock-off, face out of frame, one take.",
      caption: "readiness is spiritual.",
      anchor: "towel",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-095 [REWRITE] · cluster: queue
      hook: "the queue looked at me and cancelled the errand",
      whatToShow: "Show a fake queue/line situation or text overlay. You look at the line, look at your phone, then turn around slowly.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "patience did not follow me.",
      anchor: "queue",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-111 [REWRITE] · cluster: mute_unmute · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "mute betrayed me before the group even started",
      whatToShow: "Mute a noisy fake group. Five minutes later, open it yourself. Laugh at your lack of discipline and unmute like the problem is you.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "mute button could not save me.",
      anchor: "mute",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-114 [REWRITE] · cluster: poll_wahala · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "this poll betrayed my weekend in public",
      whatToShow: "Fake group poll about weekend plans. You vote yes. Everyone else votes no. You stare, then type 'una no get joy' and delete it.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "democracy hurt my feelings.",
      anchor: "poll",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-119 [REWRITE] · cluster: im_coming
      hook: "ironing exposed my 'I dey come' lie",
      whatToShow: "Type 'I'm coming now.' Cut to you still ironing or looking for socks while the time on your phone keeps moving.",
      howToFilm: "Bed-level handheld, low angle, one take.",
      caption: "coming soon. allegedly.",
      anchor: "ironing",
      domain: "movement",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-146 [REWRITE] · cluster: generator_food
      hook: "freezer expose blackout before my chicken survived",
      whatToShow: "Open freezer during outage. Food is thawing. You check the clock, then the freezer, then the ceiling.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "chicken under pressure.",
      anchor: "freezer",
      domain: "home",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-172 · cluster: airtime_data
      hook: "airtime finished, but somehow data is also judging me",
      whatToShow: "Try to buy airtime with slow network. App loads forever. You stare like even the phone is tired.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "connection without cooperation.",
      anchor: "airtime",
      domain: "money",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-181 [REWRITE] · cluster: no_content
      hook: "camera expose my brain wey resign live",
      whatToShow: "Sit in front of camera ready to film. Smile fades as you realize there is no idea. You slowly stop recording.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "camera ready. brain absent.",
      anchor: "camera",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-187 [REWRITE] · cluster: pos_fee · privacyNote: Use fake bank-alert mock; never a real account screen.
      hook: "POS expose my no-cash shame instantly",
      whatToShow: "At a shop counter setup, you check your wallet, then see the POS extra charge. Your face drops slowly.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "payment method with plot twist.",
      anchor: "pos",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-193 [REWRITE] · cluster: food_refusal
      hook: "my stomach exposed the 'I don chop' lie",
      whatToShow: "Someone offers food. You politely refuse. Your stomach makes noise while you look at the food too long.",
      howToFilm: "Counter-level lock-off, daylight, one take.",
      caption: "pride versus hunger.",
      anchor: "stomach",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-199 [REWRITE] · cluster: i_dey_fine
      hook: "fine leave my mouth, chaos expose my body",
      whatToShow: "Someone asks how you are. You say 'fine' while clearly tired, holding too many things, or sitting in chaos.",
      howToFilm: "Couch-level handheld, mid-shot, one take.",
      caption: "fine, according to official statement.",
      anchor: "fine",
      domain: "everyday",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-202 [REWRITE] · cluster: gif_war · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "one GIF hijack the whole group question",
      whatToShow: "You ask 'who's free this weekend?' in a fake group chat. Friends reply with a running-away GIF and laughing reactions instead of answering.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "simple question, cinema reply.",
      anchor: "gif",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-206 [REWRITE] · cluster: blue_tick · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "blue ticks expose reply wey disappear",
      whatToShow: "You send a long fake message. Blue ticks appear immediately. You keep checking the chat while doing chores, pretending you are not checking.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "read receipt with pain.",
      anchor: "ticks",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-219 [REWRITE] · cluster: online_no_reply · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "online dey expose the reply wey japa",
      whatToShow: "Friend is online for 30 minutes but still has not replied. You watch the status like live sports.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "online without responsibility.",
      anchor: "online",
      domain: "messaging",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-221 · cluster: okada_shortcut
      hook: "'I know shortcut' is where the story started",
      whatToShow: "On an okada-style POV, the rider takes a rough shortcut. You hold tight and check your map like prayer has entered the journey.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "shortcut with consequences.",
      anchor: "shortcut",
      domain: "transport",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-223 [REWRITE] · cluster: gate_lie · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "gate don expose me, keys still dey hide",
      whatToShow: "You type 'I'm at the gate' while still tying your shoe and looking for keys inside the house.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "location by confidence.",
      anchor: "gate",
      domain: "transport",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-266 [REWRITE] · cluster: zoom_camera_off
      hook: "camera off hide breakfast meeting evidence",
      whatToShow: "Join a fake Zoom meeting. Camera off, mic muted. You are quietly eating breakfast.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "attendance without presence.",
      anchor: "camera",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-269 [REWRITE] · cluster: traffic_work_lie · privacyNote: Use fake screenshots / mock chats only; never real contacts.
      hook: "traffic expose my already-seated work lie",
      whatToShow: "You reply work messages professionally while clearly stuck in traffic.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "remote presence by faith.",
      anchor: "traffic",
      domain: "work",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-292 · cluster: caption_struggle
      hook: "caption dey harder than the video itself",
      whatToShow: "Finished video ready. You type, delete, and retype captions while the post screen stays open.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "caption humbled me.",
      anchor: "caption",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-023 [REWRITE] · cluster: power
      hook: "one light blink killed my whole productivity",
      whatToShow: "Laptop open. The room light flickers. You freeze, save the document aggressively, then stare at the socket like it owes you stability.",
      howToFilm: "Desk-height lock-off, soft daylight, one take.",
      caption: "productivity needs electricity and emotional support.",
      anchor: "light",
      domain: "phone",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
    Object.freeze({
      // source: DRAFT-071 [REWRITE] · cluster: creator
      hook: "post don go live, my peace don collapse",
      whatToShow: "Show fake post analytics. You refresh, wait, refresh again, then lock the screen like you are above it. Immediately unlock.",
      howToFilm: "Phone-level lock-off, soft daylight, one take.",
      caption: "peace after posting is a myth.",
      anchor: "post",
      domain: "creator",
      pidginLevel: "light_pidgin",
      reviewedBy: "BI 2026-05-05",
    }),
  ]);

// Defense in depth: re-run the production boot assert against the
// generated array at module load. If anything regresses (e.g. a future
// regenerate produces a row that violates a tightened rule) this throws
// before the file can be imported by tests or any downstream module.
assertNigerianPackIntegrity(APPROVED_NIGERIAN_PROMOTION_CANDIDATES);
