/**
 * PHASE N1-STYLE — Cohort-gated American-internet style penalty for
 * non-pack catalog hooks targeted at NG-pidgin / NG-light_pidgin
 * users.
 *
 * MOTIVATION
 * ----------
 * The N1 throttle instrumentation (`.local/N1_THROTTLE_INSTRUMENTATION.md`)
 * confirmed that ~29% of non-pack catalog hooks shipped to NG-pidgin
 * cohorts trip American Gen-Z internet patterns ("villain arc",
 * "co-conspirator", "demolished my entire vibe", "ruined my villain
 * arc"). Those hooks read foreign to a Nigerian audience. They are
 * generated by the catalog recipe path, not the pack — so growing
 * the pack cannot displace them. This module attaches a SOFT score
 * penalty to such hooks so authentic catalog recipes (and pack
 * candidates) outscore them inside the per-core `passing[]`
 * competition in `coreCandidateGenerator.ts`.
 *
 * HARD-RULE COMPLIANCE
 * --------------------
 *   • Cohort-gated. Returns 0 unless region === "nigeria" AND
 *     languageStyle ∈ {pidgin, light_pidgin} AND the
 *     `LUMINA_NG_STYLE_PENALTY_ENABLED` env flag is "true". Western,
 *     India, PH, and NG-clean cohorts see ZERO penalty — byte-
 *     identical to baseline behavior. Same activation discipline as
 *     the N1 pack itself (`canActivateNigerianPack`).
 *   • Soft penalty (subtraction from a 0-100 quality scale), not a
 *     filter. A penalized catalog hook can still ship if no better
 *     candidate exists; the goal is to LOSE the per-core quality
 *     competition to authentic alternatives, not to be excluded.
 *   • Production stays OFF by default — the new flag defaults to
 *     unset, so this module is a no-op everywhere until staging QA
 *     proves the penalty is calibrated correctly.
 *   • No validator touched. No `scoreHookQuality` source modified.
 *     Penalty applied at the call site by subtraction, leaving
 *     `scoreHookQuality` itself byte-identical to baseline.
 *   • Pack candidates MUST NOT be penalized. Wiring in
 *     `coreCandidateGenerator.ts` calls this only on the catalog
 *     path (L1150 site), never on the pack-prefix path (L1010 site).
 */

import type { Region } from "@workspace/lumina-trends";
import type { LanguageStyle } from "./tasteCalibration.js";

/**
 * Curated American Gen-Z / TikTok-internet phrasings that read as
 * stylistically wrong for a Nigerian-Pidgin audience. Source: the
 * 47 confirmed hits from the N1 throttle audit
 * (`.local/N1_THROTTLE_INSTRUMENTATION.md` Part 2). Patterns are
 * INTENTIONALLY narrow — each one has a clear English-internet
 * register and zero overlap with authentic Pidgin cadence.
 *
 * Adding a pattern: must be a phrase, not a single common word, and
 * must not match any entry in `NIGERIAN_HOOK_PACK`. The unit test
 * for this module covers both directions to enforce.
 */
export const AMERICAN_INTERNET_PATTERNS: ReadonlyArray<RegExp> = [
  /\bvillain arc\b/i,
  /\bdemolished my (entire )?vibe\b/i,
  /\bruined my (entire )?(vibe|villain|day)\b/i,
  /\bkill(ed|ing)? my vibe\b/i,
  /\bcaught (in )?(4k|the act)\b/i,
  /\bco[- ]conspirator/i,
  /\bavoiding (it|itself|myself)\b/i,
  /\bkeeps? revealing itself\b/i,
  /\b(the|my) \w+ itself is (the|my)\b/i,
  /\bpersonality (is|itself)\b/i,
  /\bthe \w+ ate my\b/i,
  /\bmain character\b/i,
  /\bnot (me|him|her|them) \w+ing\b/i,
  /\bthe \w+ ruined\b/i,
  /\blived rent[- ]free\b/i,
  /\bunhinged\b/i,
];

/**
 * Per-match penalty applied to `scoreHookQuality` (0-100 scale).
 * 20 points is meaningful enough to typically lose to an authentic
 * catalog recipe (which scores 40-80 in practice) without being a
 * hard filter — a penalized hook with no competing candidate still
 * ships. Compound matches sum then cap at PENALTY_CAP.
 */
export const STYLE_PENALTY_PER_MATCH = 20;
export const STYLE_PENALTY_CAP = 60;

export function isNigerianStylePenaltyFeatureEnabled(): boolean {
  return process.env.LUMINA_NG_STYLE_PENALTY_ENABLED === "true";
}

export interface StylePenaltyInput {
  hook: string;
  region: Region | undefined;
  languageStyle: LanguageStyle | null;
  flagEnabled: boolean;
}

/**
 * Activation gate. Mirrors the four-AND discipline of
 * `canActivateNigerianPack`: same region, same language-style set,
 * same flag pattern. Western / India / PH / NG-clean / flag-off all
 * short-circuit to 0 penalty so non-NG-pidgin cohorts are
 * byte-identical to baseline.
 */
function canApplyNigerianStylePenalty(
  input: Pick<StylePenaltyInput, "region" | "languageStyle" | "flagEnabled">,
): boolean {
  if (!input.flagEnabled) return false;
  if (input.region !== "nigeria") return false;
  if (
    input.languageStyle !== "pidgin" &&
    input.languageStyle !== "light_pidgin"
  ) {
    return false;
  }
  return true;
}

/**
 * Returns a non-negative number to SUBTRACT from the catalog hook's
 * `scoreHookQuality` result. Returns 0 for any cohort that doesn't
 * pass the activation gate, so the wiring in
 * `coreCandidateGenerator.ts` is `quality - computeNigerianStylePenalty(...)`
 * with no branching at the call site.
 */
export function computeNigerianStylePenalty(input: StylePenaltyInput): number {
  if (!canApplyNigerianStylePenalty(input)) return 0;
  let matches = 0;
  for (const pattern of AMERICAN_INTERNET_PATTERNS) {
    if (pattern.test(input.hook)) matches += 1;
  }
  if (matches === 0) return 0;
  return Math.min(matches * STYLE_PENALTY_PER_MATCH, STYLE_PENALTY_CAP);
}
