/**
   * PHASE W2-T — curated W2-T-DIVERSITY promotion entries (DARK by
   * default; surfaced through the W2-K runtime path via
   * `westernHookPackApproved.ts`).
   *
   * 100 editorial-curated Western hooks (W2-T-DIVERSITY-001..100)
   * targeting the W2-S diversity gaps: phone/screen ratio
   * (62% → <35%), bathroom/mirror, hallway/doorway, parked car,
   * physical body, leaving-house delay, getting-ready/closet,
   * social/object comedy diversity. Imported under the same Path A
   * guardrails the W2-L / W2-N imports established:
   *
   *   • single runtime path — entries flow through the SAME approved
   *     pool that W2-K activated. Live promotion happens via the
   *     W2-O `westernHookPackLive` rubric, which scores this batch
   *     on module load alongside the other curated batches.
   *   • howToFilm is SYNTHESIZED deterministically per entry from the
   *     curated WHAT TO SHOW (each entry's actual beat narration),
   *     prefixed with a tripod/single-shot framing directive and
   *     suffixed with a voice-cluster-keyed payoff cue.
   *   • caption is synthesized deterministically per entry from
   *     (emotionalSpike × anchor × distinctive hook token).
   *   • freeform vocab from the curated batch (Comedy family,
   *     Emotional spike, Setting) is normalized into the EXISTING
   *     `WESTERN_COMEDY_FAMILIES` / `WESTERN_EMOTIONAL_SPIKES` /
   *     `WESTERN_SETTINGS` controlled vocab — no enum widening.
   *     See `.local/W2T_BUILD_REPORT.md` § Vocab remaps for the
   *     curated→controlled mappings (e.g. object_betrayal →
   *     parasocial_object, sink → bathroom, parked_car → car).
   *   • voiceCluster is normalized into `WESTERN_VOICE_CLUSTERS`.
   *   • hookStyle is normalized into `WESTERN_BATCH_HOOK_STYLES`.
   *   • safetyNote is preserved verbatim from the curated batch on
   *     entries that carry one (entries marked "None." leave the
   *     optional field unset). Parked-car entries always carry the
   *     "Film while parked only. Do not film while driving." note.
   *   • originalBatchNumber preserves the W2-T-DIVERSITY row number
   *     (1..100). Owning batch label resolved by
   *     `getWesternEntrySourceBatch` → "W2-T-DIVERSITY".
   *   • whyThisWorks intentionally NOT carried on the runtime entry —
   *     it lives in the curated source attachment + the W2-T import
   *     report (`.local/W2T_BUILD_REPORT.md`).
   *   • anchor is normalized to a single lowercase token that appears
   *     (lowercased) in whatToShow.
   *
   * Cross-batch dedup verified at import time vs:
   *   • `APPROVED_WESTERN_PROMOTION_CANDIDATES` (W2I 100 + W2-L 100
   *     + W2-N 100)
   *   • `WESTERN_HOOK_PACK_DRAFT` (150)
   *   • `userBlessedHookCorpus.ts` (532)
   *   • this batch's own running set
   *
   * Production stays OFF — gating still flows through
   * `isWesternApprovedPoolFeatureEnabled` +
   * `canActivateWesternApprovedPool` (staging) and the W2-O
   * `isWesternLivePoolFeatureEnabled` +
   * `canActivateWesternLivePool` (live).
   */

  import {
    PENDING_EDITORIAL_REVIEW,
    type WesternHookPackDraftEntry,
  } from "./westernHookPack.js";

  export const WESTERN_HOOK_PACK_DIVERSITY_IDS: readonly string[] =
    Object.freeze([
    "w2_t_diversity_001",
    "w2_t_diversity_002",
    "w2_t_diversity_003",
    "w2_t_diversity_004",
    "w2_t_diversity_005",
    "w2_t_diversity_006",
    "w2_t_diversity_007",
    "w2_t_diversity_008",
    "w2_t_diversity_009",
    "w2_t_diversity_010",
    "w2_t_diversity_011",
    "w2_t_diversity_012",
    "w2_t_diversity_013",
    "w2_t_diversity_014",
    "w2_t_diversity_015",
    "w2_t_diversity_016",
    "w2_t_diversity_017",
    "w2_t_diversity_018",
    "w2_t_diversity_019",
    "w2_t_diversity_020",
    "w2_t_diversity_021",
    "w2_t_diversity_022",
    "w2_t_diversity_023",
    "w2_t_diversity_024",
    "w2_t_diversity_025",
    "w2_t_diversity_026",
    "w2_t_diversity_027",
    "w2_t_diversity_028",
    "w2_t_diversity_029",
    "w2_t_diversity_030",
    "w2_t_diversity_031",
    "w2_t_diversity_032",
    "w2_t_diversity_033",
    "w2_t_diversity_034",
    "w2_t_diversity_035",
    "w2_t_diversity_036",
    "w2_t_diversity_037",
    "w2_t_diversity_038",
    "w2_t_diversity_039",
    "w2_t_diversity_040",
    "w2_t_diversity_041",
    "w2_t_diversity_042",
    "w2_t_diversity_043",
    "w2_t_diversity_044",
    "w2_t_diversity_045",
    "w2_t_diversity_046",
    "w2_t_diversity_047",
    "w2_t_diversity_048",
    "w2_t_diversity_049",
    "w2_t_diversity_050",
    "w2_t_diversity_051",
    "w2_t_diversity_052",
    "w2_t_diversity_053",
    "w2_t_diversity_054",
    "w2_t_diversity_055",
    "w2_t_diversity_056",
    "w2_t_diversity_057",
    "w2_t_diversity_058",
    "w2_t_diversity_059",
    "w2_t_diversity_060",
    "w2_t_diversity_061",
    "w2_t_diversity_062",
    "w2_t_diversity_063",
    "w2_t_diversity_064",
    "w2_t_diversity_065",
    "w2_t_diversity_066",
    "w2_t_diversity_067",
    "w2_t_diversity_068",
    "w2_t_diversity_069",
    "w2_t_diversity_070",
    "w2_t_diversity_071",
    "w2_t_diversity_072",
    "w2_t_diversity_073",
    "w2_t_diversity_074",
    "w2_t_diversity_075",
    "w2_t_diversity_076",
    "w2_t_diversity_077",
    "w2_t_diversity_078",
    "w2_t_diversity_079",
    "w2_t_diversity_080",
    "w2_t_diversity_081",
    "w2_t_diversity_082",
    "w2_t_diversity_083",
    "w2_t_diversity_084",
    "w2_t_diversity_085",
    "w2_t_diversity_086",
    "w2_t_diversity_087",
    "w2_t_diversity_088",
    "w2_t_diversity_089",
    "w2_t_diversity_090",
    "w2_t_diversity_091",
    "w2_t_diversity_092",
    "w2_t_diversity_093",
    "w2_t_diversity_094",
    "w2_t_diversity_095",
    "w2_t_diversity_096",
    "w2_t_diversity_097",
    "w2_t_diversity_098",
    "w2_t_diversity_099",
    "w2_t_diversity_100",
    ]);

  export const WESTERN_HOOK_PACK_DIVERSITY: readonly WesternHookPackDraftEntry[] =
    Object.freeze([
  {
    id: "w2_t_diversity_001",
    hook: "Mirror check turned into a full investigation",
    whatToShow: "Stand at the mirror ready to leave, then slowly lean closer, checking hair, collar, face, and outfit like you found evidence.",
    howToFilm: "Start with a normal mirror check. Lean closer beat by beat, checking hair, collar, face, and outfit until the mirror feels like evidence. Hold the final stare for one dry pause.",
    caption: "mirror check became a full audit.",
    anchor: "mirror",
    comedyFamily: "getting_ready",
    emotionalSpike: "private_embarrassment",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 1,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_002",
    hook: "The towel fell and took my patience with it",
    whatToShow: "Wrap or hang a towel, watch the towel fall immediately, then stare at it like it personally escalated the morning.",
    howToFilm: "Frame the towel clearly. Wrap or hang it, let it fall immediately, then stare at the towel with silent morning rage.",
    caption: "towel chose conflict today.",
    anchor: "towel",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bathroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 2,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_003",
    hook: "My toothbrush started a side quest",
    whatToShow: "Pick up a toothbrush, then accidentally clean the sink, move bottles, and reorganize the counter before brushing.",
    howToFilm: "Start with the toothbrush in hand. Before brushing, drift into cleaning the sink, moving bottles, and reorganizing the counter. End on the realization that brushing never happened.",
    caption: "toothbrush opened a side quest.",
    anchor: "toothbrush",
    comedyFamily: "task_avoidance",
    emotionalSpike: "time_loss",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 3,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_004",
    hook: "The sink looked clean until I got confident",
    whatToShow: "Lean over the sink proudly, then notice one tiny mess and start wiping more and more of the counter.",
    howToFilm: "Lean over the sink like the bathroom is handled. Spot one tiny mess, wipe it, then keep wiping more of the counter until confidence visibly leaves.",
    caption: "sink confidence lasted seconds.",
    anchor: "sink",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "instant_regret",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 4,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_005",
    hook: "My hair chose violence at the worst time",
    whatToShow: "Face the mirror with one piece of hair sticking out, fix it, then watch another section pop up worse.",
    howToFilm: "Face the mirror with one piece of hair sticking out. Fix it carefully, then reveal another section popping up worse. Let the final look say the hair won.",
    caption: "hair picked the worst time.",
    anchor: "hair",
    comedyFamily: "getting_ready",
    emotionalSpike: "panic",
    setting: "mirror",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 5,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_006",
    hook: "The bathroom counter exposed my planning system",
    whatToShow: "Pan across the bathroom counter: comb, lotion, towel, cup, and random objects scattered like a failed command center.",
    howToFilm: "Show the bathroom counter in a slow pass: comb, lotion, towel, cup, and random objects scattered everywhere. End on the creator staring at the counter in quiet defeat.",
    caption: "counter exposed the system.",
    anchor: "counter",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_realization",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide private products or labels if needed.",
    originalBatchNumber: 6,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_007",
    hook: "I washed my face and trusted the universe",
    whatToShow: "Wash at the sink, look refreshed in the mirror, then immediately notice a shirt stain or hair problem.",
    howToFilm: "Phone on a tripod, one locked-off shot. wash at the sink, look refreshed in the mirror, then immediately notice a shirt stain or hair problem. Keep your face flat the whole time; let the silence land.",
    caption: "sink washed earned no real points.",
    anchor: "sink",
    comedyFamily: "task_avoidance",
    emotionalSpike: "false_productivity",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 7,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_008",
    hook: "The mirror approved nothing and explained everything",
    whatToShow: "Step into the mirror frame confidently, freeze, then slowly remove one accessory, jacket, or hat.",
    howToFilm: "Step into the mirror confidently. Freeze when the reflection disagrees, then slowly remove one accessory, jacket, or hat like the mirror made the call.",
    caption: "mirror vetoed the outfit.",
    anchor: "frame",
    comedyFamily: "getting_ready",
    emotionalSpike: "private_embarrassment",
    setting: "mirror",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 8,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_009",
    hook: "My towel wrap had other plans",
    whatToShow: "Secure a towel wrap, take one confident step, then catch the towel slipping and freeze in panic.",
    howToFilm: "Secure the towel wrap and take one confident step. Catch the towel slipping, freeze, and let the panic land without overacting.",
    caption: "towel wrap had plans.",
    anchor: "towel",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "bathroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Keep framing modest and comfortable.",
    originalBatchNumber: 9,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_010",
    hook: "Skincare made me act employed by my face",
    whatToShow: "Line up simple skincare items by the mirror, apply one thing carefully, then nod like you managed a department.",
    howToFilm: "Phone on a tripod, one locked-off shot. line up simple skincare items by the mirror, apply one thing carefully, then nod like you managed a department. Keep your face flat the whole time; let the silence land.",
    caption: "mirror skincare earned no real points.",
    anchor: "mirror",
    comedyFamily: "getting_ready",
    emotionalSpike: "false_productivity",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid medical or skin-condition claims.",
    originalBatchNumber: 10,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_011",
    hook: "The hand towel refused basic cooperation",
    whatToShow: "Dry your hands with a hand towel, try to hang it neatly, then watch it slide down twice.",
    howToFilm: "Dry your hands, hang the hand towel neatly, and watch it slide down. Try once more, let it slide again, then hold the polite rage.",
    caption: "hand towel refused order.",
    anchor: "hands",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 11,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_012",
    hook: "I practiced one smile and found twelve problems",
    whatToShow: "Smile into the mirror, adjust posture, change angle, then give up and make a neutral face.",
    howToFilm: "Smile into the mirror like it is a quick check. Adjust posture, change angle, find another problem, then give up into a neutral face.",
    caption: "one smile found twelve issues.",
    anchor: "mirror",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "mirror",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 12,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_013",
    hook: "Bathroom light changed my whole identity",
    whatToShow: "Turn on the bathroom light, look in the mirror, then physically step back like the lighting told the truth.",
    howToFilm: "Turn on the bathroom light and look in the mirror. Step back physically when the lighting hits, like the room just told the truth.",
    caption: "bathroom light got honest.",
    anchor: "light",
    comedyFamily: "getting_ready",
    emotionalSpike: "caught_off_guard",
    setting: "bathroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "accusation",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 13,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_014",
    hook: "My robe belt became a physics problem",
    whatToShow: "Try tying a robe belt, accidentally make it uneven, then keep adjusting until it looks worse.",
    howToFilm: "Tie the robe belt once, notice it is uneven, then keep adjusting until it somehow looks worse. End on the confused pause.",
    caption: "robe belt became math.",
    anchor: "belt",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "confused_pause",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Keep framing modest and comfortable.",
    originalBatchNumber: 14,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_015",
    hook: "The sink splash humbled my whole outfit",
    whatToShow: "Use the sink carefully, then look down at a fresh water spot on your shirt and freeze.",
    howToFilm: "Use the sink carefully, then look down at the water spot on your shirt. Freeze like the outfit has officially been humbled.",
    caption: "sink humbled the outfit.",
    anchor: "shirt",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "instant_regret",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 15,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_016",
    hook: "Getting ready became mostly moving bottles around",
    whatToShow: "Reach for one item on the bathroom counter, move three bottles, lose the first item, then stare at the mess.",
    howToFilm: "Reach for one item on the bathroom counter. Move three bottles, lose the first item, then stare at the counter like it became a puzzle.",
    caption: "getting ready became logistics.",
    anchor: "counter",
    comedyFamily: "getting_ready",
    emotionalSpike: "time_loss",
    setting: "bathroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Hide private labels if needed.",
    originalBatchNumber: 16,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_017",
    hook: "I reached the door and forgot the mission",
    whatToShow: "Stand at the doorway holding keys, touch the door handle, then freeze and look back into the room confused.",
    howToFilm: "Stand at the doorway holding keys. Touch the door handle, freeze, then look back into the room like the mission disappeared.",
    caption: "doorway erased the mission.",
    anchor: "doorway",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "confused_pause",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "realization",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 17,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_018",
    hook: "One shoe on and the plan collapsed",
    whatToShow: "Put on one shoe at the front door, then sit there holding the other shoe while remembering another task.",
    howToFilm: "Put on one shoe at the front door. Sit holding the other shoe while remembering another task, then let the one-shoe pause become the punchline.",
    caption: "one shoe ended momentum.",
    anchor: "task",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "time_loss",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 18,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_019",
    hook: "The doorknob asked if I was actually ready",
    whatToShow: "Reach for the doorknob confidently, stop mid-grab, then pat pockets and check your bag again.",
    howToFilm: "Reach for the doorknob confidently. Stop mid-grab, pat your pockets, check the bag, and let the doorknob become the doubt trigger.",
    caption: "doorknob asked too much.",
    anchor: "doorknob",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 19,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_020",
    hook: "My bag got packed and immediately became suspicious",
    whatToShow: "Zip a bag at the doorway, pick it up, pause, then unpack one item to check if it exists.",
    howToFilm: "Zip the bag at the doorway and pick it up. Pause, unzip it, and check one item like the packed bag suddenly cannot be trusted.",
    caption: "packed bag got suspicious.",
    anchor: "bag",
    comedyFamily: "adulting_panic",
    emotionalSpike: "avoidance_spike",
    setting: "entryway",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Do not show IDs, cards, or private documents.",
    originalBatchNumber: 20,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_021",
    hook: "The hallway erased my entire purpose",
    whatToShow: "Walk into the hallway with purpose, stop suddenly, turn around, then re-enter the room confused.",
    howToFilm: "Walk into the hallway with purpose. Stop suddenly, turn around, and re-enter the room confused like the hallway deleted the plan.",
    caption: "hallway deleted the purpose.",
    anchor: "hallway",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "confused_pause",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid filming neighbors or private building details.",
    originalBatchNumber: 21,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_022",
    hook: "My coat joined the argument too late",
    whatToShow: "Reach the doorway ready to leave, notice the coat, put it on, then realize the outfit feels wrong.",
    howToFilm: "Reach the doorway ready to leave. Notice the coat, put it on, then realize the whole outfit has changed for the worse.",
    caption: "coat joined too late.",
    anchor: "coat",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "instant_regret",
    setting: "entryway",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 22,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_023",
    hook: "I opened the door and remembered three emergencies",
    whatToShow: "Crack open the door, then quickly turn back to grab keys, bag, and one random forgotten item.",
    howToFilm: "Crack open the door, then snap back inside for keys, bag, and one random forgotten item. Keep the scramble quick and controlled.",
    caption: "door opened three emergencies.",
    anchor: "door",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 23,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_024",
    hook: "Ready to leave became ready to sit down",
    whatToShow: "Stand fully dressed at the doorway, pause, then sit on the nearest chair without taking anything off.",
    howToFilm: "Stand fully dressed at the doorway. Pause like leaving is possible, then sit on the nearest chair without removing anything.",
    caption: "ready to leave became seated.",
    anchor: "doorway",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 24,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_025",
    hook: "The keys moved after I spiritually found them",
    whatToShow: "Spot the keys on a table, turn to grab a jacket, then look back and act like the keys disappeared.",
    howToFilm: "Spot the keys on the table. Turn away for the jacket, then look back and act like the keys moved by themselves.",
    caption: "keys moved spiritually.",
    anchor: "keys",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "entryway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Do not show address tags or identifiable key details.",
    originalBatchNumber: 25,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_026",
    hook: "The doorway turned my brain into airport security",
    whatToShow: "At the doorway, pat every pocket, check the bag, check the coat, then repeat once more.",
    howToFilm: "Phone on a tripod, one locked-off shot. at the doorway, pat every pocket, check the bag, check the coat, then repeat once more. Punch the final beat with one theatrical reaction.",
    caption: "pocket doorway triggered a tiny crisis.",
    anchor: "pocket",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing private documents.",
    originalBatchNumber: 26,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_027",
    hook: "I put my shoes on and lost momentum",
    whatToShow: "Tie both shoes at the front door, stand up, then immediately sit back down like the task was enough.",
    howToFilm: "Tie both shoes at the front door. Stand up, process the effort, then immediately sit back down like the shoes were the whole task.",
    caption: "shoes counted as the errand.",
    anchor: "shoes",
    comedyFamily: "task_avoidance",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 27,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_028",
    hook: "The bag strap attacked my exit timing",
    whatToShow: "Swing a bag onto your shoulder at the doorway, get tangled in the strap, then miss your confident exit.",
    howToFilm: "Swing the bag onto your shoulder at the doorway. Let the strap tangle, miss the confident exit, and reset with embarrassed composure.",
    caption: "bag strap ruined the exit.",
    anchor: "strap",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Keep movement slow and safe.",
    originalBatchNumber: 28,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_029",
    hook: "My hallway walk had too much confidence",
    whatToShow: "Stride down the hallway confidently, then stop because you forgot one item and shuffle backward.",
    howToFilm: "Stride down the hallway with too much confidence. Stop because you forgot something, then shuffle backward with the confidence gone.",
    caption: "hallway walk got humbled.",
    anchor: "stride",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "instant_regret",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    safetyNote: "Avoid filming neighbors or private building details.",
    originalBatchNumber: 29,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_030",
    hook: "I touched the door and became unavailable",
    whatToShow: "Touch the door handle, freeze, then slowly take your hand off and look back at the couch.",
    howToFilm: "Touch the door handle, freeze, and slowly remove your hand. Look back at the couch like it made a better offer.",
    caption: "door made me unavailable.",
    anchor: "handle",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 30,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_031",
    hook: "The jacket zipper delayed the whole operation",
    whatToShow: "At the doorway, pull a jacket zipper halfway, get stuck, then stand there negotiating with it silently.",
    howToFilm: "Pull the jacket zipper halfway at the entryway. Get stuck, pause, then negotiate silently with the zipper before giving up or trying again.",
    caption: "zipper delayed the operation.",
    anchor: "zipper",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 31,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_032",
    hook: "I forgot something and chose emotional collapse",
    whatToShow: "Step through the doorway, remember something, then slowly return inside with full-body disappointment.",
    howToFilm: "Phone on a tripod, one locked-off shot. step through the doorway, remember something, then slowly return inside with full-body disappointment. Punch the final beat with one theatrical reaction.",
    caption: "return forgot won the negotiation.",
    anchor: "return",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 32,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_033",
    hook: "My closet rejected the entire plan",
    whatToShow: "Open the closet, pull out one shirt, hold it up, then slowly put it back and close the closet.",
    howToFilm: "Open the closet with hope. Pull out one shirt, hold it up, then slowly return it and close the closet like the plan has been rejected.",
    caption: "closet rejected the plan.",
    anchor: "closet",
    comedyFamily: "getting_ready",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 33,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_034",
    hook: "My jeans asked questions I was not ready for",
    whatToShow: "Try to put on jeans, pause halfway, then sit on the bed and reconsider the entire outfit.",
    howToFilm: "Try putting on the jeans, pause halfway, then sit on the bed and reconsider the entire outfit. Keep the movement comfortable and safe.",
    caption: "jeans asked too many questions.",
    anchor: "bed",
    comedyFamily: "getting_ready",
    emotionalSpike: "private_embarrassment",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "accusation",
    safetyNote: "Keep movement safe and comfortable.",
    originalBatchNumber: 34,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_035",
    hook: "The hanger fought harder than expected",
    whatToShow: "Pull a shirt from a hanger, get the hanger caught, then shake it gently while trying to stay calm.",
    howToFilm: "Phone on a tripod, one locked-off shot. pull a shirt from a hanger, get the hanger caught, then shake it gently while trying to stay calm. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the hanger fought situation is not okay.",
    anchor: "hanger",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    originalBatchNumber: 35,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_036",
    hook: "One sock became a personal attack",
    whatToShow: "Look down at one normal sock and one wrong sock, then slowly lift your foot like evidence.",
    howToFilm: "Look down at the socks like you are presenting evidence. Lift the wrong sock slowly, then hold the betrayal beat.",
    caption: "sock became evidence.",
    anchor: "sock",
    comedyFamily: "getting_ready",
    emotionalSpike: "caught_off_guard",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 36,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_037",
    hook: "My jacket made the whole outfit worse",
    whatToShow: "Check outfit in mirror, add a jacket, then visibly deflate and remove it with disappointment.",
    howToFilm: "Check the outfit in the mirror. Add the jacket, visibly deflate, then remove it like the jacket personally made things worse.",
    caption: "jacket made it worse.",
    anchor: "jacket",
    comedyFamily: "getting_ready",
    emotionalSpike: "instant_regret",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 37,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_038",
    hook: "The belt chose today for character development",
    whatToShow: "Thread a belt through loops, miss one loop, notice it late, then start over with visible defeat.",
    howToFilm: "Phone on a tripod, one locked-off shot. thread a belt through loops, miss one loop, notice it late, then start over with visible defeat. Punch the final beat with one theatrical reaction.",
    caption: "belt chose won the negotiation.",
    anchor: "belt",
    comedyFamily: "parasocial_object",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 38,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_039",
    hook: "My outfit needed math I did not study",
    whatToShow: "Lay out two shirts and one pair of pants, swap combinations, then stare like the outfit became algebra.",
    howToFilm: "Lay out the shirts and pants like a serious equation. Swap combinations, pause, and stare as if the outfit became algebra.",
    caption: "outfit math defeated me.",
    anchor: "outfit",
    comedyFamily: "getting_ready",
    emotionalSpike: "confused_pause",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "overdramatic_diagnosis",
    originalBatchNumber: 39,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_040",
    hook: "The sleeve went inside out and won",
    whatToShow: "Try to put on a shirt, discover one sleeve is inside out, then wrestle it gently and give up.",
    howToFilm: "Try putting on the shirt, find one sleeve inside out, and wrestle it gently. End with the sleeve still feeling victorious.",
    caption: "sleeve won the round.",
    anchor: "sleeve",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    originalBatchNumber: 40,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_041",
    hook: "My shoes disagreed with the entire vibe",
    whatToShow: "Stand in a finished outfit, look down at shoes, then step backward like the shoes betrayed the plan.",
    howToFilm: "Stand in the finished outfit and look down at the shoes. Step backward slowly like the shoes ruined the entire vibe.",
    caption: "shoes broke the vibe.",
    anchor: "shoes",
    comedyFamily: "getting_ready",
    emotionalSpike: "instant_regret",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "accusation",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 41,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_042",
    hook: "The closet door opened and lowered morale",
    whatToShow: "Open the closet door with hope, stare at clothes, then slowly close it and look at the floor.",
    howToFilm: "Open the closet door with hope. Stare at the clothes, slowly close the door, and look at the floor like morale dropped.",
    caption: "closet lowered morale.",
    anchor: "clothes",
    comedyFamily: "getting_ready",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 42,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_043",
    hook: "My sweater trapped me in negotiations",
    whatToShow: "Pull on a sweater, get stuck for one second, then emerge with hair or collar messed up.",
    howToFilm: "Phone on a tripod, one locked-off shot. pull on a sweater, get stuck for one second, then emerge with hair or collar messed up. Talk-to-camera between beats; loose, a little frantic.",
    caption: "sweater trapped caught me in the act.",
    anchor: "sweater",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement gentle and safe.",
    originalBatchNumber: 43,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_044",
    hook: "The button entered a long-term conflict",
    whatToShow: "Try fastening one button, miss the hole, try again, then look down at the shirt like it escalated.",
    howToFilm: "Phone on a tripod, one locked-off shot. try fastening one button, miss the hole, try again, then look down at the shirt like it escalated. Keep your face flat the whole time; let the silence land.",
    caption: "the button entered situation is not okay.",
    anchor: "button",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 44,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_045",
    hook: "I changed shirts and lost the plot",
    whatToShow: "Hold two shirts, put one on, immediately remove it, then stand holding both with no clear answer.",
    howToFilm: "Hold two shirts, put one on, then immediately remove it. End holding both shirts with no answer and less confidence.",
    caption: "shirt swap lost the plot.",
    anchor: "shirts",
    comedyFamily: "getting_ready",
    emotionalSpike: "time_loss",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "confession",
    originalBatchNumber: 45,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_046",
    hook: "Hoodie strings ruined my leadership",
    whatToShow: "Look in the mirror, notice uneven hoodie strings, pull one side, then make the other side worse.",
    howToFilm: "Face the mirror and notice the hoodie strings are uneven. Pull one side, make the other side worse, and let the correction spiral.",
    caption: "hoodie strings chose chaos.",
    anchor: "hoodie",
    comedyFamily: "parasocial_object",
    emotionalSpike: "panic",
    setting: "mirror",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 46,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_047",
    hook: "The car seat became a waiting room",
    whatToShow: "Sit in the parked car, hands on the seat or wheel, then lean back and stare forward like you need a minute before going inside.",
    howToFilm: "Sit in the parked car with hands on the seat or wheel. Lean back and stare forward like the car became a waiting room.",
    caption: "car became the waiting room.",
    anchor: "car",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 47,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_048",
    hook: "I rehearsed hello like it had choreography",
    whatToShow: "In the parked car, practice a normal wave and greeting, then immediately look embarrassed at yourself.",
    howToFilm: "Phone on a tripod, one locked-off shot. in the parked car, practice a normal wave and greeting, then immediately look embarrassed at yourself. Talk-to-camera between beats; loose, a little frantic.",
    caption: "car rehearsed caught me in the act.",
    anchor: "car",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "car",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 48,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_049",
    hook: "The seatbelt trapped my dramatic exit",
    whatToShow: "Try to leave the parked car confidently, forget the seatbelt, get pulled back gently, then pause in defeat.",
    howToFilm: "Try to exit the parked car confidently. Let the seatbelt gently pull you back, then pause in defeat before unbuckling.",
    caption: "seatbelt stopped the exit.",
    anchor: "seatbelt",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 49,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_050",
    hook: "Car mirror confidence lasted exactly four seconds",
    whatToShow: "Check yourself in the car mirror, nod confidently, then notice one detail and start fixing everything.",
    howToFilm: "Phone on a tripod, one locked-off shot. check yourself in the car mirror, nod confidently, then notice one detail and start fixing everything. Hold the final pause one beat longer than feels comfortable.",
    caption: "mirror confidence happened, then the regret arrived.",
    anchor: "mirror",
    comedyFamily: "getting_ready",
    emotionalSpike: "instant_regret",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 50,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_051",
    hook: "The passenger seat became my command center",
    whatToShow: "Arrange a bag, jacket, receipt, and keys on the passenger seat, then lose one item under the pile.",
    howToFilm: "Arrange the bag, jacket, receipt, and keys on the passenger seat. Lose one item under the pile and search like the seat became a command center.",
    caption: "passenger seat became headquarters.",
    anchor: "seat",
    comedyFamily: "adulting_panic",
    emotionalSpike: "confused_pause",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 51,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_052",
    hook: "I arrived early and still wasn’t ready",
    whatToShow: "Sit in the parked car, check the door outside, adjust jacket, then continue sitting instead of leaving.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit in the parked car, check the door outside, adjust jacket, then continue sitting instead of leaving. Hold the final pause one beat longer than feels comfortable.",
    caption: "jacket arrived stayed exactly where it was.",
    anchor: "jacket",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "avoidance_spike",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 52,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_053",
    hook: "The steering wheel heard my entire pep talk",
    whatToShow: "Grip the steering wheel in the parked car and silently hype yourself up before opening the door.",
    howToFilm: "Grip the steering wheel in the parked car. Silently hype yourself up, then reach for the door like the wheel heard the whole pep talk.",
    caption: "wheel heard the pep talk.",
    anchor: "wheel",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "false_productivity",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 53,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_054",
    hook: "The receipt made the car very quiet",
    whatToShow: "In the parked car, unfold a receipt, glance at the bags, then fold it back with silent regret.",
    howToFilm: "Unfold the receipt in the parked car. Glance from the receipt to the bags, then fold it back with silent regret.",
    caption: "receipt made the car quiet.",
    anchor: "receipt",
    comedyFamily: "adulting_panic",
    emotionalSpike: "quiet_realization",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    safetyNote: "Film while parked only. Do not film while driving. Hide payment/store details if needed.",
    originalBatchNumber: 54,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_055",
    hook: "My car keys started the second errand crisis",
    whatToShow: "Hold car keys in the parked car, prepare to leave, then realize you need something from the back seat.",
    howToFilm: "Hold the car keys in the parked car. Prepare to leave, then realize something is in the back seat and the errand has multiplied.",
    caption: "keys started another crisis.",
    anchor: "keys",
    comedyFamily: "task_avoidance",
    emotionalSpike: "panic",
    setting: "car",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 55,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_056",
    hook: "The car door opened before my courage did",
    whatToShow: "Open the car door from inside, pause with one foot out, then pull the foot back in for one more second.",
    howToFilm: "Open the car door from inside and put one foot out. Pause, pull the foot back in, and take one more second before leaving.",
    caption: "car door opened too soon.",
    anchor: "door",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 56,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_057",
    hook: "The glovebox contained everything except maturity",
    whatToShow: "Open the glovebox in the parked car, reveal napkins and random items, then fail to find the one needed thing.",
    howToFilm: "Open the glovebox in the parked car. Reveal napkins and random items, search for one needed thing, and fail with quiet disbelief.",
    caption: "glovebox had everything else.",
    anchor: "glovebox",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "confused_pause",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 57,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_058",
    hook: "I parked and became emotionally unavailable",
    whatToShow: "Sit in the parked car after arriving, unbuckle, then rebuckle or lean back like you need a reset.",
    howToFilm: "Sit in the parked car after arriving. Unbuckle, then rebuckle or lean back like you need an emotional reset before going inside.",
    caption: "parked car claimed me.",
    anchor: "reset",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 58,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_059",
    hook: "I stood up like my knees signed approval",
    whatToShow: "Rise from a chair too confidently, pause halfway, then adjust your stance like the chair exposed you.",
    howToFilm: "Phone on a tripod, one locked-off shot. rise from a chair too confidently, pause halfway, then adjust your stance like the chair exposed you. Keep your face flat the whole time; let the silence land.",
    caption: "chair stood did not warn me.",
    anchor: "chair",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement gentle and safe.",
    originalBatchNumber: 59,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_060",
    hook: "The floor item became a whole commitment",
    whatToShow: "Drop a small item on the floor, look down, bend halfway, then reconsider and use your foot to move it closer.",
    howToFilm: "Drop a small item on the floor. Bend halfway, reconsider, then use your foot to slide the item closer like that was the plan.",
    caption: "floor item became a project.",
    anchor: "floor",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Keep movement safe and avoid strain.",
    originalBatchNumber: 60,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_061",
    hook: "My sock slide had too much ambition",
    whatToShow: "Attempt a tiny sock slide across the floor, immediately lose balance slightly, then freeze and pretend it was planned.",
    howToFilm: "Attempt a tiny sock slide across the floor. Lose balance slightly, freeze, then pretend the slide was intentional.",
    caption: "sock slide got ambitious.",
    anchor: "sock",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "living_room",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    safetyNote: "Use a clear floor and keep movement small.",
    originalBatchNumber: 61,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_062",
    hook: "The blanket refused to release its hostage",
    whatToShow: "Try to stand from the couch while tangled in a blanket, take one step, then return to untangle.",
    howToFilm: "Try standing from the couch while tangled in the blanket. Take one slow step, get caught, and return to untangle.",
    caption: "blanket refused release.",
    anchor: "blanket",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "couch",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Keep steps slow and avoid tripping.",
    originalBatchNumber: 62,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_063",
    hook: "The pillow rearranged my spine without permission",
    whatToShow: "Lie on a pillow, adjust it repeatedly, then sit up looking personally offended by the pillow.",
    howToFilm: "Lie on the pillow and adjust it repeatedly. Sit up looking offended, as if the pillow made a personal decision.",
    caption: "pillow rearranged my spine.",
    anchor: "pillow",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "accusation",
    originalBatchNumber: 63,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_064",
    hook: "My chair squeaked and exposed the operation",
    whatToShow: "Sit carefully in a chair, hear a squeak, freeze, then sit even slower like negotiating peace.",
    howToFilm: "Sit carefully in the chair. Let the squeak happen, freeze, then lower yourself slower for the second attempt.",
    caption: "chair exposed the operation.",
    anchor: "squeak",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    safetyNote: "Use a stable chair.",
    originalBatchNumber: 64,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_065",
    hook: "The rug tried to humble my confidence",
    whatToShow: "Walk across a rug, catch your foot slightly, then look back at the rug like it started something.",
    howToFilm: "Walk across the rug and catch your foot slightly. Recover safely, then look back at the rug like it started the problem.",
    caption: "rug tried to humble me.",
    anchor: "rug",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "accusation",
    safetyNote: "Use a safe, tiny stumble only; avoid actual tripping.",
    originalBatchNumber: 65,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_066",
    hook: "I bent down and aged seven minutes",
    whatToShow: "Bend to pick up one object, pause dramatically, then stand up slowly holding the item like a trophy.",
    howToFilm: "Phone on a tripod, one locked-off shot. bend to pick up one object, pause dramatically, then stand up slowly holding the item like a trophy. Keep your face flat the whole time; let the silence land.",
    caption: "object bent won the negotiation.",
    anchor: "object",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Keep movement gentle and safe.",
    originalBatchNumber: 66,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_067",
    hook: "The blanket escape needed more strategy",
    whatToShow: "Try to leave bed or couch under a blanket, get one foot trapped, then carefully reverse and start again.",
    howToFilm: "Try to leave the couch or bed under the blanket. Let one foot get trapped, reverse carefully, and start the escape again.",
    caption: "blanket escape needed strategy.",
    anchor: "foot",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "time_loss",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement slow and avoid tripping.",
    originalBatchNumber: 67,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_068",
    hook: "My slippers gave me false athletic confidence",
    whatToShow: "Shuffle quickly in slippers, stop when one almost slides off, then look down with betrayed confidence.",
    howToFilm: "Shuffle in slippers with too much confidence. Stop when one almost slides off, then look down like the slippers betrayed the athlete.",
    caption: "slippers lied about my skills.",
    anchor: "slippers",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "false_productivity",
    setting: "hallway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Keep movement slow and controlled.",
    originalBatchNumber: 68,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_069",
    hook: "Couch accepted my failed escape attempt",
    whatToShow: "Start standing from the couch, get halfway up, then sink back down like the couch made a strong argument.",
    howToFilm: "Start standing from the couch. Get halfway up, then sink back down like the couch made a convincing argument.",
    caption: "couch accepted my resignation.",
    anchor: "couch",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 69,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_070",
    hook: "I stretched once and needed a statement",
    whatToShow: "Do one small stretch, pause dramatically, then sit down like the stretch required formal recovery.",
    howToFilm: "Phone on a tripod, one locked-off shot. do one small stretch, pause dramatically, then sit down like the stretch required formal recovery. Punch the final beat with one theatrical reaction.",
    caption: "stretch stretched earned no real points.",
    anchor: "stretch",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "false_productivity",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Keep the stretch gentle and safe.",
    originalBatchNumber: 70,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_071",
    hook: "The pillow fight was against my comfort",
    whatToShow: "Fluff a pillow aggressively, place it behind you, then immediately pull it out because it feels wrong.",
    howToFilm: "Phone on a tripod, one locked-off shot. fluff a pillow aggressively, place it behind you, then immediately pull it out because it feels wrong. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the pillow fight situation is not okay.",
    anchor: "pillow",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 71,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_072",
    hook: "My balance left before the errand did",
    whatToShow: "Stand on one foot to put on a shoe, wobble safely, then sit down with instant humility.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand on one foot to put on a shoe, wobble safely, then sit down with instant humility. Hold the final pause one beat longer than feels comfortable.",
    caption: "shoe balance did not warn me.",
    anchor: "shoe",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "entryway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Use a wall or chair nearby for balance.",
    originalBatchNumber: 72,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_073",
    hook: "The chair caught me sitting down emotionally",
    whatToShow: "Approach a chair like you are just resting briefly, then sink into it with full dramatic surrender.",
    howToFilm: "Approach the chair like you are only resting for a second. Sit down and immediately sink into full dramatic surrender.",
    caption: "chair caught the surrender.",
    anchor: "chair",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Use a stable chair.",
    originalBatchNumber: 73,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_074",
    hook: "The broom made cleaning legally binding",
    whatToShow: "Pick up a broom to sweep one spot, notice another spot, then stand there realizing the broom started a whole job.",
    howToFilm: "Pick up the broom to sweep one spot. Notice another spot, then stand still as the broom turns one task into a full job.",
    caption: "broom started a whole job.",
    anchor: "broom",
    comedyFamily: "parasocial_object",
    emotionalSpike: "instant_regret",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 74,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_075",
    hook: "The drawer opened and revealed consequences",
    whatToShow: "Open a drawer looking for one item, find a messy pile, then slowly close the drawer without solving anything.",
    howToFilm: "Open the drawer looking for one item. Reveal the messy pile, pause, then close the drawer without solving anything.",
    caption: "drawer revealed consequences.",
    anchor: "drawer",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "avoidance_spike",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Avoid showing private documents.",
    originalBatchNumber: 75,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_076",
    hook: "The cabinet door chose public disrespect",
    whatToShow: "Close a cabinet door, watch it swing open again, then push it closed with increasing seriousness.",
    howToFilm: "Close the cabinet door and watch it swing open again. Push it closed more seriously, then wait to see if it disrespects you twice.",
    caption: "cabinet chose disrespect.",
    anchor: "cabinet",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 76,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_077",
    hook: "The lid refused the entire household",
    whatToShow: "Try to place a lid on a container, rotate it several times, then realize it belongs to something else.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to place a lid on a container, rotate it several times, then realize it belongs to something else. Talk-to-camera between beats; loose, a little frantic.",
    caption: "lid refused required a hard pause.",
    anchor: "lid",
    comedyFamily: "parasocial_object",
    emotionalSpike: "confused_pause",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 77,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_078",
    hook: "My zipper waited until confidence arrived",
    whatToShow: "Zip a bag or jacket confidently, get stuck halfway, then look directly at the zipper like it planned this.",
    howToFilm: "Zip the bag or jacket confidently. Get stuck halfway, then look directly at the zipper like it waited for confidence to arrive.",
    caption: "zipper waited for confidence.",
    anchor: "stuck",
    comedyFamily: "parasocial_object",
    emotionalSpike: "instant_regret",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "accusation",
    originalBatchNumber: 78,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_079",
    hook: "A shoelace resigned during business hours",
    whatToShow: "Tie a shoelace at the doorway, stand up, then watch the shoelace immediately loosen.",
    howToFilm: "Tie the shoelace at the doorway and stand up. Watch it immediately loosen, then hold the stare before bending down again.",
    caption: "shoelace resigned immediately.",
    anchor: "shoelace",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 79,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_080",
    hook: "The reusable bag folded me into confusion",
    whatToShow: "Try folding a reusable bag neatly, lose the shape, then stuff it into itself with quiet defeat.",
    howToFilm: "Try folding the reusable bag neatly. Lose the shape, stuff it into itself, and accept quiet defeat.",
    caption: "reusable bag folded me.",
    anchor: "bag",
    comedyFamily: "parasocial_object",
    emotionalSpike: "confused_pause",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 80,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_081",
    hook: "The tape stuck to everyone except the package",
    whatToShow: "Seal a package with tape, get the tape stuck to your fingers, scissors, or counter instead.",
    howToFilm: "Seal the package with tape. Let the tape stick to your fingers, scissors, or counter instead of the package, then pause in polite rage.",
    caption: "tape chose everyone else.",
    anchor: "tape",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Keep scissors or sharp tools out of frame if not needed.",
    originalBatchNumber: 81,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_082",
    hook: "Doorknob made leaving optional again",
    whatToShow: "Grab the doorknob, realize your sleeve or bag is caught, then slowly let go and reset.",
    howToFilm: "Grab the doorknob to leave. Realize your sleeve or bag is caught, let go slowly, and reset like leaving became optional.",
    caption: "doorknob made leaving optional.",
    anchor: "doorknob",
    comedyFamily: "parasocial_object",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 82,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_083",
    hook: "The package became a doorway decoration",
    whatToShow: "Place a return package by the doorway, walk past it twice, then pretend not to see it.",
    howToFilm: "Place the return package by the doorway. Walk past it twice, avoid eye contact, and pretend it became decoration.",
    caption: "package became doorway decor.",
    anchor: "package",
    comedyFamily: "task_avoidance",
    emotionalSpike: "avoidance_spike",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide names, addresses, and labels.",
    originalBatchNumber: 83,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_084",
    hook: "Kitchen counter checkout had unexpected pressure",
    whatToShow: "Set items on the kitchen counter like self-checkout, pretend to scan them, then freeze when one item will not “scan.”",
    howToFilm: "Set items on the kitchen counter like self-checkout. Pretend to scan them, then freeze when one item refuses to scan.",
    caption: "counter checkout got tense.",
    anchor: "counter",
    comedyFamily: "task_avoidance",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 84,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_085",
    hook: "The return label became a full obstacle",
    whatToShow: "Hold a package and return label, line it up badly, peel it crooked, then stare at the package.",
    howToFilm: "Hold the package and return label at the counter. Line it up badly, peel it crooked, then stare at the package like the errand escalated.",
    caption: "return label chose violence.",
    anchor: "label",
    comedyFamily: "task_avoidance",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    safetyNote: "Hide names, addresses, and labels.",
    originalBatchNumber: 85,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_086",
    hook: "I recreated the waiting room too accurately",
    whatToShow: "Sit stiffly in a chair, hold a bag in your lap, look around your living room like you are waiting to be called.",
    howToFilm: "Sit stiffly in the chair with a bag in your lap. Look around the living room like you are waiting to be called.",
    caption: "waiting room energy found me.",
    anchor: "chair",
    comedyFamily: "task_avoidance",
    emotionalSpike: "private_embarrassment",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid medical framing or private health details.",
    originalBatchNumber: 86,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_087",
    hook: "My pantry became a grocery aisle with judgment",
    whatToShow: "Stand at the pantry, compare two items in your hands like you are shopping, then choose neither.",
    howToFilm: "Stand at the pantry and compare two items in your hands. Decide on neither, then return both like the pantry judged you.",
    caption: "pantry became the aisle.",
    anchor: "pantry",
    comedyFamily: "task_avoidance",
    emotionalSpike: "confused_pause",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 87,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_088",
    hook: "The receipt review became a small trial",
    whatToShow: "Spread a receipt on the kitchen counter, point at one line, then look at the item like it betrayed you.",
    howToFilm: "Spread the receipt on the kitchen counter. Point at one line, then look at the item like it betrayed you in court.",
    caption: "receipt entered evidence.",
    anchor: "receipt",
    comedyFamily: "task_avoidance",
    emotionalSpike: "quiet_realization",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide payment/store details if needed.",
    originalBatchNumber: 88,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_089",
    hook: "I practiced small talk with a cereal box",
    whatToShow: "Place a cereal box on the counter, rehearse a normal greeting to it, then immediately cringe.",
    howToFilm: "Place the cereal box on the counter. Rehearse a normal greeting to it, then cringe when the small talk gets too real.",
    caption: "cereal box heard too much.",
    anchor: "box",
    comedyFamily: "task_avoidance",
    emotionalSpike: "private_embarrassment",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    originalBatchNumber: 89,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_090",
    hook: "The tote bag made errands look official",
    whatToShow: "Pack a tote bag with one item, stand proudly, then realize you forgot the actual errand item.",
    howToFilm: "Pack the tote bag with one item and stand proudly. Then realize the actual errand item is missing.",
    caption: "tote bag looked official.",
    anchor: "bag",
    comedyFamily: "task_avoidance",
    emotionalSpike: "instant_regret",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    safetyNote: "Do not show IDs, cards, or private documents.",
    originalBatchNumber: 90,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_091",
    hook: "I got ready for plans and sat down",
    whatToShow: "Stand fully dressed near the mirror, grab your bag, then sit on the couch like the preparation was the event.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand fully dressed near the mirror, grab your bag, then sit on the couch like the preparation was the event. Keep your face flat the whole time; let the silence land.",
    caption: "bag ready won the negotiation.",
    anchor: "bag",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 91,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_092",
    hook: "My casual outfit required a legal review",
    whatToShow: "Hold two casual outfit options, inspect both in the mirror, then change into a third unrelated option.",
    howToFilm: "Hold two casual outfit options in the mirror. Inspect both seriously, then change into a third option that solves nothing.",
    caption: "casual outfit needed review.",
    anchor: "outfit",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "time_loss",
    setting: "mirror",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 92,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_093",
    hook: "I rehearsed a normal greeting and made it weird",
    whatToShow: "Stand in the hallway, practice saying hello to an empty room, then stop because it sounded unnatural.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand in the hallway, practice saying hello to an empty room, then stop because it sounded unnatural. Talk-to-camera between beats; loose, a little frantic.",
    caption: "hallway rehearsed caught me in the act.",
    anchor: "hallway",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "hallway",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Avoid filming neighbors or private building details.",
    originalBatchNumber: 93,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_094",
    hook: "The guest pillow created fake responsibility",
    whatToShow: "Place a guest pillow on the couch, adjust it three times, then notice the rest of the room is messy.",
    howToFilm: "Phone on a tripod, one locked-off shot. place a guest pillow on the couch, adjust it three times, then notice the rest of the room is messy. Hold the final pause one beat longer than feels comfortable.",
    caption: "pillow guest triggered a tiny crisis.",
    anchor: "pillow",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "panic",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 94,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_095",
    hook: "I picked a jacket for imaginary weather",
    whatToShow: "Try one jacket, look toward the door, switch jackets, then stand holding both like there is no answer.",
    howToFilm: "Try one jacket at the entryway, look toward the door, then switch jackets. End holding both like weather became imaginary.",
    caption: "jacket weather was imaginary.",
    anchor: "jacket",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "confused_pause",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 95,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_096",
    hook: "The snack bowl became my hosting personality",
    whatToShow: "Set out a snack bowl, adjust it seriously, then stand back like the room suddenly has hospitality.",
    howToFilm: "Set out the snack bowl and adjust it with too much care. Step back like the bowl gave the room a hosting personality.",
    caption: "snack bowl became hospitality.",
    anchor: "bowl",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "false_productivity",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 96,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_097",
    hook: "I practiced being relaxed and failed immediately",
    whatToShow: "Sit on the couch in a casual pose for plans, adjust your arms, legs, and face until it looks worse.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit on the couch in a casual pose for plans, adjust your arms, legs, and face until it looks worse. Talk-to-camera between beats; loose, a little frantic.",
    caption: "couch practiced caught me in the act.",
    anchor: "couch",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 97,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_098",
    hook: "The doorbell practice lowered morale",
    whatToShow: "Stand near the front door, mime hearing a doorbell, compose yourself, then immediately lose composure.",
    howToFilm: "Stand near the front door and mime hearing a doorbell. Compose yourself, then immediately lose composure before anyone arrives.",
    caption: "doorbell practice lowered morale.",
    anchor: "doorbell",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 98,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_099",
    hook: "I dressed for plans and became furniture",
    whatToShow: "Sit fully dressed on the couch, shoes on, jacket ready, completely still like a decorative object.",
    howToFilm: "Sit fully dressed on the couch with shoes and jacket ready. Stay completely still until the outfit starts looking decorative.",
    caption: "dressed for plans, became furniture.",
    anchor: "jacket",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "realization",
    originalBatchNumber: 99,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_100",
    hook: "My entrance wave had too many drafts",
    whatToShow: "Practice entering the room and waving, reset twice, then choose the smallest awkward wave possible.",
    howToFilm: "Phone on a tripod, one locked-off shot. practice entering the room and waving, reset twice, then choose the smallest awkward wave possible. Talk-to-camera between beats; loose, a little frantic.",
    caption: "wave entrance caught me in the act.",
    anchor: "wave",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 100,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
    ]);
