/**
   * PHASE W2-T — curated W2-T-DIVERSITY promotion entries (DARK by
   * default; surfaced through the W2-K runtime path via
   * `westernHookPackApproved.ts`).
   *
   * 100 editorial-curated Western hooks (W2-T-DIVERSITY-001..100)
   * targeting the W2-S diversity gaps: phone/screen ratio
   * (62% → <35%), bathroom/mirror, hallway/doorway, parked car,
   * physical body, leaving-house delay, getting-ready/closet,
   * social/object comedy diversity. Imported under the same Path A
   * guardrails the W2-L / W2-N imports established:
   *
   *   • single runtime path — entries flow through the SAME approved
   *     pool that W2-K activated. Live promotion happens via the
   *     W2-O `westernHookPackLive` rubric, which scores this batch
   *     on module load alongside the other curated batches.
   *   • howToFilm is SYNTHESIZED deterministically per entry from the
   *     curated WHAT TO SHOW (each entry's actual beat narration),
   *     prefixed with a tripod/single-shot framing directive and
   *     suffixed with a voice-cluster-keyed payoff cue.
   *   • caption is synthesized deterministically per entry from
   *     (emotionalSpike × anchor × distinctive hook token).
   *   • freeform vocab from the curated batch (Comedy family,
   *     Emotional spike, Setting) is normalized into the EXISTING
   *     `WESTERN_COMEDY_FAMILIES` / `WESTERN_EMOTIONAL_SPIKES` /
   *     `WESTERN_SETTINGS` controlled vocab — no enum widening.
   *     See `.local/W2T_BUILD_REPORT.md` § Vocab remaps for the
   *     curated→controlled mappings (e.g. object_betrayal →
   *     parasocial_object, sink → bathroom, parked_car → car).
   *   • voiceCluster is normalized into `WESTERN_VOICE_CLUSTERS`.
   *   • hookStyle is normalized into `WESTERN_BATCH_HOOK_STYLES`.
   *   • safetyNote is preserved verbatim from the curated batch on
   *     entries that carry one (entries marked "None." leave the
   *     optional field unset). Parked-car entries always carry the
   *     "Film while parked only. Do not film while driving." note.
   *   • originalBatchNumber preserves the W2-T-DIVERSITY row number
   *     (1..100). Owning batch label resolved by
   *     `getWesternEntrySourceBatch` → "W2-T-DIVERSITY".
   *   • whyThisWorks intentionally NOT carried on the runtime entry —
   *     it lives in the curated source attachment + the W2-T import
   *     report (`.local/W2T_BUILD_REPORT.md`).
   *   • anchor is normalized to a single lowercase token that appears
   *     (lowercased) in whatToShow.
   *
   * Cross-batch dedup verified at import time vs:
   *   • `APPROVED_WESTERN_PROMOTION_CANDIDATES` (W2I 100 + W2-L 100
   *     + W2-N 100)
   *   • `WESTERN_HOOK_PACK_DRAFT` (150)
   *   • `userBlessedHookCorpus.ts` (532)
   *   • this batch's own running set
   *
   * Production stays OFF — gating still flows through
   * `isWesternApprovedPoolFeatureEnabled` +
   * `canActivateWesternApprovedPool` (staging) and the W2-O
   * `isWesternLivePoolFeatureEnabled` +
   * `canActivateWesternLivePool` (live).
   */

  import {
    PENDING_EDITORIAL_REVIEW,
    type WesternHookPackDraftEntry,
  } from "./westernHookPack.js";

  export const WESTERN_HOOK_PACK_DIVERSITY_IDS: readonly string[] =
    Object.freeze([
    "w2_t_diversity_001",
    "w2_t_diversity_002",
    "w2_t_diversity_003",
    "w2_t_diversity_004",
    "w2_t_diversity_005",
    "w2_t_diversity_006",
    "w2_t_diversity_007",
    "w2_t_diversity_008",
    "w2_t_diversity_009",
    "w2_t_diversity_010",
    "w2_t_diversity_011",
    "w2_t_diversity_012",
    "w2_t_diversity_013",
    "w2_t_diversity_014",
    "w2_t_diversity_015",
    "w2_t_diversity_016",
    "w2_t_diversity_017",
    "w2_t_diversity_018",
    "w2_t_diversity_019",
    "w2_t_diversity_020",
    "w2_t_diversity_021",
    "w2_t_diversity_022",
    "w2_t_diversity_023",
    "w2_t_diversity_024",
    "w2_t_diversity_025",
    "w2_t_diversity_026",
    "w2_t_diversity_027",
    "w2_t_diversity_028",
    "w2_t_diversity_029",
    "w2_t_diversity_030",
    "w2_t_diversity_031",
    "w2_t_diversity_032",
    "w2_t_diversity_033",
    "w2_t_diversity_034",
    "w2_t_diversity_035",
    "w2_t_diversity_036",
    "w2_t_diversity_037",
    "w2_t_diversity_038",
    "w2_t_diversity_039",
    "w2_t_diversity_040",
    "w2_t_diversity_041",
    "w2_t_diversity_042",
    "w2_t_diversity_043",
    "w2_t_diversity_044",
    "w2_t_diversity_045",
    "w2_t_diversity_046",
    "w2_t_diversity_047",
    "w2_t_diversity_048",
    "w2_t_diversity_049",
    "w2_t_diversity_050",
    "w2_t_diversity_051",
    "w2_t_diversity_052",
    "w2_t_diversity_053",
    "w2_t_diversity_054",
    "w2_t_diversity_055",
    "w2_t_diversity_056",
    "w2_t_diversity_057",
    "w2_t_diversity_058",
    "w2_t_diversity_059",
    "w2_t_diversity_060",
    "w2_t_diversity_061",
    "w2_t_diversity_062",
    "w2_t_diversity_063",
    "w2_t_diversity_064",
    "w2_t_diversity_065",
    "w2_t_diversity_066",
    "w2_t_diversity_067",
    "w2_t_diversity_068",
    "w2_t_diversity_069",
    "w2_t_diversity_070",
    "w2_t_diversity_071",
    "w2_t_diversity_072",
    "w2_t_diversity_073",
    "w2_t_diversity_074",
    "w2_t_diversity_075",
    "w2_t_diversity_076",
    "w2_t_diversity_077",
    "w2_t_diversity_078",
    "w2_t_diversity_079",
    "w2_t_diversity_080",
    "w2_t_diversity_081",
    "w2_t_diversity_082",
    "w2_t_diversity_083",
    "w2_t_diversity_084",
    "w2_t_diversity_085",
    "w2_t_diversity_086",
    "w2_t_diversity_087",
    "w2_t_diversity_088",
    "w2_t_diversity_089",
    "w2_t_diversity_090",
    "w2_t_diversity_091",
    "w2_t_diversity_092",
    "w2_t_diversity_093",
    "w2_t_diversity_094",
    "w2_t_diversity_095",
    "w2_t_diversity_096",
    "w2_t_diversity_097",
    "w2_t_diversity_098",
    "w2_t_diversity_099",
    "w2_t_diversity_100",
    ]);

  export const WESTERN_HOOK_PACK_DIVERSITY: readonly WesternHookPackDraftEntry[] =
    Object.freeze([
  {
    id: "w2_t_diversity_001",
    hook: "Mirror check turned into a full investigation",
    whatToShow: "Stand at the mirror ready to leave, then slowly lean closer, checking hair, collar, face, and outfit like you found evidence.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand at the mirror ready to leave, then slowly lean closer, checking hair, collar, face, and outfit like you found evidence. Keep your face flat the whole time; let the silence land.",
    caption: "mirror check caught me in the act.",
    anchor: "mirror",
    comedyFamily: "getting_ready",
    emotionalSpike: "private_embarrassment",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 1,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_002",
    hook: "The towel fell and took my patience with it",
    whatToShow: "Wrap or hang a towel, watch the towel fall immediately, then stare at it like it personally escalated the morning.",
    howToFilm: "Phone on a tripod, one locked-off shot. wrap or hang a towel, watch the towel fall immediately, then stare at it like it personally escalated the morning. Punch the final beat with one theatrical reaction.",
    caption: "the towel fell situation is not okay.",
    anchor: "towel",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bathroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 2,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_003",
    hook: "My toothbrush started a side quest",
    whatToShow: "Pick up a toothbrush, then accidentally clean the sink, move bottles, and reorganize the counter before brushing.",
    howToFilm: "Phone on a tripod, one locked-off shot. pick up a toothbrush, then accidentally clean the sink, move bottles, and reorganize the counter before brushing. Hold the final pause one beat longer than feels comfortable.",
    caption: "toothbrush started stole the whole window.",
    anchor: "toothbrush",
    comedyFamily: "task_avoidance",
    emotionalSpike: "time_loss",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 3,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_004",
    hook: "The sink looked clean until I got confident",
    whatToShow: "Lean over the sink proudly, then notice one tiny mess and start wiping more and more of the counter.",
    howToFilm: "Phone on a tripod, one locked-off shot. lean over the sink proudly, then notice one tiny mess and start wiping more and more of the counter. Keep your face flat the whole time; let the silence land.",
    caption: "sink looked happened, then the regret arrived.",
    anchor: "sink",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "instant_regret",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 4,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_005",
    hook: "My hair chose violence at the worst time",
    whatToShow: "Face the mirror with one piece of hair sticking out, fix it, then watch another section pop up worse.",
    howToFilm: "Phone on a tripod, one locked-off shot. face the mirror with one piece of hair sticking out, fix it, then watch another section pop up worse. Talk-to-camera between beats; loose, a little frantic.",
    caption: "hair chose triggered a tiny crisis.",
    anchor: "hair",
    comedyFamily: "getting_ready",
    emotionalSpike: "panic",
    setting: "mirror",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 5,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_006",
    hook: "The bathroom counter exposed my planning system",
    whatToShow: "Pan across the bathroom counter: comb, lotion, towel, cup, and random objects scattered like a failed command center.",
    howToFilm: "Phone on a tripod, one locked-off shot. pan across the bathroom counter: comb, lotion, towel, cup, and random objects scattered like a failed command center. Hold the final pause one beat longer than feels comfortable.",
    caption: "counter bathroom explained the whole morning.",
    anchor: "counter",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_realization",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide private products or labels if needed.",
    originalBatchNumber: 6,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_007",
    hook: "I washed my face and trusted the universe",
    whatToShow: "Wash at the sink, look refreshed in the mirror, then immediately notice a shirt stain or hair problem.",
    howToFilm: "Phone on a tripod, one locked-off shot. wash at the sink, look refreshed in the mirror, then immediately notice a shirt stain or hair problem. Keep your face flat the whole time; let the silence land.",
    caption: "sink washed earned no real points.",
    anchor: "sink",
    comedyFamily: "task_avoidance",
    emotionalSpike: "false_productivity",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 7,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_008",
    hook: "The mirror approved nothing and explained everything",
    whatToShow: "Step into the mirror frame confidently, freeze, then slowly remove one accessory, jacket, or hat.",
    howToFilm: "Phone on a tripod, one locked-off shot. step into the mirror frame confidently, freeze, then slowly remove one accessory, jacket, or hat. Punch the final beat with one theatrical reaction.",
    caption: "frame mirror caught me in the act.",
    anchor: "frame",
    comedyFamily: "getting_ready",
    emotionalSpike: "private_embarrassment",
    setting: "mirror",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 8,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_009",
    hook: "My towel wrap had other plans",
    whatToShow: "Secure a towel wrap, take one confident step, then catch the towel slipping and freeze in panic.",
    howToFilm: "Phone on a tripod, one locked-off shot. secure a towel wrap, take one confident step, then catch the towel slipping and freeze in panic. Talk-to-camera between beats; loose, a little frantic.",
    caption: "towel wrap did not warn me.",
    anchor: "towel",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "bathroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Keep framing modest and comfortable.",
    originalBatchNumber: 9,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_010",
    hook: "Skincare made me act employed by my face",
    whatToShow: "Line up simple skincare items by the mirror, apply one thing carefully, then nod like you managed a department.",
    howToFilm: "Phone on a tripod, one locked-off shot. line up simple skincare items by the mirror, apply one thing carefully, then nod like you managed a department. Keep your face flat the whole time; let the silence land.",
    caption: "mirror skincare earned no real points.",
    anchor: "mirror",
    comedyFamily: "getting_ready",
    emotionalSpike: "false_productivity",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid medical or skin-condition claims.",
    originalBatchNumber: 10,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_011",
    hook: "The hand towel refused basic cooperation",
    whatToShow: "Dry your hands with a hand towel, try to hang it neatly, then watch it slide down twice.",
    howToFilm: "Phone on a tripod, one locked-off shot. dry your hands with a hand towel, try to hang it neatly, then watch it slide down twice. Hold the final pause one beat longer than feels comfortable.",
    caption: "the hands hand situation is not okay.",
    anchor: "hands",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 11,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_012",
    hook: "I practiced one smile and found twelve problems",
    whatToShow: "Smile into the mirror, adjust posture, change angle, then give up and make a neutral face.",
    howToFilm: "Phone on a tripod, one locked-off shot. smile into the mirror, adjust posture, change angle, then give up and make a neutral face. Talk-to-camera between beats; loose, a little frantic.",
    caption: "mirror practiced caught me in the act.",
    anchor: "mirror",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "mirror",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 12,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_013",
    hook: "Bathroom light changed my whole identity",
    whatToShow: "Turn on the bathroom light, look in the mirror, then physically step back like the lighting told the truth.",
    howToFilm: "Phone on a tripod, one locked-off shot. turn on the bathroom light, look in the mirror, then physically step back like the lighting told the truth. Punch the final beat with one theatrical reaction.",
    caption: "light bathroom did not warn me.",
    anchor: "light",
    comedyFamily: "getting_ready",
    emotionalSpike: "caught_off_guard",
    setting: "bathroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "accusation",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 13,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_014",
    hook: "My robe belt became a physics problem",
    whatToShow: "Try tying a robe belt, accidentally make it uneven, then keep adjusting until it looks worse.",
    howToFilm: "Phone on a tripod, one locked-off shot. try tying a robe belt, accidentally make it uneven, then keep adjusting until it looks worse. Keep your face flat the whole time; let the silence land.",
    caption: "belt robe required a hard pause.",
    anchor: "belt",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "confused_pause",
    setting: "bathroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Keep framing modest and comfortable.",
    originalBatchNumber: 14,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_015",
    hook: "The sink splash humbled my whole outfit",
    whatToShow: "Use the sink carefully, then look down at a fresh water spot on your shirt and freeze.",
    howToFilm: "Phone on a tripod, one locked-off shot. use the sink carefully, then look down at a fresh water spot on your shirt and freeze. Hold the final pause one beat longer than feels comfortable.",
    caption: "shirt sink happened, then the regret arrived.",
    anchor: "shirt",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "instant_regret",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 15,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_016",
    hook: "Getting ready became mostly moving bottles around",
    whatToShow: "Reach for one item on the bathroom counter, move three bottles, lose the first item, then stare at the mess.",
    howToFilm: "Phone on a tripod, one locked-off shot. reach for one item on the bathroom counter, move three bottles, lose the first item, then stare at the mess. Talk-to-camera between beats; loose, a little frantic.",
    caption: "counter getting stole the whole window.",
    anchor: "counter",
    comedyFamily: "getting_ready",
    emotionalSpike: "time_loss",
    setting: "bathroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Hide private labels if needed.",
    originalBatchNumber: 16,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_017",
    hook: "I reached the door and forgot the mission",
    whatToShow: "Stand at the doorway holding keys, touch the door handle, then freeze and look back into the room confused.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand at the doorway holding keys, touch the door handle, then freeze and look back into the room confused. Keep your face flat the whole time; let the silence land.",
    caption: "doorway reached required a hard pause.",
    anchor: "doorway",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "confused_pause",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "realization",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 17,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_018",
    hook: "One shoe on and the plan collapsed",
    whatToShow: "Put on one shoe at the front door, then sit there holding the other shoe while remembering another task.",
    howToFilm: "Phone on a tripod, one locked-off shot. put on one shoe at the front door, then sit there holding the other shoe while remembering another task. Hold the final pause one beat longer than feels comfortable.",
    caption: "task shoe stole the whole window.",
    anchor: "task",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "time_loss",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 18,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_019",
    hook: "The doorknob asked if I was actually ready",
    whatToShow: "Reach for the doorknob confidently, stop mid-grab, then pat pockets and check your bag again.",
    howToFilm: "Phone on a tripod, one locked-off shot. reach for the doorknob confidently, stop mid-grab, then pat pockets and check your bag again. Punch the final beat with one theatrical reaction.",
    caption: "doorknob asked triggered a tiny crisis.",
    anchor: "doorknob",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 19,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_020",
    hook: "My bag got packed and immediately became suspicious",
    whatToShow: "Zip a bag at the doorway, pick it up, pause, then unpack one item to check if it exists.",
    howToFilm: "Phone on a tripod, one locked-off shot. zip a bag at the doorway, pick it up, pause, then unpack one item to check if it exists. Talk-to-camera between beats; loose, a little frantic.",
    caption: "bag packed stayed exactly where it was.",
    anchor: "bag",
    comedyFamily: "adulting_panic",
    emotionalSpike: "avoidance_spike",
    setting: "entryway",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Do not show IDs, cards, or private documents.",
    originalBatchNumber: 20,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_021",
    hook: "The hallway erased my entire purpose",
    whatToShow: "Walk into the hallway with purpose, stop suddenly, turn around, then re-enter the room confused.",
    howToFilm: "Phone on a tripod, one locked-off shot. walk into the hallway with purpose, stop suddenly, turn around, then re-enter the room confused. Keep your face flat the whole time; let the silence land.",
    caption: "hallway erased required a hard pause.",
    anchor: "hallway",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "confused_pause",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid filming neighbors or private building details.",
    originalBatchNumber: 21,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_022",
    hook: "My coat joined the argument too late",
    whatToShow: "Reach the doorway ready to leave, notice the coat, put it on, then realize the outfit feels wrong.",
    howToFilm: "Phone on a tripod, one locked-off shot. reach the doorway ready to leave, notice the coat, put it on, then realize the outfit feels wrong. Hold the final pause one beat longer than feels comfortable.",
    caption: "coat joined happened, then the regret arrived.",
    anchor: "coat",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "instant_regret",
    setting: "entryway",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 22,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_023",
    hook: "I opened the door and remembered three emergencies",
    whatToShow: "Crack open the door, then quickly turn back to grab keys, bag, and one random forgotten item.",
    howToFilm: "Phone on a tripod, one locked-off shot. crack open the door, then quickly turn back to grab keys, bag, and one random forgotten item. Talk-to-camera between beats; loose, a little frantic.",
    caption: "door opened triggered a tiny crisis.",
    anchor: "door",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 23,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_024",
    hook: "Ready to leave became ready to sit down",
    whatToShow: "Stand fully dressed at the doorway, pause, then sit on the nearest chair without taking anything off.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand fully dressed at the doorway, pause, then sit on the nearest chair without taking anything off. Keep your face flat the whole time; let the silence land.",
    caption: "doorway ready won the negotiation.",
    anchor: "doorway",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 24,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_025",
    hook: "The keys moved after I spiritually found them",
    whatToShow: "Spot the keys on a table, turn to grab a jacket, then look back and act like the keys disappeared.",
    howToFilm: "Phone on a tripod, one locked-off shot. spot the keys on a table, turn to grab a jacket, then look back and act like the keys disappeared. Punch the final beat with one theatrical reaction.",
    caption: "keys moved did not warn me.",
    anchor: "keys",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "entryway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Do not show address tags or identifiable key details.",
    originalBatchNumber: 25,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_026",
    hook: "The doorway turned my brain into airport security",
    whatToShow: "At the doorway, pat every pocket, check the bag, check the coat, then repeat once more.",
    howToFilm: "Phone on a tripod, one locked-off shot. at the doorway, pat every pocket, check the bag, check the coat, then repeat once more. Punch the final beat with one theatrical reaction.",
    caption: "pocket doorway triggered a tiny crisis.",
    anchor: "pocket",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing private documents.",
    originalBatchNumber: 26,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_027",
    hook: "I put my shoes on and lost momentum",
    whatToShow: "Tie both shoes at the front door, stand up, then immediately sit back down like the task was enough.",
    howToFilm: "Phone on a tripod, one locked-off shot. tie both shoes at the front door, stand up, then immediately sit back down like the task was enough. Hold the final pause one beat longer than feels comfortable.",
    caption: "shoes lost won the negotiation.",
    anchor: "shoes",
    comedyFamily: "task_avoidance",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 27,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_028",
    hook: "The bag strap attacked my exit timing",
    whatToShow: "Swing a bag onto your shoulder at the doorway, get tangled in the strap, then miss your confident exit.",
    howToFilm: "Phone on a tripod, one locked-off shot. swing a bag onto your shoulder at the doorway, get tangled in the strap, then miss your confident exit. Talk-to-camera between beats; loose, a little frantic.",
    caption: "strap attacked caught me in the act.",
    anchor: "strap",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Keep movement slow and safe.",
    originalBatchNumber: 28,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_029",
    hook: "My hallway walk had too much confidence",
    whatToShow: "Stride down the hallway confidently, then stop because you forgot one item and shuffle backward.",
    howToFilm: "Phone on a tripod, one locked-off shot. stride down the hallway confidently, then stop because you forgot one item and shuffle backward. Keep your face flat the whole time; let the silence land.",
    caption: "stride hallway happened, then the regret arrived.",
    anchor: "stride",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "instant_regret",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    safetyNote: "Avoid filming neighbors or private building details.",
    originalBatchNumber: 29,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_030",
    hook: "I touched the door and became unavailable",
    whatToShow: "Touch the door handle, freeze, then slowly take your hand off and look back at the couch.",
    howToFilm: "Phone on a tripod, one locked-off shot. touch the door handle, freeze, then slowly take your hand off and look back at the couch. Hold the final pause one beat longer than feels comfortable.",
    caption: "handle touched stayed exactly where it was.",
    anchor: "handle",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 30,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_031",
    hook: "The jacket zipper delayed the whole operation",
    whatToShow: "At the doorway, pull a jacket zipper halfway, get stuck, then stand there negotiating with it silently.",
    howToFilm: "Phone on a tripod, one locked-off shot. at the doorway, pull a jacket zipper halfway, get stuck, then stand there negotiating with it silently. Keep your face flat the whole time; let the silence land.",
    caption: "the zipper jacket situation is not okay.",
    anchor: "zipper",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 31,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_032",
    hook: "I forgot something and chose emotional collapse",
    whatToShow: "Step through the doorway, remember something, then slowly return inside with full-body disappointment.",
    howToFilm: "Phone on a tripod, one locked-off shot. step through the doorway, remember something, then slowly return inside with full-body disappointment. Punch the final beat with one theatrical reaction.",
    caption: "return forgot won the negotiation.",
    anchor: "return",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 32,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_033",
    hook: "My closet rejected the entire plan",
    whatToShow: "Open the closet, pull out one shirt, hold it up, then slowly put it back and close the closet.",
    howToFilm: "Phone on a tripod, one locked-off shot. open the closet, pull out one shirt, hold it up, then slowly put it back and close the closet. Keep your face flat the whole time; let the silence land.",
    caption: "closet rejected won the negotiation.",
    anchor: "closet",
    comedyFamily: "getting_ready",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 33,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_034",
    hook: "My jeans asked questions I was not ready for",
    whatToShow: "Try to put on jeans, pause halfway, then sit on the bed and reconsider the entire outfit.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to put on jeans, pause halfway, then sit on the bed and reconsider the entire outfit. Punch the final beat with one theatrical reaction.",
    caption: "bed jeans caught me in the act.",
    anchor: "bed",
    comedyFamily: "getting_ready",
    emotionalSpike: "private_embarrassment",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "accusation",
    safetyNote: "Keep movement safe and comfortable.",
    originalBatchNumber: 34,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_035",
    hook: "The hanger fought harder than expected",
    whatToShow: "Pull a shirt from a hanger, get the hanger caught, then shake it gently while trying to stay calm.",
    howToFilm: "Phone on a tripod, one locked-off shot. pull a shirt from a hanger, get the hanger caught, then shake it gently while trying to stay calm. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the hanger fought situation is not okay.",
    anchor: "hanger",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    originalBatchNumber: 35,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_036",
    hook: "One sock became a personal attack",
    whatToShow: "Look down at one normal sock and one wrong sock, then slowly lift your foot like evidence.",
    howToFilm: "Phone on a tripod, one locked-off shot. look down at one normal sock and one wrong sock, then slowly lift your foot like evidence. Hold the final pause one beat longer than feels comfortable.",
    caption: "sock became did not warn me.",
    anchor: "sock",
    comedyFamily: "getting_ready",
    emotionalSpike: "caught_off_guard",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 36,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_037",
    hook: "My jacket made the whole outfit worse",
    whatToShow: "Check outfit in mirror, add a jacket, then visibly deflate and remove it with disappointment.",
    howToFilm: "Phone on a tripod, one locked-off shot. check outfit in mirror, add a jacket, then visibly deflate and remove it with disappointment. Keep your face flat the whole time; let the silence land.",
    caption: "jacket whole happened, then the regret arrived.",
    anchor: "jacket",
    comedyFamily: "getting_ready",
    emotionalSpike: "instant_regret",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 37,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_038",
    hook: "The belt chose today for character development",
    whatToShow: "Thread a belt through loops, miss one loop, notice it late, then start over with visible defeat.",
    howToFilm: "Phone on a tripod, one locked-off shot. thread a belt through loops, miss one loop, notice it late, then start over with visible defeat. Punch the final beat with one theatrical reaction.",
    caption: "belt chose won the negotiation.",
    anchor: "belt",
    comedyFamily: "parasocial_object",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 38,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_039",
    hook: "My outfit needed math I did not study",
    whatToShow: "Lay out two shirts and one pair of pants, swap combinations, then stare like the outfit became algebra.",
    howToFilm: "Phone on a tripod, one locked-off shot. lay out two shirts and one pair of pants, swap combinations, then stare like the outfit became algebra. Hold the final pause one beat longer than feels comfortable.",
    caption: "outfit needed required a hard pause.",
    anchor: "outfit",
    comedyFamily: "getting_ready",
    emotionalSpike: "confused_pause",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "overdramatic_diagnosis",
    originalBatchNumber: 39,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_040",
    hook: "The sleeve went inside out and won",
    whatToShow: "Try to put on a shirt, discover one sleeve is inside out, then wrestle it gently and give up.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to put on a shirt, discover one sleeve is inside out, then wrestle it gently and give up. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the sleeve went situation is not okay.",
    anchor: "sleeve",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    originalBatchNumber: 40,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_041",
    hook: "My shoes disagreed with the entire vibe",
    whatToShow: "Stand in a finished outfit, look down at shoes, then step backward like the shoes betrayed the plan.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand in a finished outfit, look down at shoes, then step backward like the shoes betrayed the plan. Keep your face flat the whole time; let the silence land.",
    caption: "shoes disagreed happened, then the regret arrived.",
    anchor: "shoes",
    comedyFamily: "getting_ready",
    emotionalSpike: "instant_regret",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "accusation",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 41,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_042",
    hook: "The closet door opened and lowered morale",
    whatToShow: "Open the closet door with hope, stare at clothes, then slowly close it and look at the floor.",
    howToFilm: "Phone on a tripod, one locked-off shot. open the closet door with hope, stare at clothes, then slowly close it and look at the floor. Hold the final pause one beat longer than feels comfortable.",
    caption: "clothes closet won the negotiation.",
    anchor: "clothes",
    comedyFamily: "getting_ready",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 42,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_043",
    hook: "My sweater trapped me in negotiations",
    whatToShow: "Pull on a sweater, get stuck for one second, then emerge with hair or collar messed up.",
    howToFilm: "Phone on a tripod, one locked-off shot. pull on a sweater, get stuck for one second, then emerge with hair or collar messed up. Talk-to-camera between beats; loose, a little frantic.",
    caption: "sweater trapped caught me in the act.",
    anchor: "sweater",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement gentle and safe.",
    originalBatchNumber: 43,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_044",
    hook: "The button entered a long-term conflict",
    whatToShow: "Try fastening one button, miss the hole, try again, then look down at the shirt like it escalated.",
    howToFilm: "Phone on a tripod, one locked-off shot. try fastening one button, miss the hole, try again, then look down at the shirt like it escalated. Keep your face flat the whole time; let the silence land.",
    caption: "the button entered situation is not okay.",
    anchor: "button",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 44,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_045",
    hook: "I changed shirts and lost the plot",
    whatToShow: "Hold two shirts, put one on, immediately remove it, then stand holding both with no clear answer.",
    howToFilm: "Phone on a tripod, one locked-off shot. hold two shirts, put one on, immediately remove it, then stand holding both with no clear answer. Hold the final pause one beat longer than feels comfortable.",
    caption: "shirts changed stole the whole window.",
    anchor: "shirts",
    comedyFamily: "getting_ready",
    emotionalSpike: "time_loss",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "confession",
    originalBatchNumber: 45,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_046",
    hook: "Hoodie strings ruined my leadership",
    whatToShow: "Look in the mirror, notice uneven hoodie strings, pull one side, then make the other side worse.",
    howToFilm: "Phone on a tripod, one locked-off shot. look in the mirror, notice uneven hoodie strings, pull one side, then make the other side worse. Punch the final beat with one theatrical reaction.",
    caption: "hoodie strings triggered a tiny crisis.",
    anchor: "hoodie",
    comedyFamily: "parasocial_object",
    emotionalSpike: "panic",
    setting: "mirror",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 46,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_047",
    hook: "The car seat became a waiting room",
    whatToShow: "Sit in the parked car, hands on the seat or wheel, then lean back and stare forward like you need a minute before going inside.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit in the parked car, hands on the seat or wheel, then lean back and stare forward like you need a minute before going inside. Keep your face flat the whole time; let the silence land.",
    caption: "car seat stayed exactly where it was.",
    anchor: "car",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 47,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_048",
    hook: "I rehearsed hello like it had choreography",
    whatToShow: "In the parked car, practice a normal wave and greeting, then immediately look embarrassed at yourself.",
    howToFilm: "Phone on a tripod, one locked-off shot. in the parked car, practice a normal wave and greeting, then immediately look embarrassed at yourself. Talk-to-camera between beats; loose, a little frantic.",
    caption: "car rehearsed caught me in the act.",
    anchor: "car",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "car",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 48,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_049",
    hook: "The seatbelt trapped my dramatic exit",
    whatToShow: "Try to leave the parked car confidently, forget the seatbelt, get pulled back gently, then pause in defeat.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to leave the parked car confidently, forget the seatbelt, get pulled back gently, then pause in defeat. Punch the final beat with one theatrical reaction.",
    caption: "seatbelt trapped did not warn me.",
    anchor: "seatbelt",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 49,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_050",
    hook: "Car mirror confidence lasted exactly four seconds",
    whatToShow: "Check yourself in the car mirror, nod confidently, then notice one detail and start fixing everything.",
    howToFilm: "Phone on a tripod, one locked-off shot. check yourself in the car mirror, nod confidently, then notice one detail and start fixing everything. Hold the final pause one beat longer than feels comfortable.",
    caption: "mirror confidence happened, then the regret arrived.",
    anchor: "mirror",
    comedyFamily: "getting_ready",
    emotionalSpike: "instant_regret",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 50,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_051",
    hook: "The passenger seat became my command center",
    whatToShow: "Arrange a bag, jacket, receipt, and keys on the passenger seat, then lose one item under the pile.",
    howToFilm: "Phone on a tripod, one locked-off shot. arrange a bag, jacket, receipt, and keys on the passenger seat, then lose one item under the pile. Keep your face flat the whole time; let the silence land.",
    caption: "seat passenger required a hard pause.",
    anchor: "seat",
    comedyFamily: "adulting_panic",
    emotionalSpike: "confused_pause",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 51,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_052",
    hook: "I arrived early and still wasn’t ready",
    whatToShow: "Sit in the parked car, check the door outside, adjust jacket, then continue sitting instead of leaving.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit in the parked car, check the door outside, adjust jacket, then continue sitting instead of leaving. Hold the final pause one beat longer than feels comfortable.",
    caption: "jacket arrived stayed exactly where it was.",
    anchor: "jacket",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "avoidance_spike",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 52,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_053",
    hook: "The steering wheel heard my entire pep talk",
    whatToShow: "Grip the steering wheel in the parked car and silently hype yourself up before opening the door.",
    howToFilm: "Phone on a tripod, one locked-off shot. grip the steering wheel in the parked car and silently hype yourself up before opening the door. Punch the final beat with one theatrical reaction.",
    caption: "wheel steering earned no real points.",
    anchor: "wheel",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "false_productivity",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 53,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_054",
    hook: "The receipt made the car very quiet",
    whatToShow: "In the parked car, unfold a receipt, glance at the bags, then fold it back with silent regret.",
    howToFilm: "Phone on a tripod, one locked-off shot. in the parked car, unfold a receipt, glance at the bags, then fold it back with silent regret. Keep your face flat the whole time; let the silence land.",
    caption: "receipt very explained the whole morning.",
    anchor: "receipt",
    comedyFamily: "adulting_panic",
    emotionalSpike: "quiet_realization",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    safetyNote: "Film while parked only. Do not film while driving. Hide payment/store details if needed.",
    originalBatchNumber: 54,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_055",
    hook: "My car keys started the second errand crisis",
    whatToShow: "Hold car keys in the parked car, prepare to leave, then realize you need something from the back seat.",
    howToFilm: "Phone on a tripod, one locked-off shot. hold car keys in the parked car, prepare to leave, then realize you need something from the back seat. Talk-to-camera between beats; loose, a little frantic.",
    caption: "keys started triggered a tiny crisis.",
    anchor: "keys",
    comedyFamily: "task_avoidance",
    emotionalSpike: "panic",
    setting: "car",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 55,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_056",
    hook: "The car door opened before my courage did",
    whatToShow: "Open the car door from inside, pause with one foot out, then pull the foot back in for one more second.",
    howToFilm: "Phone on a tripod, one locked-off shot. open the car door from inside, pause with one foot out, then pull the foot back in for one more second. Hold the final pause one beat longer than feels comfortable.",
    caption: "door opened stayed exactly where it was.",
    anchor: "door",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 56,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_057",
    hook: "The glovebox contained everything except maturity",
    whatToShow: "Open the glovebox in the parked car, reveal napkins and random items, then fail to find the one needed thing.",
    howToFilm: "Phone on a tripod, one locked-off shot. open the glovebox in the parked car, reveal napkins and random items, then fail to find the one needed thing. Keep your face flat the whole time; let the silence land.",
    caption: "glovebox contained required a hard pause.",
    anchor: "glovebox",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "confused_pause",
    setting: "car",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 57,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_058",
    hook: "I parked and became emotionally unavailable",
    whatToShow: "Sit in the parked car after arriving, unbuckle, then rebuckle or lean back like you need a reset.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit in the parked car after arriving, unbuckle, then rebuckle or lean back like you need a reset. Punch the final beat with one theatrical reaction.",
    caption: "reset parked won the negotiation.",
    anchor: "reset",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Film while parked only. Do not film while driving.",
    originalBatchNumber: 58,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_059",
    hook: "I stood up like my knees signed approval",
    whatToShow: "Rise from a chair too confidently, pause halfway, then adjust your stance like the chair exposed you.",
    howToFilm: "Phone on a tripod, one locked-off shot. rise from a chair too confidently, pause halfway, then adjust your stance like the chair exposed you. Keep your face flat the whole time; let the silence land.",
    caption: "chair stood did not warn me.",
    anchor: "chair",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement gentle and safe.",
    originalBatchNumber: 59,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_060",
    hook: "The floor item became a whole commitment",
    whatToShow: "Drop a small item on the floor, look down, bend halfway, then reconsider and use your foot to move it closer.",
    howToFilm: "Phone on a tripod, one locked-off shot. drop a small item on the floor, look down, bend halfway, then reconsider and use your foot to move it closer. Hold the final pause one beat longer than feels comfortable.",
    caption: "floor item won the negotiation.",
    anchor: "floor",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Keep movement safe and avoid strain.",
    originalBatchNumber: 60,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_061",
    hook: "My sock slide had too much ambition",
    whatToShow: "Attempt a tiny sock slide across the floor, immediately lose balance slightly, then freeze and pretend it was planned.",
    howToFilm: "Phone on a tripod, one locked-off shot. attempt a tiny sock slide across the floor, immediately lose balance slightly, then freeze and pretend it was planned. Talk-to-camera between beats; loose, a little frantic.",
    caption: "sock slide caught me in the act.",
    anchor: "sock",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "living_room",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    safetyNote: "Use a clear floor and keep movement small.",
    originalBatchNumber: 61,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_062",
    hook: "The blanket refused to release its hostage",
    whatToShow: "Try to stand from the couch while tangled in a blanket, take one step, then return to untangle.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to stand from the couch while tangled in a blanket, take one step, then return to untangle. Punch the final beat with one theatrical reaction.",
    caption: "blanket refused did not warn me.",
    anchor: "blanket",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "couch",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Keep steps slow and avoid tripping.",
    originalBatchNumber: 62,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_063",
    hook: "The pillow rearranged my spine without permission",
    whatToShow: "Lie on a pillow, adjust it repeatedly, then sit up looking personally offended by the pillow.",
    howToFilm: "Phone on a tripod, one locked-off shot. lie on a pillow, adjust it repeatedly, then sit up looking personally offended by the pillow. Keep your face flat the whole time; let the silence land.",
    caption: "the pillow rearranged situation is not okay.",
    anchor: "pillow",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "accusation",
    originalBatchNumber: 63,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_064",
    hook: "My chair squeaked and exposed the operation",
    whatToShow: "Sit carefully in a chair, hear a squeak, freeze, then sit even slower like negotiating peace.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit carefully in a chair, hear a squeak, freeze, then sit even slower like negotiating peace. Hold the final pause one beat longer than feels comfortable.",
    caption: "squeak chair caught me in the act.",
    anchor: "squeak",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "private_embarrassment",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    safetyNote: "Use a stable chair.",
    originalBatchNumber: 64,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_065",
    hook: "The rug tried to humble my confidence",
    whatToShow: "Walk across a rug, catch your foot slightly, then look back at the rug like it started something.",
    howToFilm: "Phone on a tripod, one locked-off shot. walk across a rug, catch your foot slightly, then look back at the rug like it started something. Punch the final beat with one theatrical reaction.",
    caption: "rug tried did not warn me.",
    anchor: "rug",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "accusation",
    safetyNote: "Use a safe, tiny stumble only; avoid actual tripping.",
    originalBatchNumber: 65,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_066",
    hook: "I bent down and aged seven minutes",
    whatToShow: "Bend to pick up one object, pause dramatically, then stand up slowly holding the item like a trophy.",
    howToFilm: "Phone on a tripod, one locked-off shot. bend to pick up one object, pause dramatically, then stand up slowly holding the item like a trophy. Keep your face flat the whole time; let the silence land.",
    caption: "object bent won the negotiation.",
    anchor: "object",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Keep movement gentle and safe.",
    originalBatchNumber: 66,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_067",
    hook: "The blanket escape needed more strategy",
    whatToShow: "Try to leave bed or couch under a blanket, get one foot trapped, then carefully reverse and start again.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to leave bed or couch under a blanket, get one foot trapped, then carefully reverse and start again. Talk-to-camera between beats; loose, a little frantic.",
    caption: "foot blanket stole the whole window.",
    anchor: "foot",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "time_loss",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement slow and avoid tripping.",
    originalBatchNumber: 67,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_068",
    hook: "My slippers gave me false athletic confidence",
    whatToShow: "Shuffle quickly in slippers, stop when one almost slides off, then look down with betrayed confidence.",
    howToFilm: "Phone on a tripod, one locked-off shot. shuffle quickly in slippers, stop when one almost slides off, then look down with betrayed confidence. Hold the final pause one beat longer than feels comfortable.",
    caption: "slippers gave earned no real points.",
    anchor: "slippers",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "false_productivity",
    setting: "hallway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Keep movement slow and controlled.",
    originalBatchNumber: 68,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_069",
    hook: "Couch accepted my failed escape attempt",
    whatToShow: "Start standing from the couch, get halfway up, then sink back down like the couch made a strong argument.",
    howToFilm: "Phone on a tripod, one locked-off shot. start standing from the couch, get halfway up, then sink back down like the couch made a strong argument. Keep your face flat the whole time; let the silence land.",
    caption: "couch accepted won the negotiation.",
    anchor: "couch",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 69,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_070",
    hook: "I stretched once and needed a statement",
    whatToShow: "Do one small stretch, pause dramatically, then sit down like the stretch required formal recovery.",
    howToFilm: "Phone on a tripod, one locked-off shot. do one small stretch, pause dramatically, then sit down like the stretch required formal recovery. Punch the final beat with one theatrical reaction.",
    caption: "stretch stretched earned no real points.",
    anchor: "stretch",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "false_productivity",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Keep the stretch gentle and safe.",
    originalBatchNumber: 70,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_071",
    hook: "The pillow fight was against my comfort",
    whatToShow: "Fluff a pillow aggressively, place it behind you, then immediately pull it out because it feels wrong.",
    howToFilm: "Phone on a tripod, one locked-off shot. fluff a pillow aggressively, place it behind you, then immediately pull it out because it feels wrong. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the pillow fight situation is not okay.",
    anchor: "pillow",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 71,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_072",
    hook: "My balance left before the errand did",
    whatToShow: "Stand on one foot to put on a shoe, wobble safely, then sit down with instant humility.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand on one foot to put on a shoe, wobble safely, then sit down with instant humility. Hold the final pause one beat longer than feels comfortable.",
    caption: "shoe balance did not warn me.",
    anchor: "shoe",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "entryway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Use a wall or chair nearby for balance.",
    originalBatchNumber: 72,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_073",
    hook: "The chair caught me sitting down emotionally",
    whatToShow: "Approach a chair like you are just resting briefly, then sink into it with full dramatic surrender.",
    howToFilm: "Phone on a tripod, one locked-off shot. approach a chair like you are just resting briefly, then sink into it with full dramatic surrender. Keep your face flat the whole time; let the silence land.",
    caption: "chair caught won the negotiation.",
    anchor: "chair",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Use a stable chair.",
    originalBatchNumber: 73,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_074",
    hook: "The broom made cleaning legally binding",
    whatToShow: "Pick up a broom to sweep one spot, notice another spot, then stand there realizing the broom started a whole job.",
    howToFilm: "Phone on a tripod, one locked-off shot. pick up a broom to sweep one spot, notice another spot, then stand there realizing the broom started a whole job. Hold the final pause one beat longer than feels comfortable.",
    caption: "broom cleaning happened, then the regret arrived.",
    anchor: "broom",
    comedyFamily: "parasocial_object",
    emotionalSpike: "instant_regret",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 74,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_075",
    hook: "The drawer opened and revealed consequences",
    whatToShow: "Open a drawer looking for one item, find a messy pile, then slowly close the drawer without solving anything.",
    howToFilm: "Phone on a tripod, one locked-off shot. open a drawer looking for one item, find a messy pile, then slowly close the drawer without solving anything. Keep your face flat the whole time; let the silence land.",
    caption: "drawer opened stayed exactly where it was.",
    anchor: "drawer",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "avoidance_spike",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Avoid showing private documents.",
    originalBatchNumber: 75,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_076",
    hook: "The cabinet door chose public disrespect",
    whatToShow: "Close a cabinet door, watch it swing open again, then push it closed with increasing seriousness.",
    howToFilm: "Phone on a tripod, one locked-off shot. close a cabinet door, watch it swing open again, then push it closed with increasing seriousness. Punch the final beat with one theatrical reaction.",
    caption: "the cabinet door situation is not okay.",
    anchor: "cabinet",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 76,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_077",
    hook: "The lid refused the entire household",
    whatToShow: "Try to place a lid on a container, rotate it several times, then realize it belongs to something else.",
    howToFilm: "Phone on a tripod, one locked-off shot. try to place a lid on a container, rotate it several times, then realize it belongs to something else. Talk-to-camera between beats; loose, a little frantic.",
    caption: "lid refused required a hard pause.",
    anchor: "lid",
    comedyFamily: "parasocial_object",
    emotionalSpike: "confused_pause",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 77,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_078",
    hook: "My zipper waited until confidence arrived",
    whatToShow: "Zip a bag or jacket confidently, get stuck halfway, then look directly at the zipper like it planned this.",
    howToFilm: "Phone on a tripod, one locked-off shot. zip a bag or jacket confidently, get stuck halfway, then look directly at the zipper like it planned this. Keep your face flat the whole time; let the silence land.",
    caption: "stuck zipper happened, then the regret arrived.",
    anchor: "stuck",
    comedyFamily: "parasocial_object",
    emotionalSpike: "instant_regret",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "accusation",
    originalBatchNumber: 78,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_079",
    hook: "A shoelace resigned during business hours",
    whatToShow: "Tie a shoelace at the doorway, stand up, then watch the shoelace immediately loosen.",
    howToFilm: "Phone on a tripod, one locked-off shot. tie a shoelace at the doorway, stand up, then watch the shoelace immediately loosen. Punch the final beat with one theatrical reaction.",
    caption: "the shoelace resigned situation is not okay.",
    anchor: "shoelace",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 79,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_080",
    hook: "The reusable bag folded me into confusion",
    whatToShow: "Try folding a reusable bag neatly, lose the shape, then stuff it into itself with quiet defeat.",
    howToFilm: "Phone on a tripod, one locked-off shot. try folding a reusable bag neatly, lose the shape, then stuff it into itself with quiet defeat. Hold the final pause one beat longer than feels comfortable.",
    caption: "bag reusable required a hard pause.",
    anchor: "bag",
    comedyFamily: "parasocial_object",
    emotionalSpike: "confused_pause",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 80,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_081",
    hook: "The tape stuck to everyone except the package",
    whatToShow: "Seal a package with tape, get the tape stuck to your fingers, scissors, or counter instead.",
    howToFilm: "Phone on a tripod, one locked-off shot. seal a package with tape, get the tape stuck to your fingers, scissors, or counter instead. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the tape stuck situation is not okay.",
    anchor: "tape",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Keep scissors or sharp tools out of frame if not needed.",
    originalBatchNumber: 81,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_082",
    hook: "Doorknob made leaving optional again",
    whatToShow: "Grab the doorknob, realize your sleeve or bag is caught, then slowly let go and reset.",
    howToFilm: "Phone on a tripod, one locked-off shot. grab the doorknob, realize your sleeve or bag is caught, then slowly let go and reset. Keep your face flat the whole time; let the silence land.",
    caption: "doorknob leaving won the negotiation.",
    anchor: "doorknob",
    comedyFamily: "parasocial_object",
    emotionalSpike: "quiet_defeat",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 82,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_083",
    hook: "The package became a doorway decoration",
    whatToShow: "Place a return package by the doorway, walk past it twice, then pretend not to see it.",
    howToFilm: "Phone on a tripod, one locked-off shot. place a return package by the doorway, walk past it twice, then pretend not to see it. Keep your face flat the whole time; let the silence land.",
    caption: "package became stayed exactly where it was.",
    anchor: "package",
    comedyFamily: "task_avoidance",
    emotionalSpike: "avoidance_spike",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide names, addresses, and labels.",
    originalBatchNumber: 83,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_084",
    hook: "Kitchen counter checkout had unexpected pressure",
    whatToShow: "Set items on the kitchen counter like self-checkout, pretend to scan them, then freeze when one item will not “scan.”",
    howToFilm: "Phone on a tripod, one locked-off shot. set items on the kitchen counter like self-checkout, pretend to scan them, then freeze when one item will not “scan.” Talk-to-camera between beats; loose, a little frantic.",
    caption: "counter kitchen triggered a tiny crisis.",
    anchor: "counter",
    comedyFamily: "task_avoidance",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 84,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_085",
    hook: "The return label became a full obstacle",
    whatToShow: "Hold a package and return label, line it up badly, peel it crooked, then stare at the package.",
    howToFilm: "Phone on a tripod, one locked-off shot. hold a package and return label, line it up badly, peel it crooked, then stare at the package. Hold the final pause one beat longer than feels comfortable.",
    caption: "the label return situation is not okay.",
    anchor: "label",
    comedyFamily: "task_avoidance",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    safetyNote: "Hide names, addresses, and labels.",
    originalBatchNumber: 85,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_086",
    hook: "I recreated the waiting room too accurately",
    whatToShow: "Sit stiffly in a chair, hold a bag in your lap, look around your living room like you are waiting to be called.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit stiffly in a chair, hold a bag in your lap, look around your living room like you are waiting to be called. Keep your face flat the whole time; let the silence land.",
    caption: "chair recreated caught me in the act.",
    anchor: "chair",
    comedyFamily: "task_avoidance",
    emotionalSpike: "private_embarrassment",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid medical framing or private health details.",
    originalBatchNumber: 86,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_087",
    hook: "My pantry became a grocery aisle with judgment",
    whatToShow: "Stand at the pantry, compare two items in your hands like you are shopping, then choose neither.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand at the pantry, compare two items in your hands like you are shopping, then choose neither. Hold the final pause one beat longer than feels comfortable.",
    caption: "pantry became required a hard pause.",
    anchor: "pantry",
    comedyFamily: "task_avoidance",
    emotionalSpike: "confused_pause",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 87,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_088",
    hook: "The receipt review became a small trial",
    whatToShow: "Spread a receipt on the kitchen counter, point at one line, then look at the item like it betrayed you.",
    howToFilm: "Phone on a tripod, one locked-off shot. spread a receipt on the kitchen counter, point at one line, then look at the item like it betrayed you. Punch the final beat with one theatrical reaction.",
    caption: "receipt review explained the whole morning.",
    anchor: "receipt",
    comedyFamily: "task_avoidance",
    emotionalSpike: "quiet_realization",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide payment/store details if needed.",
    originalBatchNumber: 88,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_089",
    hook: "I practiced small talk with a cereal box",
    whatToShow: "Place a cereal box on the counter, rehearse a normal greeting to it, then immediately cringe.",
    howToFilm: "Phone on a tripod, one locked-off shot. place a cereal box on the counter, rehearse a normal greeting to it, then immediately cringe. Talk-to-camera between beats; loose, a little frantic.",
    caption: "box practiced caught me in the act.",
    anchor: "box",
    comedyFamily: "task_avoidance",
    emotionalSpike: "private_embarrassment",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    originalBatchNumber: 89,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_090",
    hook: "The tote bag made errands look official",
    whatToShow: "Pack a tote bag with one item, stand proudly, then realize you forgot the actual errand item.",
    howToFilm: "Phone on a tripod, one locked-off shot. pack a tote bag with one item, stand proudly, then realize you forgot the actual errand item. Keep your face flat the whole time; let the silence land.",
    caption: "bag tote happened, then the regret arrived.",
    anchor: "bag",
    comedyFamily: "task_avoidance",
    emotionalSpike: "instant_regret",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    safetyNote: "Do not show IDs, cards, or private documents.",
    originalBatchNumber: 90,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_091",
    hook: "I got ready for plans and sat down",
    whatToShow: "Stand fully dressed near the mirror, grab your bag, then sit on the couch like the preparation was the event.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand fully dressed near the mirror, grab your bag, then sit on the couch like the preparation was the event. Keep your face flat the whole time; let the silence land.",
    caption: "bag ready won the negotiation.",
    anchor: "bag",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "quiet_defeat",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 91,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_092",
    hook: "My casual outfit required a legal review",
    whatToShow: "Hold two casual outfit options, inspect both in the mirror, then change into a third unrelated option.",
    howToFilm: "Phone on a tripod, one locked-off shot. hold two casual outfit options, inspect both in the mirror, then change into a third unrelated option. Punch the final beat with one theatrical reaction.",
    caption: "outfit casual stole the whole window.",
    anchor: "outfit",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "time_loss",
    setting: "mirror",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid showing private background details.",
    originalBatchNumber: 92,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_093",
    hook: "I rehearsed a normal greeting and made it weird",
    whatToShow: "Stand in the hallway, practice saying hello to an empty room, then stop because it sounded unnatural.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand in the hallway, practice saying hello to an empty room, then stop because it sounded unnatural. Talk-to-camera between beats; loose, a little frantic.",
    caption: "hallway rehearsed caught me in the act.",
    anchor: "hallway",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "hallway",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Avoid filming neighbors or private building details.",
    originalBatchNumber: 93,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_094",
    hook: "The guest pillow created fake responsibility",
    whatToShow: "Place a guest pillow on the couch, adjust it three times, then notice the rest of the room is messy.",
    howToFilm: "Phone on a tripod, one locked-off shot. place a guest pillow on the couch, adjust it three times, then notice the rest of the room is messy. Hold the final pause one beat longer than feels comfortable.",
    caption: "pillow guest triggered a tiny crisis.",
    anchor: "pillow",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "panic",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 94,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_095",
    hook: "I picked a jacket for imaginary weather",
    whatToShow: "Try one jacket, look toward the door, switch jackets, then stand holding both like there is no answer.",
    howToFilm: "Phone on a tripod, one locked-off shot. try one jacket, look toward the door, switch jackets, then stand holding both like there is no answer. Keep your face flat the whole time; let the silence land.",
    caption: "jacket picked required a hard pause.",
    anchor: "jacket",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "confused_pause",
    setting: "entryway",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 95,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_096",
    hook: "The snack bowl became my hosting personality",
    whatToShow: "Set out a snack bowl, adjust it seriously, then stand back like the room suddenly has hospitality.",
    howToFilm: "Phone on a tripod, one locked-off shot. set out a snack bowl, adjust it seriously, then stand back like the room suddenly has hospitality. Punch the final beat with one theatrical reaction.",
    caption: "bowl snack earned no real points.",
    anchor: "bowl",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "false_productivity",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 96,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_097",
    hook: "I practiced being relaxed and failed immediately",
    whatToShow: "Sit on the couch in a casual pose for plans, adjust your arms, legs, and face until it looks worse.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit on the couch in a casual pose for plans, adjust your arms, legs, and face until it looks worse. Talk-to-camera between beats; loose, a little frantic.",
    caption: "couch practiced caught me in the act.",
    anchor: "couch",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    originalBatchNumber: 97,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_098",
    hook: "The doorbell practice lowered morale",
    whatToShow: "Stand near the front door, mime hearing a doorbell, compose yourself, then immediately lose composure.",
    howToFilm: "Phone on a tripod, one locked-off shot. stand near the front door, mime hearing a doorbell, compose yourself, then immediately lose composure. Hold the final pause one beat longer than feels comfortable.",
    caption: "doorbell practice triggered a tiny crisis.",
    anchor: "doorbell",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Avoid showing address or exterior details.",
    originalBatchNumber: 98,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_099",
    hook: "I dressed for plans and became furniture",
    whatToShow: "Sit fully dressed on the couch, shoes on, jacket ready, completely still like a decorative object.",
    howToFilm: "Phone on a tripod, one locked-off shot. sit fully dressed on the couch, shoes on, jacket ready, completely still like a decorative object. Keep your face flat the whole time; let the silence land.",
    caption: "jacket dressed stayed exactly where it was.",
    anchor: "jacket",
    comedyFamily: "procrastination",
    emotionalSpike: "avoidance_spike",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "realization",
    originalBatchNumber: 99,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_t_diversity_100",
    hook: "My entrance wave had too many drafts",
    whatToShow: "Practice entering the room and waving, reset twice, then choose the smallest awkward wave possible.",
    howToFilm: "Phone on a tripod, one locked-off shot. practice entering the room and waving, reset twice, then choose the smallest awkward wave possible. Talk-to-camera between beats; loose, a little frantic.",
    caption: "wave entrance caught me in the act.",
    anchor: "wave",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "private_embarrassment",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 100,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
    ]);
