/**
   * PHASE W2-L — curated W2-BATCH-NEXT promotion entries (DARK by
   * default; surfaced through the W2-K runtime path via
   * `westernHookPackApproved.ts`).
   *
   * 100 editorial-curated Western hooks supplied as a single batch
   * (W2-BATCH-NEXT-001..100). Imported under Path A guardrails:
   *
   *   • single runtime path — entries flow through the SAME approved
   *     pool that W2-K activated; no new public API surface.
   *   • howToFilm is SYNTHESIZED deterministically per entry from the
   *     curated WHAT TO SHOW (each entry's actual beat narration),
   *     prefixed with a tripod/single-shot framing directive and
   *     suffixed with a voice-cluster-keyed payoff cue. Result:
   *     100 distinct howToFilm strings, every one mentioning the
   *     entry's actual props/actions and ending on a payoff beat —
   *     no generic "framed on the {anchor}" filler.
   *   • caption is synthesized deterministically per entry by spike
   *     bucket × anchor (verified 100/100 distinct).
   *   • freeform vocab from the curated batch (Comedy family,
   *     Emotional spike, Setting) is normalized into the EXISTING
   *     `WESTERN_COMEDY_FAMILIES` / `WESTERN_EMOTIONAL_SPIKES` /
   *     `WESTERN_SETTINGS` controlled vocab — no enum widening was
   *     necessary for any curated entry.
   *   • voiceCluster is normalized into the W2-L-additive
   *     `WESTERN_VOICE_CLUSTERS` vocab (4 values supplied by review).
   *   • hookStyle is normalized into the W2-L-additive
   *     `WESTERN_BATCH_HOOK_STYLES` vocab (10 values surfaced by the
   *     curated batch; snake_cased from the editorial labels).
   *   • safetyNote is preserved verbatim from the curated batch on the
   *     ~half of entries that carry one (the other half explicitly
   *     state "None" → stored as the optional field being unset).
   *   • originalBatchNumber preserves the W2-BATCH-NEXT row number
   *     (1..100) for editorial traceback. The owning batch label is
   *     derivable from the id prefix via `getWesternEntrySourceBatch`.
   *   • whyThisWorks is intentionally NOT carried on the runtime entry
   *     — the W2 runtime type by design excludes editorial commentary
   *     (the hook + whatToShow + caption already carry the creative
   *     intent the runtime needs). The full whyThisWorks text remains
   *     in the curated source attachment + the W2-L import report.
   *   • anchor is normalized to a single token that appears
   *     (lowercased) in whatToShow — exactly the invariant the W2-I
   *     unit test enforces. Five entries (#36, #66, #74, #81, #86)
   *     received an anchor swap to avoid collision with an existing
   *     approved (anchor|setting|comedyFamily) triple; one entry
   *     (#38) received an anchor swap to avoid collision with another
   *     batch entry on (comedyFamily|emotionalSpike|anchor).
   *
   * Cross-batch dedup verified at import time vs:
   *   • `APPROVED_WESTERN_PROMOTION_CANDIDATES` (existing 100)
   *   • `WESTERN_HOOK_PACK_DRAFT` (150)
   *   • `userBlessedHookCorpus.ts` (heuristic string scan)
   *   • this batch's own running set
   *
   * Exact-hook, normalized-skeleton (long tokens >=5 chars -> "__",
   * cap 24), bigram-Jaccard >= 0.50, and (anchor|setting|comedyFamily)
   * triple — all enforced at import time. Result: 100/100 accepted.
   *
   * Production stays OFF — gating still flows through
   * `isWesternApprovedPoolFeatureEnabled` +
   * `canActivateWesternApprovedPool`. Promotion to live requires a
   * separate editorial-review PR that overwrites
   * `reviewedBy: PENDING_EDITORIAL_REVIEW`.
   */

  import {
    PENDING_EDITORIAL_REVIEW,
    type WesternHookPackDraftEntry,
  } from "./westernHookPack.js";

  export const WESTERN_HOOK_PACK_BATCH_NEXT_IDS: readonly string[] =
    Object.freeze([
    "w2_next_001",
  "w2_next_002",
  "w2_next_003",
  "w2_next_004",
  "w2_next_005",
  "w2_next_006",
  "w2_next_007",
  "w2_next_008",
  "w2_next_009",
  "w2_next_010",
  "w2_next_011",
  "w2_next_012",
  "w2_next_013",
  "w2_next_014",
  "w2_next_015",
  "w2_next_016",
  "w2_next_017",
  "w2_next_018",
  "w2_next_019",
  "w2_next_020",
  "w2_next_021",
  "w2_next_022",
  "w2_next_023",
  "w2_next_024",
  "w2_next_025",
  "w2_next_026",
  "w2_next_027",
  "w2_next_028",
  "w2_next_029",
  "w2_next_030",
  "w2_next_031",
  "w2_next_032",
  "w2_next_033",
  "w2_next_034",
  "w2_next_035",
  "w2_next_036",
  "w2_next_037",
  "w2_next_038",
  "w2_next_039",
  "w2_next_040",
  "w2_next_041",
  "w2_next_042",
  "w2_next_043",
  "w2_next_044",
  "w2_next_045",
  "w2_next_046",
  "w2_next_047",
  "w2_next_048",
  "w2_next_049",
  "w2_next_050",
  "w2_next_051",
  "w2_next_052",
  "w2_next_053",
  "w2_next_054",
  "w2_next_055",
  "w2_next_056",
  "w2_next_057",
  "w2_next_058",
  "w2_next_059",
  "w2_next_060",
  "w2_next_061",
  "w2_next_062",
  "w2_next_063",
  "w2_next_064",
  "w2_next_065",
  "w2_next_066",
  "w2_next_067",
  "w2_next_068",
  "w2_next_069",
  "w2_next_070",
  "w2_next_071",
  "w2_next_072",
  "w2_next_073",
  "w2_next_074",
  "w2_next_075",
  "w2_next_076",
  "w2_next_077",
  "w2_next_078",
  "w2_next_079",
  "w2_next_080",
  "w2_next_081",
  "w2_next_082",
  "w2_next_083",
  "w2_next_084",
  "w2_next_085",
  "w2_next_086",
  "w2_next_087",
  "w2_next_088",
  "w2_next_089",
  "w2_next_090",
  "w2_next_091",
  "w2_next_092",
  "w2_next_093",
  "w2_next_094",
  "w2_next_095",
  "w2_next_096",
  "w2_next_097",
  "w2_next_098",
  "w2_next_099",
  "w2_next_100",
    ]);

  export const WESTERN_HOOK_PACK_BATCH_NEXT: readonly WesternHookPackDraftEntry[] =
    Object.freeze([
    {
      id: "w2_next_001",
      hook: "My fridge light just exposed another week of good intentions",
      whatToShow:
        "Fridge door swings open, slow pan across wilting kale bag next to three identical takeout containers, hand grabs yogurt instead, door slams",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Fridge door swings open, slow pan across wilting kale bag next to three identical takeout containers, hand grabs yogurt instead, door slams. End on a held silent stare; let the realization sit.",
      caption: "the fridge knows.",
      anchor: "fridge",
      comedyFamily: "anxious_optimism",
      emotionalSpike: "self_critique",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
      originalBatchNumber: 1,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_002",
      hook: "The takeout bag math that never adds up",
      whatToShow:
        "Creator unpacks the takeout bag on the kitchen counter, counts twelve sauce packets and three napkins, then finally lifts out one tiny entrée and stares at the bag like it committed fraud.",
      howToFilm:
        "Lock the phone on the kitchen counter. Pull out the sauce packets one by one like evidence, then reveal the tiny entrée last. End on a flat stare at the oversized bag.",
      caption: "twelve sauces. one entrée. no explanation.",
      anchor: "takeout",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "accusation",
      originalBatchNumber: 2,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_003",
      hook: "Third night of leftovers and I’m still pretending",
      whatToShow:
        "Creator opens the microwave on the third night of leftovers, sniffs the Tupperware, takes one brave bite, and nods like this was always dinner.",
      howToFilm:
        "Frame the microwave and Tupperware. Open it like you are already suspicious, take the third-night bite, then nod through visible regret.",
      caption: "third night. same lie.",
      anchor: "third",
      comedyFamily: "self_betrayal",
      emotionalSpike: "avoidance_spike",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "confession",
      originalBatchNumber: 3,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_004",
      hook: "Cutting board looks like a crime scene every single time",
      whatToShow:
        "Close-up of a cutting board covered in uneven carrot chunks, knife pauses mid-chop, creator compares it to the recipe photo and stares in defeat.",
      howToFilm:
        "Shoot down at the cutting board. Show the recipe photo, the chaotic carrot pieces, then pause the knife like the board has evidence on it.",
      caption: "the cutting board saw everything.",
      anchor: "cutting",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "chaotic_confession",
      hookStyle: "fake_tutorial",
    safetyNote: "Avoid showing private recipe accounts or personal tabs.",
      originalBatchNumber: 4,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_005",
      hook: "Grocery bags unloaded and the snacks won again",
      whatToShow:
        "Creator unloads grocery bags onto the counter, places one healthy item down carefully, then keeps pulling out snacks until the chips fully block it from view.",
      howToFilm:
        "Start with the grocery bags in frame. Put the healthy item down like you had a plan, then stack snacks around it until it disappears. End by quietly accepting the snack pile.",
      caption: "the snacks had numbers.",
      anchor: "snacks",
      comedyFamily: "self_betrayal",
      emotionalSpike: "instant_regret",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "before_after_self",
      originalBatchNumber: 5,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_006",
      hook: "That unopened yogurt is now part of the fridge furniture",
      whatToShow:
        "Fridge door opens, hand reaches for yogurt, pauses at the date, gently rotates it to the back like hiding evidence",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Fridge door opens, hand reaches for yogurt, pauses at the date, gently rotates it to the back like hiding evidence. End on a held silent stare; let the realization sit.",
      caption: "yogurt update: not great.",
      anchor: "yogurt",
      comedyFamily: "parasocial_object",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
      originalBatchNumber: 6,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_007",
      hook: "I bought oat milk like an adult and it’s still unopened",
      whatToShow:
        "Fridge pull, oat milk carton held up proudly then placed back untouched next to regular milk",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Fridge pull, oat milk carton held up proudly then placed back untouched next to regular milk. Punch the final beat with one theatrical reaction.",
      caption: "milk update: not great.",
      anchor: "milk",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "confession",
      originalBatchNumber: 7,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_008",
      hook: "Microwave said done and I still negotiated with it",
      whatToShow:
        "Microwave beeps, food gets opened, poked once, door closes again for “just 12 more seconds”",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Microwave beeps, food gets opened, poked once, door closes again for “just 12 more seconds”. Keep your face flat the whole time; let the silence land.",
      caption: "food math.",
      anchor: "food",
      comedyFamily: "task_avoidance",
      emotionalSpike: "confused_pause",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
      originalBatchNumber: 8,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_009",
      hook: "My “one bowl” dinner turned into three separate plates",
      whatToShow:
        "Counter with one empty bowl then three half-used plates of random ingredients",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Counter with one empty bowl then three half-used plates of random ingredients. Talk-to-camera between beats; loose, a little frantic.",
      caption: "bowl update: not great.",
      anchor: "bowl",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "chaotic_confession",
      hookStyle: "realization",
      originalBatchNumber: 9,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_010",
      hook: "Freezer drawer refuses to close for the fourth night",
      whatToShow:
        "Freezer door open, hand shoving ice cream tub deeper, drawer still won’t shut",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Freezer door open, hand shoving ice cream tub deeper, drawer still won’t shut. End on a held silent stare; let the realization sit.",
      caption: "freezer won.",
      anchor: "freezer",
      comedyFamily: "parasocial_object",
      emotionalSpike: "polite_rage",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "object_betrayal",
      originalBatchNumber: 10,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_011",
      hook: "My meal prep plan fit inside one container",
      whatToShow:
        "Creator lines up empty meal prep containers on the counter, places one lonely container with actual food in the middle, then slowly removes the empty ones.",
      howToFilm:
        "Start with the meal prep containers like a big plan is happening. Reveal only one container has food, then clear the empty ones away in silence.",
      caption: "meal prep, singular.",
      anchor: "meal",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "overdramatic_diagnosis",
      originalBatchNumber: 11,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_012",
      hook: "Condiment shelf has seventeen mustards and no ketchup",
      whatToShow:
        "Fridge door open, condiments scanned, hand holds up random mustards",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Fridge door open, condiments scanned, hand holds up random mustards. Punch the final beat with one theatrical reaction.",
      caption: "mustards update: not great.",
      anchor: "mustards",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "tiny_documentary",
      originalBatchNumber: 12,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_013",
      hook: "Grocery list still has confidence I lost days ago",
      whatToShow:
        "Creator opens a staged grocery list that says “spinach, bananas, salmon,” then cuts to the counter: chips, coffee, and absolutely no bananas.",
      howToFilm:
        "Show the grocery list first so the optimism is clear. Cut to the real counter and let the missing bananas do the joke.",
      caption: "the grocery list believed in someone else.",
      anchor: "grocery",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_realization",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "before_after_self",
    safetyNote: "Use a staged grocery list, not private notes.",
      originalBatchNumber: 13,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_014",
      hook: "Toast landed butter-side down again",
      whatToShow:
        "Butter knife hovers, bread drops, slow-motion regret face",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Butter knife hovers, bread drops, slow-motion regret face. Talk-to-camera between beats; loose, a little frantic.",
      caption: "butter update: not great.",
      anchor: "butter",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "chaotic_confession",
      hookStyle: "object_betrayal",
    safetyNote: "Keep floor/counter clean if food is used.",
      originalBatchNumber: 14,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_015",
      hook: "I cooked rice and immediately ordered pizza",
      whatToShow:
        "Pot of rice on stove, phone showing pizza tracker, shrug to camera",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Pot of rice on stove, phone showing pizza tracker, shrug to camera. Keep your face flat the whole time; let the silence land.",
      caption: "rice? never met them.",
      anchor: "rice",
      comedyFamily: "self_betrayal",
      emotionalSpike: "avoidance_spike",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "before_after_self",
    safetyNote: "Hide delivery address/order details.",
      originalBatchNumber: 15,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_016",
      hook: "Cart total hit $92 and I still added gum",
      whatToShow:
        "Creator shows a staged cart total at $92, pauses, then drops a pack of gum onto the counter like that was somehow still necessary.",
      howToFilm:
        "Use a fake cart total or staged grocery counter. Show the $92 cart total first, then add the gum as the final bad decision.",
      caption: "cart total was already yelling.",
      anchor: "gum",
      comedyFamily: "self_betrayal",
      emotionalSpike: "instant_regret",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "realization",
      originalBatchNumber: 16,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_017",
      hook: "I opened my bank app like it owed me emotional support",
      whatToShow:
        "Phone angled away from camera, face goes from hopeful to blank, app gets closed with two fingers",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone angled away from camera, face goes from hopeful to blank, app gets closed with two fingers. Talk-to-camera between beats; loose, a little frantic.",
      caption: "phone situation, ongoing.",
      anchor: "phone",
      comedyFamily: "task_avoidance",
      emotionalSpike: "social_panic",
      setting: "couch",
      voiceCluster: "chaotic_confession",
      hookStyle: "accusation",
    safetyNote: "Use fake or blurred balance screen only.",
      originalBatchNumber: 17,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_018",
      hook: "A subscription from my confident self just charged me",
      whatToShow:
        "Creator gets a staged subscription charge notification, stares at the app icon, then tries to remember what version of themselves signed up for this.",
      howToFilm:
        "Frame the subscription notification safely. Hold on the stare at the app icon, then look off like you are searching your past for answers.",
      caption: "subscription from a person i no longer know.",
      anchor: "subscription",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "financial_dread",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
    safetyNote: "Hide real billing details.",
      originalBatchNumber: 18,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_019",
      hook: "Checkout line total made me put back the fancy cheese",
      whatToShow:
        "Creator recreates the checkout moment at home: staged receipt total on the table, fancy cheese in hand, then the cheese slowly goes back into the bag.",
      howToFilm:
        "Show the checkout total first, then the fancy cheese. The punchline is putting it back with the seriousness of a financial decision.",
      caption: "checkout humbled the cheese.",
      anchor: "checkout",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "before_after_self",
      originalBatchNumber: 19,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_020",
      hook: "My “treat yourself” budget lasts until Wednesday",
      whatToShow:
        "Creator opens a staged treat-yourself budget note, checks the date, then quietly puts one card back in the wallet like the week is over.",
      howToFilm:
        "Frame the wallet, card, and staged budget note. Show the “treat yourself” line, then return the card with quiet disappointment.",
      caption: "treat yourself had office hours.",
      anchor: "treat",
      comedyFamily: "self_betrayal",
      emotionalSpike: "instant_regret",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "confession",
    safetyNote: "Do not show real card numbers.",
      originalBatchNumber: 20,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_021",
      hook: "Parking lot receipt still in my cupholder two weeks later",
      whatToShow:
        "Car dashboard close-up, hand grabs crumpled receipt, tosses it in glovebox",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Car dashboard close-up, hand grabs crumpled receipt, tosses it in glovebox. Talk-to-camera between beats; loose, a little frantic.",
      caption: "the receipt knows.",
      anchor: "receipt",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_guilt",
      setting: "car",
      voiceCluster: "chaotic_confession",
      hookStyle: "domestic_crime_scene",
    safetyNote: "Do not film while driving; hide address/license/receipt details.",
      originalBatchNumber: 21,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_022",
      hook: "I budgeted for coffee and still bought the large",
      whatToShow:
        "Creator places a large coffee on the desk, sets the receipt beside it, taps the word “large,” then slowly slides the budget notebook out of frame.",
      howToFilm:
        "Frame the coffee, receipt, and budget notebook together. Tap the large size on the receipt, then quietly remove the budget notebook like it no longer applies.",
      caption: "budget saw the cup and gave up.",
      anchor: "coffee",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "confession",
    safetyNote: "Hide payment details.",
      originalBatchNumber: 22,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_023",
      hook: "Cart had three “essentials” and fourteen snacks",
      whatToShow:
        "Creator unloads a staged cart haul onto the kitchen table: three practical items on one side, fourteen snacks forming a much larger pile on the other.",
      howToFilm:
        "Frame the cart haul on the kitchen table. Build the essentials pile first, then build the snack pile until it clearly wins the shot.",
      caption: "cart priorities were exposed.",
      anchor: "cart",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_realization",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "realization",
      originalBatchNumber: 23,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_024",
      hook: "Payment failed and somehow I felt personally reviewed",
      whatToShow:
        "Phone shows generic payment error, hand slowly turns the phone face-down like ending a conversation",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone shows generic payment error, hand slowly turns the phone face-down like ending a conversation. Keep your face flat the whole time; let the silence land.",
      caption: "payment update: not great.",
      anchor: "payment",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
    safetyNote: "Use a fake/generic payment screen.",
      originalBatchNumber: 24,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_025",
      hook: "I canceled three subscriptions and kept the one I forgot",
      whatToShow:
        "Creator opens a staged canceled subscriptions list, checks off three canceled items, then notices one forgotten subscription and slowly closes the laptop.",
      howToFilm:
        "Show the canceled subscription list clearly. Let the forgotten one appear last, then close the laptop like the audit is over.",
      caption: "canceled three. feared one.",
      anchor: "canceled",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "calendar_task_betrayal",
    safetyNote: "Use fake/blurred subscription details.",
      originalBatchNumber: 25,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_026",
      hook: "Receipt says $6.99 and my brain says “worth it”",
      whatToShow:
        "Creator places a tiny unnecessary item next to the receipt, points at the $6.99 price, gives one guilty shrug, then moves the item closer like defending it.",
      howToFilm:
        "Shoot from above on the kitchen table. Show the tiny item, the staged receipt, and the shrug. The final beat is moving the item closer like it deserves protection.",
      caption: "financially small. emotionally loud.",
      anchor: "receipt",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_guilt",
      setting: "kitchen",
      voiceCluster: "chaotic_confession",
      hookStyle: "confession",
    safetyNote: "Hide store/payment details if needed.",
      originalBatchNumber: 26,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_027",
      hook: "My savings goal notification just got swiped away",
      whatToShow:
        "Phone lock screen savings alert, finger swipe dismisses it",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone lock screen savings alert, finger swipe dismisses it. Keep your face flat the whole time; let the silence land.",
      caption: "the savings knows.",
      anchor: "savings",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_guilt",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
    safetyNote: "Use fake savings notification.",
      originalBatchNumber: 27,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_028",
      hook: "Typing bubble stayed so long I started preparing emotionally",
      whatToShow:
        "Phone with typing dots, creator sits upright, fixes posture, then the dots vanish",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone with typing dots, creator sits upright, fixes posture, then the dots vanish. Talk-to-camera between beats; loose, a little frantic.",
      caption: "typing update: not great.",
      anchor: "typing",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "quiet_defeat",
      setting: "couch",
      voiceCluster: "chaotic_confession",
      hookStyle: "tiny_documentary",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 28,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_029",
      hook: "Read at 2:14am turned my ceiling into a witness",
      whatToShow:
        "Phone lights up in bed, creator lowers phone and stares straight at the ceiling like it has answers",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone lights up in bed, creator lowers phone and stares straight at the ceiling like it has answers. End on a held silent stare; let the realization sit.",
      caption: "ceiling math.",
      anchor: "ceiling",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "caught_off_guard",
      setting: "bedroom",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 29,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_030",
      hook: "The second text left my body before my pride could stop it",
      whatToShow:
        "Two message bubbles on phone, thumb hovers over delete even though it is already sent",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Two message bubbles on phone, thumb hovers over delete even though it is already sent. Punch the final beat with one theatrical reaction.",
      caption: "the message knows.",
      anchor: "message",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "instant_regret",
      setting: "couch",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "confession",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 30,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_031",
      hook: "Voice note deleted after thirty seconds of rambling",
      whatToShow:
        "Phone recording screen, finger hits delete after long voice note",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone recording screen, finger hits delete after long voice note. Keep your face flat the whole time; let the silence land.",
      caption: "voice update: not great.",
      anchor: "voice",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
    safetyNote: "Use staged voice note; do not reveal private messages.",
      originalBatchNumber: 31,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_032",
      hook: "They said “k” and I assembled a legal defense",
      whatToShow:
        "Phone shows a fake “k” text, creator types a huge legal defense paragraph, deletes the paragraph, then sends “cool” with visible spiritual damage.",
      howToFilm:
        "Start tight on the fake “k” text. Show the legal defense paragraph building, delete the paragraph, then send “cool” like you just represented yourself in court.",
      caption: "“k” required legal counsel.",
      anchor: "legal",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "social_panic",
      setting: "couch",
      voiceCluster: "chaotic_confession",
      hookStyle: "overdramatic_diagnosis",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 32,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_033",
      hook: "Four hours on delivered and I became a private investigator",
      whatToShow:
        "Phone shows delivered status, creator checks Wi-Fi, battery, app, then pretends not to care",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone shows delivered status, creator checks Wi-Fi, battery, app, then pretends not to care. Punch the final beat with one theatrical reaction.",
      caption: "delivered won.",
      anchor: "delivered",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "impatient_spiral",
      setting: "couch",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "tiny_documentary",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 33,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_034",
      hook: "Group chat went quiet and I assumed I was canceled",
      whatToShow:
        "Phone group chat silence, me staring then typing “haha” then deleting",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone group chat silence, me staring then typing “haha” then deleting. End on a held silent stare; let the realization sit.",
      caption: "group situation, ongoing.",
      anchor: "group",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "social_panic",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "confession",
    safetyNote: "Use fake group chat text.",
      originalBatchNumber: 34,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_035",
      hook: "I sent the screenshot to the wrong person and left my body",
      whatToShow:
        "Creator sees a staged screenshot send confirmation in the wrong chat, freezes with one hand over their mouth, then slowly turns the phone face-down like hiding evidence.",
      howToFilm:
        "Use a staged screenshot and fake chat. Hold on the screenshot send confirmation, freeze, then turn the phone face-down with dramatic calm.",
      caption: "wrong chat. correct panic.",
      anchor: "screenshot",
      comedyFamily: "self_betrayal",
      emotionalSpike: "panic",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "domestic_crime_scene",
    safetyNote: "Use fake chat names and staged screenshot.",
      originalBatchNumber: 35,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_036",
      hook: "“We should catch up” text I will never follow through on",
      whatToShow:
        "Phone message thread, me typing then closing app",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone message thread, me typing then closing app. Keep your face flat the whole time; let the silence land.",
      caption: "no comment on the message.",
      anchor: "message",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_guilt",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "realization",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 36,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_037",
      hook: "Dating app match replied and I left them on read",
      whatToShow:
        "Creator gets a staged dating app match reply notification, opens the match reply for half a second, panics, closes the phone, then sits perfectly still.",
      howToFilm:
        "Start on the staged dating app match reply notification. Open the match reply briefly, close the phone too fast, then sit frozen with the phone face-down beside you.",
      caption: "wanted attention. received consequences.",
      anchor: "match",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "quiet_guilt",
      setting: "couch",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "accusation",
    safetyNote: "Use fake/staged dating-app screen.",
      originalBatchNumber: 37,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_038",
      hook: "The typing dots disappeared and took my confidence with them",
      whatToShow:
        "Phone typing dots vanish, creator slowly lowers phone onto chest like receiving news",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone typing dots vanish, creator slowly lowers phone onto chest like receiving news. End on a held silent stare; let the realization sit.",
      caption: "the chest caught me.",
      anchor: "chest",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "quiet_defeat",
      setting: "bedroom",
      voiceCluster: "quiet_realization",
      hookStyle: "object_betrayal",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 38,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_039",
      hook: "I replied “lol” to a serious text",
      whatToShow:
        "Phone serious message, “lol” typed, send, immediate regret face",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone serious message, “lol” typed, send, immediate regret face. Talk-to-camera between beats; loose, a little frantic.",
      caption: "the serious knows.",
      anchor: "serious",
      comedyFamily: "texting_overthinking",
      emotionalSpike: "instant_regret",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "confession",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 39,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_040",
      hook: "Calendar says deep work while my thumb is on autopilot",
      whatToShow:
        "Laptop calendar block labeled “deep work,” phone scrolls beside it without the creator looking proud",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Laptop calendar block labeled “deep work, ” phone scrolls beside it without the creator looking proud. Keep your face flat the whole time; let the silence land.",
      caption: "the calendar knows.",
      anchor: "calendar",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_guilt",
      setting: "desk",
      voiceCluster: "dry_deadpan",
      hookStyle: "calendar_task_betrayal",
    safetyNote: "Avoid showing private calendar details.",
      originalBatchNumber: 40,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_041",
      hook: "This to-do item has survived three versions of me",
      whatToShow:
        "Creator points to the same to-do item copied across three planner pages or app lists, each in a different pen/color, still not completed.",
      howToFilm:
        "Show the first to-do item, then the second, then the third. End on the same task still waiting like it pays rent.",
      caption: "three versions of me. one task.",
      anchor: "to-do",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private tasks.",
      originalBatchNumber: 41,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_042",
      hook: "Pomodoro timer just rang and I ignored it",
      whatToShow:
        "Phone timer rings on the desk, creator reaches toward it like they might work, taps stop, then immediately keeps scrolling with the same hand.",
      howToFilm:
        "Frame the timer and phone clearly. Let the alarm ring, stop it with purpose, then use that same hand to keep scrolling. Keep your face completely blank.",
      caption: "timer had ambition. i did not.",
      anchor: "timer",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "avoidance_spike",
      setting: "desk",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "object_betrayal",
      originalBatchNumber: 42,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_043",
      hook: "Productivity app opened and my soul logged out",
      whatToShow:
        "Laptop productivity page loads, creator stares, closes tab, and immediately opens a blank browser tab",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Laptop productivity page loads, creator stares, closes tab, and immediately opens a blank browser tab. Talk-to-camera between beats; loose, a little frantic.",
      caption: "productivity situation, ongoing.",
      anchor: "productivity",
      comedyFamily: "task_avoidance",
      emotionalSpike: "social_panic",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "object_betrayal",
    safetyNote: "Avoid showing private workspace data.",
      originalBatchNumber: 43,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_044",
      hook: "Work-from-home outfit is still pajamas at 3pm",
      whatToShow:
        "Creator shows a work-from-home mirror check: nice top or hoodie above, pajama pants below, clock visible at 3pm.",
      howToFilm:
        "Use the mirror as the reveal. Start with the work-from-home outfit from the waist up, then tilt down to the pajamas and show the 3pm clock.",
      caption: "work from home, barely from outfit.",
      anchor: "work",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "bathroom",
      voiceCluster: "dry_deadpan",
      hookStyle: "before_after_self",
      originalBatchNumber: 44,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_045",
      hook: "Slack “away” status I never turned off",
      whatToShow:
        "Laptop Slack status still “away,” me actually working",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Laptop Slack status still “away, ” me actually working. End on a held silent stare; let the realization sit.",
      caption: "slack? never met them.",
      anchor: "slack",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "false_productivity",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "confession",
    safetyNote: "Use a staged or blurred workspace screen.",
      originalBatchNumber: 45,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_046",
      hook: "My focus playlist is just lo-fi and snacks",
      whatToShow:
        "Creator opens a focus playlist on the laptop, nods like work is starting, then immediately grabs chips and never touches the keyboard.",
      howToFilm:
        "Frame the laptop playlist and keyboard. Start the focus playlist, then let the snack grab steal the entire scene.",
      caption: "focus playlist. snack behavior.",
      anchor: "focus",
      comedyFamily: "self_betrayal",
      emotionalSpike: "false_productivity",
      setting: "desk",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private account details.",
      originalBatchNumber: 46,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_047",
      hook: "I accepted the calendar invite before my personality loaded",
      whatToShow:
        "Phone calendar invite accepted, creator freezes, then checks the time like it changed",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone calendar invite accepted, creator freezes, then checks the time like it changed. Talk-to-camera between beats; loose, a little frantic.",
      caption: "no comment on the calendar.",
      anchor: "calendar",
      comedyFamily: "task_avoidance",
      emotionalSpike: "instant_regret",
      setting: "couch",
      voiceCluster: "chaotic_confession",
      hookStyle: "realization",
    safetyNote: "Hide private invite details.",
      originalBatchNumber: 47,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_048",
      hook: "I wrote “email boss” on my list and it’s still there",
      whatToShow:
        "Notebook entry “email boss,” crossed nothing out",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Notebook entry “email boss, ” crossed nothing out. Keep your face flat the whole time; let the silence land.",
      caption: "email update: not great.",
      anchor: "email",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "dry_deadpan",
      hookStyle: "calendar_task_betrayal",
    safetyNote: "Use a staged task list.",
      originalBatchNumber: 48,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_049",
      hook: "Standing desk became a very expensive shelf",
      whatToShow:
        "Standing desk covered with mugs, mail, headphones; creator works from chair beside it",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Standing desk covered with mugs, mail, headphones; creator works from chair beside it. End on a held silent stare; let the realization sit.",
      caption: "standing update: not great.",
      anchor: "standing",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "before_after_self",
      originalBatchNumber: 49,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_050",
      hook: "My daily planner is now a snack log",
      whatToShow:
        "Creator opens planner to a crossed-out task list, writes “chips,” “coffee,” and “more chips” underneath, then checks one off with real pride.",
      howToFilm:
        "Shoot overhead at the planner. Show the task list first, then add the snack entries like they are official responsibilities. End by checking one off.",
      caption: "finally, a planner that reflects my values.",
      anchor: "planner",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "confession",
    safetyNote: "Avoid showing private planner details.",
      originalBatchNumber: 50,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_051",
      hook: "“Urgent” flag still on email from last month",
      whatToShow:
        "Email inbox with old urgent flag, me sipping coffee",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Email inbox with old urgent flag, me sipping coffee. Keep your face flat the whole time; let the silence land.",
      caption: "urgent update: not great.",
      anchor: "urgent",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "dry_deadpan",
      hookStyle: "tiny_documentary",
    safetyNote: "Use a staged/blurred inbox.",
      originalBatchNumber: 51,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_052",
      hook: "I blocked my own calendar for “me time” and filled it",
      whatToShow:
        "Calendar block labeled “me time,” then new meeting added",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Calendar block labeled “me time, ” then new meeting added. Talk-to-camera between beats; loose, a little frantic.",
      caption: "time update: not great.",
      anchor: "time",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "calendar_task_betrayal",
    safetyNote: "Use fake or blurred calendar details.",
      originalBatchNumber: 52,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_053",
      hook: "My task streak broke and I felt free too quickly",
      whatToShow:
        "App streak reset screen, creator looks disappointed for one second, then visibly relieved",
      howToFilm:
        "Phone on a tripod, one locked-off shot. App streak reset screen, creator looks disappointed for one second, then visibly relieved. End on a held silent stare; let the realization sit.",
      caption: "streak update: not great.",
      anchor: "streak",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "overdramatic_diagnosis",
    safetyNote: "Use fake/generic task app screen.",
      originalBatchNumber: 53,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_054",
      hook: "Roommate left one dish and I’m writing the constitution",
      whatToShow:
        "Sink with single plate, me dramatically gesturing with dish soap",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Sink with single plate, me dramatically gesturing with dish soap. Punch the final beat with one theatrical reaction.",
      caption: "single won.",
      anchor: "single",
      comedyFamily: "tiny_public_private_awkwardness",
      emotionalSpike: "polite_rage",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "accusation",
    safetyNote: "Avoid showing identifying roommate details.",
      originalBatchNumber: 54,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_055",
      hook: "Laundry basket has been “almost done” for six days",
      whatToShow:
        "Laundry basket in hallway, hand touches it then walks away",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Laundry basket in hallway, hand touches it then walks away. Keep your face flat the whole time; let the silence land.",
      caption: "the laundry knows.",
      anchor: "laundry",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_guilt",
      setting: "hallway",
      voiceCluster: "dry_deadpan",
      hookStyle: "domestic_crime_scene",
      originalBatchNumber: 55,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_056",
      hook: "Fridge note from roommate is now a passive-aggressive novel",
      whatToShow:
        "Fridge sticky note with long handwriting, me reading aloud silently",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Fridge sticky note with long handwriting, me reading aloud silently. End on a held silent stare; let the realization sit.",
      caption: "fridge won.",
      anchor: "fridge",
      comedyFamily: "tiny_public_private_awkwardness",
      emotionalSpike: "polite_rage",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
    safetyNote: "Use a staged note; do not expose real roommate messages.",
      originalBatchNumber: 56,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_057",
      hook: "Shared bathroom counter has my stuff and zero of theirs",
      whatToShow:
        "Creator pans across a bathroom counter completely covered with their products, finds one tiny empty corner, places another bottle there, then shrugs.",
      howToFilm:
        "Use a slow bathroom counter pan. Show your products covering the counter, place one more bottle in the only open corner, then end on the guilty shrug.",
      caption: "shared in theory.",
      anchor: "bathroom",
      comedyFamily: "tiny_public_private_awkwardness",
      emotionalSpike: "self_critique",
      setting: "bathroom",
      voiceCluster: "chaotic_confession",
      hookStyle: "realization",
      originalBatchNumber: 57,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_058",
      hook: "I folded one towel and called it “laundry day”",
      whatToShow:
        "Creator folds one towel perfectly on the bed, looks proud, then camera tilts to the untouched laundry pile beside it.",
      howToFilm:
        "Open on the single towel fold like a serious accomplishment. Hold the proud pause, then tilt to the giant pile still waiting.",
      caption: "one towel carried the department.",
      anchor: "towel",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "false_productivity",
      setting: "bedroom",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "confession",
      originalBatchNumber: 58,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_059",
      hook: "Trash can full and I’m still adding one more thing",
      whatToShow:
        "Creator presses one last item into an overflowing trash can, waits to see if it stays, then slowly backs away when it balances.",
      howToFilm:
        "Frame the overflowing trash can low and close. Push the final item in, hold the suspense, then back away like you just defused something.",
      caption: "engineering degree pending.",
      anchor: "trash",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "avoidance_spike",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
    safetyNote: "Keep shot sanitary; avoid showing personal mail.",
      originalBatchNumber: 59,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_060",
      hook: "My side of the couch has permanent snack crumbs",
      whatToShow:
        "Couch cushion close-up with crumbs, hand brushes half-heartedly",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Couch cushion close-up with crumbs, hand brushes half-heartedly. End on a held silent stare; let the realization sit.",
      caption: "couch update: not great.",
      anchor: "couch",
      comedyFamily: "self_betrayal",
      emotionalSpike: "quiet_defeat",
      setting: "couch",
      voiceCluster: "quiet_realization",
      hookStyle: "confession",
      originalBatchNumber: 60,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_061",
      hook: "Roommate schedule says they’re home and they’re not",
      whatToShow:
        "Creator checks a staged roommate schedule on the phone that says “home,” then pans across an obviously empty living room.",
      howToFilm:
        "Show the roommate schedule first, then slowly pan the empty room. End on the confused look back at the schedule.",
      caption: "roommate schedule entered fiction.",
      anchor: "roommate",
      comedyFamily: "tiny_public_private_awkwardness",
      emotionalSpike: "confused_pause",
      setting: "living_room",
      voiceCluster: "chaotic_confession",
      hookStyle: "calendar_task_betrayal",
    safetyNote: "Use fake schedule details; avoid identifying roommate data.",
      originalBatchNumber: 61,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_062",
      hook: "I used their mug and immediately washed it",
      whatToShow:
        "Creator takes a mug from the cabinet, uses it for one sip, then washes it with suspicious intensity and returns it perfectly.",
      howToFilm:
        "Show the mug coming out of the cabinet, take one tiny sip, then wash the mug with suspicious intensity and return it perfectly.",
      caption: "borrowed. panicked. sanitized.",
      anchor: "mug",
      comedyFamily: "tiny_public_private_awkwardness",
      emotionalSpike: "social_panic",
      setting: "kitchen",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "confession",
      originalBatchNumber: 62,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_063",
      hook: "Vacuum line still visible from last month",
      whatToShow:
        "Carpet with faint vacuum line, foot steps on it",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Carpet with faint vacuum line, foot steps on it. Keep your face flat the whole time; let the silence land.",
      caption: "vacuum update: not great.",
      anchor: "vacuum",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "hallway",
      voiceCluster: "dry_deadpan",
      hookStyle: "tiny_documentary",
      originalBatchNumber: 63,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_064",
      hook: "Shared grocery list has only my snacks now",
      whatToShow:
        "Creator opens a staged fridge grocery list, crosses out vegetables, adds three snack items, then steps back like the list has evolved.",
      howToFilm:
        "Frame the fridge list. Cross out one healthy item, add the snack items underneath, then hold on the final list like it speaks for itself.",
      caption: "democracy failed at snacks.",
      anchor: "grocery",
      comedyFamily: "tiny_public_private_awkwardness",
      emotionalSpike: "quiet_guilt",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "before_after_self",
    safetyNote: "Use staged list.",
      originalBatchNumber: 64,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_065",
      hook: "I took the last paper towel and didn’t replace it",
      whatToShow:
        "Creator pulls the final sheet from the paper towel roll, sees the empty cardboard tube, freezes, then quietly turns it so the empty side faces away.",
      howToFilm:
        "Start close on the last sheet. Pull it off, reveal the empty roll, then rotate the roll like hiding a crime scene.",
      caption: "not proud. still leaving.",
      anchor: "paper",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_guilt",
      setting: "kitchen",
      voiceCluster: "chaotic_confession",
      hookStyle: "domestic_crime_scene",
      originalBatchNumber: 65,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_066",
      hook: "Drafts folder is where my confidence goes to cool off",
      whatToShow:
        "Phone drafts scroll, thumb opens one draft, watches it for half a second, exits without posting",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone drafts scroll, thumb opens one draft, watches it for half a second, exits without posting. Keep your face flat the whole time; let the silence land.",
      caption: "me vs the phone: phone won.",
      anchor: "phone",
      comedyFamily: "posting_anxiety",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "dry_deadpan",
      hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private drafts unless staged.",
      originalBatchNumber: 66,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_067",
      hook: "Algorithm showed me my old post like it found evidence",
      whatToShow:
        "Phone feed surfaces an old post, creator immediately lowers brightness and looks away",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone feed surfaces an old post, creator immediately lowers brightness and looks away. Punch the final beat with one theatrical reaction.",
      caption: "the post caught me.",
      anchor: "post",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "private_embarrassment",
      setting: "couch",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "accusation",
    safetyNote: "Use own/staged content only.",
      originalBatchNumber: 67,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_068",
      hook: "I filmed a 12-second idea for 45 minutes",
      whatToShow:
        "Creator opens phone camera, taps through multiple filmed takes, then shows an exhausted face beside the final 12-second clip.",
      howToFilm:
        "Show the camera roll or fake take list. Let the number of takes feel excessive, then end on the tiny final clip and your defeated face.",
      caption: "filmed for 45. posted for 12.",
      anchor: "filmed",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "confession",
      originalBatchNumber: 68,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_069",
      hook: "Caption deleted after 200 likes",
      whatToShow:
        "Post with likes, caption edited to blank",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Post with likes, caption edited to blank. End on a held silent stare; let the realization sit.",
      caption: "post situation, ongoing.",
      anchor: "post",
      comedyFamily: "posting_anxiety",
      emotionalSpike: "self_doubt_spike",
      setting: "phone",
      voiceCluster: "quiet_realization",
      hookStyle: "object_betrayal",
    safetyNote: "Use staged/blurred post details.",
      originalBatchNumber: 69,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_070",
      hook: "I found the trend right after it turned into homework",
      whatToShow:
        "Phone trend page, creator opens camera, pauses, closes it because the sound already feels tired",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone trend page, creator opens camera, pauses, closes it because the sound already feels tired. Keep your face flat the whole time; let the silence land.",
      caption: "trend update: not great.",
      anchor: "trend",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "quiet_defeat",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "realization",
      originalBatchNumber: 70,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_071",
      hook: "This saved video is retired before it ever worked",
      whatToShow:
        "Phone saved folder, creator taps a video thumbnail, shakes head, moves it to another folder",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone saved folder, creator taps a video thumbnail, shakes head, moves it to another folder. End on a held silent stare; let the realization sit.",
      caption: "saved update: not great.",
      anchor: "saved",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "quiet_realization",
      hookStyle: "domestic_crime_scene",
    safetyNote: "Use staged/private-safe thumbnails.",
      originalBatchNumber: 71,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_072",
      hook: "Analytics gave me hope and I punished the app for it",
      whatToShow:
        "Analytics screen flashes a positive metric, creator smiles for half a second, then force-closes the app",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Analytics screen flashes a positive metric, creator smiles for half a second, then force-closes the app. Punch the final beat with one theatrical reaction.",
      caption: "analytics? never met them.",
      anchor: "analytics",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "avoidance_spike",
      setting: "desk",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "object_betrayal",
    safetyNote: "Use fake/blurred analytics.",
      originalBatchNumber: 72,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_073",
      hook: "Story reply I overthought for an hour",
      whatToShow:
        "Story reply bubble typing, deleted, retyped, deleted",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Story reply bubble typing, deleted, retyped, deleted. Talk-to-camera between beats; loose, a little frantic.",
      caption: "story won.",
      anchor: "story",
      comedyFamily: "posting_anxiety",
      emotionalSpike: "impatient_spiral",
      setting: "couch",
      voiceCluster: "chaotic_confession",
      hookStyle: "tiny_documentary",
    safetyNote: "Use fake/staged story reply.",
      originalBatchNumber: 73,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_074",
      hook: "I posted at 9:07pm like it was prime time",
      whatToShow:
        "Creator shows a staged post timestamped 9:07pm, refreshes the post for likes, then checks the time again like the algorithm missed an appointment.",
      howToFilm:
        "Use a fake post screen. Show the staged post timestamp, refresh the post once or twice, then look at the clock like 9:07pm was supposed to do something.",
      caption: "prime time according to me.",
      anchor: "post",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "impatient_spiral",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "confession",
    safetyNote: "Use staged post details.",
      originalBatchNumber: 74,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_075",
      hook: "My drafts are now organized by emotional damage",
      whatToShow:
        "Creator opens a staged drafts folder with labels like “maybe,” “absolutely not,” and “why did I film this,” then silently moves one draft into the worst folder.",
      howToFilm:
        "Use staged folder names. Scroll slowly, move one draft, and let the folder labels be the joke.",
      caption: "drafts folder has departments now.",
      anchor: "drafts",
      comedyFamily: "posting_anxiety",
      emotionalSpike: "quiet_realization",
      setting: "phone",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
    safetyNote: "Use staged draft names only.",
      originalBatchNumber: 75,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_076",
      hook: "Algorithm recommended a memory I did not authorize",
      whatToShow:
        "Creator sees a staged algorithm memory recommendation on the phone, freezes, then scrolls away so fast the phone almost slips.",
      howToFilm:
        "Show a blurred or fake memory recommendation. The reaction is the point: freeze first, then panic-scroll away.",
      caption: "algorithm, delete that thought.",
      anchor: "algorithm",
      comedyFamily: "posting_anxiety",
      emotionalSpike: "caught_off_guard",
      setting: "couch",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "accusation",
    safetyNote: "Do not show real people, usernames, exes, or private posts.",
      originalBatchNumber: 76,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_077",
      hook: "I refreshed the feed and the feed refreshed my patience",
      whatToShow:
        "Creator pulls to refresh a staged feed, the exact same post returns, and the phone gets set down like it lost privileges.",
      howToFilm:
        "Frame the staged feed and the pull-to-refresh gesture. Show the same post returning, then set the phone down with parental disappointment.",
      caption: "refreshed and learned nothing.",
      anchor: "refresh",
      comedyFamily: "creator_anxiety",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "object_betrayal",
    safetyNote: "Use staged or blurred feed.",
      originalBatchNumber: 77,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_078",
      hook: "Snooze button turned morning into a rumor",
      whatToShow:
        "Alarm at 7:00, quick cuts of snooze taps, final clock reads 11:48",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Alarm at 7:00, quick cuts of snooze taps, final clock reads 11:48. Keep your face flat the whole time; let the silence land.",
      caption: "alarm math.",
      anchor: "alarm",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "time_loss",
      setting: "bedroom",
      voiceCluster: "dry_deadpan",
      hookStyle: "calendar_task_betrayal",
      originalBatchNumber: 78,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_079",
      hook: "Wellness journal entry is just “coffee”",
      whatToShow:
        "Creator opens a staged wellness journal, writes “coffee” as the full entry, pauses, then underlines it like that explains enough.",
      howToFilm:
        "Shoot overhead on the wellness journal. Write “coffee,” pause at the mostly empty page, then underline the coffee entry with too much confidence.",
      caption: "healing, allegedly.",
      anchor: "journal",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "confession",
    safetyNote: "Use staged journal page.",
      originalBatchNumber: 79,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_080",
      hook: "Nighttime skincare routine reduced to face wash",
      whatToShow:
        "Bathroom sink, single face wash pump, done",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Bathroom sink, single face wash pump, done. Punch the final beat with one theatrical reaction.",
      caption: "face update: not great.",
      anchor: "face",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "bathroom",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "before_after_self",
      originalBatchNumber: 80,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_081",
      hook: "5am me made promises 5:12am me never respected",
      whatToShow:
        "Creator’s alarm rings at 5am, they sit up like a new person, then at 5:12am they are fully back under the blanket.",
      howToFilm:
        "Show the 5am alarm, the heroic sit-up, then the 5:12am collapse back under the blanket. Make the two times feel like enemies.",
      caption: "5am me was unsupervised.",
      anchor: "5am",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "bedroom",
      voiceCluster: "chaotic_confession",
      hookStyle: "before_after_self",
      originalBatchNumber: 81,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_082",
      hook: "Meditation app streak ended because I checked my phone",
      whatToShow:
        "Meditation timer open, phone notification distracts, streak broken",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Meditation timer open, phone notification distracts, streak broken. Keep your face flat the whole time; let the silence land.",
      caption: "meditation update: not great.",
      anchor: "meditation",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
    safetyNote: "Use staged app/notification.",
      originalBatchNumber: 82,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_083",
      hook: "Wind-down routine became a wrist workout",
      whatToShow:
        "Creator starts a wind-down routine in bed with book and eye mask nearby, then thumb-scrolls on the phone until the book is clearly ignored.",
      howToFilm:
        "Frame the wind-down props first. Then let the phone take over the shot while the thumb does all the “routine.”",
      caption: "wind-down routine, thumb edition.",
      anchor: "wind",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_guilt",
      setting: "bedroom",
      voiceCluster: "quiet_realization",
      hookStyle: "tiny_documentary",
      originalBatchNumber: 83,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_084",
      hook: "I stretched once and called it yoga",
      whatToShow:
        "Creator does one tiny stretch on the living room floor, immediately stands up satisfied, and rolls the mat away like a class ended.",
      howToFilm:
        "Use one safe tiny stretch on the living room floor. Stand up immediately, roll the mat away, and act like the class is over.",
      caption: "yoga was brief.",
      anchor: "stretch",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "false_productivity",
      setting: "living_room",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "fake_tutorial",
    safetyNote: "Avoid unsafe stretching positions.",
      originalBatchNumber: 84,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_085",
      hook: "Sleep tracker says I slept great and I feel dead",
      whatToShow:
        "Phone sleep data “excellent,” me with tired face",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone sleep data “excellent, ” me with tired face. Talk-to-camera between beats; loose, a little frantic.",
      caption: "the sleep caught me.",
      anchor: "sleep",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "exposed_lie",
      setting: "bedroom",
      voiceCluster: "chaotic_confession",
      hookStyle: "accusation",
    safetyNote: "Use fake/blurred health data; avoid medical claims.",
      originalBatchNumber: 85,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_086",
      hook: "Morning coffee is now my only productivity",
      whatToShow:
        "Creator holds a coffee mug like a trophy in front of an untouched desk, sets it down, then does absolutely nothing else.",
      howToFilm:
        "Frame the mug and the empty desk together. Lift the mug like a completed task, set it down, and let the untouched workspace sit in frame.",
      caption: "task one: coffee. task two: unclear.",
      anchor: "coffee",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "confession",
      originalBatchNumber: 86,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_087",
      hook: "Bedtime reminder arrived like a suggestion box",
      whatToShow:
        "Phone bedtime reminder pops up, creator taps “remind me later” while already under blankets",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Phone bedtime reminder pops up, creator taps “remind me later” while already under blankets. End on a held silent stare; let the realization sit.",
      caption: "bedtime? never met them.",
      anchor: "bedtime",
      comedyFamily: "self_improvement_attempt",
      emotionalSpike: "avoidance_spike",
      setting: "bedroom",
      voiceCluster: "quiet_realization",
      hookStyle: "calendar_task_betrayal",
      originalBatchNumber: 87,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_088",
      hook: "Autocorrect changed my tone and left me with the consequences",
      whatToShow:
        "Phone autocorrects a fake message into something colder than intended, creator notices after sending, freezes, then slowly puts the phone down.",
      howToFilm:
        "Use a fake message. Show autocorrect changing the word, send the message, then freeze when the colder tone lands.",
      caption: "autocorrect chose violence politely.",
      anchor: "autocorrect",
      comedyFamily: "parasocial_object",
      emotionalSpike: "polite_rage",
      setting: "couch",
      voiceCluster: "chaotic_confession",
      hookStyle: "object_betrayal",
    safetyNote: "Use fake chat text.",
      originalBatchNumber: 88,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_089",
      hook: "Charger waited until 3% to reveal its true character",
      whatToShow:
        "Creator sees phone at 3%, plugs in the charger, battery icon does nothing, and the creator slowly turns to stare at the cord.",
      howToFilm:
        "Start on the 3% battery. Plug in the charger, wait for nothing to happen, then give the cord the full betrayal stare.",
      caption: "charger picked a moment.",
      anchor: "charger",
      comedyFamily: "parasocial_object",
      emotionalSpike: "panic",
      setting: "desk",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "accusation",
      originalBatchNumber: 89,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_090",
      hook: "Earbuds fell in the exact spot I can’t reach",
      whatToShow:
        "Creator drops an earbud between couch cushions, reaches in from three angles, then stares into the gap like it became a different address.",
      howToFilm:
        "Show the earbud drop between the couch cushions. Try reaching from three angles, fail, then hold on the impossible couch gap.",
      caption: "earbuds found another dimension.",
      anchor: "earbud",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "couch",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
      originalBatchNumber: 90,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_091",
      hook: "Remote died during the one scene I was emotionally available for",
      whatToShow:
        "TV paused, remote click fails, creator stares at remote like it betrayed the plot",
      howToFilm:
        "Phone on a tripod, one locked-off shot. TV paused, remote click fails, creator stares at remote like it betrayed the plot. End on a held silent stare; let the realization sit.",
      caption: "remote won.",
      anchor: "remote",
      comedyFamily: "parasocial_object",
      emotionalSpike: "polite_rage",
      setting: "couch",
      voiceCluster: "quiet_realization",
      hookStyle: "accusation",
    safetyNote: "Do not show copyrighted TV content clearly.",
      originalBatchNumber: 91,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_092",
      hook: "Mouse stopped working and I accused the whole laptop",
      whatToShow:
        "Mouse click fails, creator taps keyboard, shakes mouse, then notices mouse power switch",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Mouse click fails, creator taps keyboard, shakes mouse, then notices mouse power switch. Talk-to-camera between beats; loose, a little frantic.",
      caption: "mouse won.",
      anchor: "mouse",
      comedyFamily: "parasocial_object",
      emotionalSpike: "polite_rage",
      setting: "desk",
      voiceCluster: "chaotic_confession",
      hookStyle: "realization",
      originalBatchNumber: 92,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_093",
      hook: "Laptop fan started screaming at 2% battery",
      whatToShow:
        "Creator hears the laptop fan ramp up, sees the staged 2% battery warning, then looks between the laptop and charger like choosing who to save.",
      howToFilm:
        "Frame the laptop and charger. Add fan sound if needed, show the 2% warning, then cut to the panicked look between laptop and cord.",
      caption: "the laptop chose drama.",
      anchor: "laptop",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "performance_panic",
      setting: "desk",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing private desktop/app content.",
      originalBatchNumber: 93,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_094",
      hook: "Headphones tangled themselves overnight",
      whatToShow:
        "Creator pulls headphones from a bag, reveals a huge knot, shakes the bag once like checking for an explanation, then gives up.",
      howToFilm:
        "Start with the headphones being pulled from the bag. Reveal the giant knot slowly, shake the bag once for answers, then hold the defeated stare.",
      caption: "they had all night to plan this.",
      anchor: "headphones",
      comedyFamily: "parasocial_object",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
      originalBatchNumber: 94,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_095",
      hook: "Water bottle lid popped off in my bag",
      whatToShow:
        "Creator opens a bag, spots a staged water spill, lifts the loose bottle lid, then slowly closes the bag again like they need a minute.",
      howToFilm:
        "Use a safe staged spill. Open the bag, show the loose lid and wet area, then close the bag with quiet defeat.",
      caption: "hydration betrayed the team.",
      anchor: "bottle",
      comedyFamily: "parasocial_object",
      emotionalSpike: "quiet_defeat",
      setting: "hallway",
      voiceCluster: "quiet_realization",
      hookStyle: "domestic_crime_scene",
    safetyNote: "Avoid showing personal documents inside bag.",
      originalBatchNumber: 95,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_096",
      hook: "I bought a plant and it’s already yellow",
      whatToShow:
        "Windowsill plant turning yellow, me watering anyway",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Windowsill plant turning yellow, me watering anyway. End on a held silent stare; let the realization sit.",
      caption: "the plant knows.",
      anchor: "plant",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_guilt",
      setting: "home",
      voiceCluster: "quiet_realization",
      hookStyle: "confession",
      originalBatchNumber: 96,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_097",
      hook: "My keys were in my hand the whole search",
      whatToShow:
        "Hand holding keys while other hand searches pockets",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Hand holding keys while other hand searches pockets. Talk-to-camera between beats; loose, a little frantic.",
      caption: "keys math.",
      anchor: "keys",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_realization",
      setting: "hallway",
      voiceCluster: "chaotic_confession",
      hookStyle: "realization",
      originalBatchNumber: 97,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_098",
      hook: "Reminder popped up and watched me choose chaos",
      whatToShow:
        "Phone reminder appears, creator reads it, nods like they understand, dismisses it, then immediately continues doing the opposite task.",
      howToFilm:
        "Frame the phone reminder with generic text. Read the reminder, nod seriously, dismiss it, then continue doing the opposite task without changing expression.",
      caption: "the reminder witnessed everything.",
      anchor: "reminder",
      comedyFamily: "task_avoidance",
      emotionalSpike: "quiet_defeat",
      setting: "desk",
      voiceCluster: "dry_deadpan",
      hookStyle: "object_betrayal",
    safetyNote: "Use generic reminder text.",
      originalBatchNumber: 98,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_099",
      hook: "Laundry returned every sock except the one with accountability",
      whatToShow:
        "Laundry basket dump, creator holds two obviously wrong socks together and accepts it",
      howToFilm:
        "Phone on a tripod, one locked-off shot. Laundry basket dump, creator holds two obviously wrong socks together and accepts it. Punch the final beat with one theatrical reaction.",
      caption: "laundry math.",
      anchor: "laundry",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "confused_pause",
      setting: "home",
      voiceCluster: "overdramatic_reframe",
      hookStyle: "tiny_documentary",
      originalBatchNumber: 99,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
  {
      id: "w2_next_100",
      hook: "I cleaned one surface and immediately gave it a sequel",
      whatToShow:
        "Creator shows a cleaned counter, places one item down, then another, then another, until the cleaned surface has a full sequel of clutter.",
      howToFilm:
        "Open on the clean surface. Add clutter one item at a time like the mess is rebuilding itself. End on the counter fully back in chaos.",
      caption: "cleaned surface, part two.",
      anchor: "cleaned",
      comedyFamily: "tiny_humiliation",
      emotionalSpike: "quiet_defeat",
      setting: "kitchen",
      voiceCluster: "quiet_realization",
      hookStyle: "before_after_self",
      originalBatchNumber: 100,
      reviewedBy: PENDING_EDITORIAL_REVIEW,
    },
    ]);

  /**
   * Derive the human-readable source-batch label from a W2-L approved
   * id. Cohorts beyond W2-BATCH-NEXT may be added in future imports;
   * the helper centralizes the id-prefix → label mapping so consumers
   * never hard-code the prefix string.
   */
  export function getWesternEntrySourceBatch(id: string): string | null {
    if (typeof id !== "string") return null;
    // Order matters: the W2-N prefix `w2_next2_` shares the prefix
    // `w2_next` with the W2-L prefix `w2_next_`, so check the longer
    // (more specific) prefix first.
    if (id.startsWith("w2_next2_")) return "W2-BATCH-NEXT-2";
    if (id.startsWith("w2_next_")) return "W2-BATCH-NEXT";
    return null;
  }
  