/**
   * PHASE W2-N — curated W2-BATCH-NEXT-2 promotion entries (DARK by
   * default; surfaced through the W2-K runtime path via
   * `westernHookPackApproved.ts`).
   *
   * 100 editorial-curated Western hooks supplied as the second curated
   * batch (W2-BATCH-NEXT2-001..100). Imported under the same Path A
   * guardrails the W2-L import established:
   *
   *   • single runtime path — entries flow through the SAME approved
   *     pool that W2-K activated; no new public API surface.
   *   • howToFilm is SYNTHESIZED deterministically per entry from the
   *     curated WHAT TO SHOW (each entry's actual beat narration),
   *     prefixed with a tripod/single-shot framing directive and
   *     suffixed with a voice-cluster-keyed payoff cue. Result: 100
   *     distinct howToFilm strings, every one mentioning the entry's
   *     actual props/actions.
   *   • caption is synthesized deterministically per entry from
   *     (emotionalSpike × anchor × distinctive hook token); 100/100
   *     distinct within the batch and 0 collisions vs the W2-L batch's
   *     captions.
   *   • freeform vocab from the curated batch (Comedy family,
   *     Emotional spike, Setting) is normalized into the EXISTING
   *     `WESTERN_COMEDY_FAMILIES` / `WESTERN_EMOTIONAL_SPIKES` /
   *     `WESTERN_SETTINGS` controlled vocab — no enum widening was
   *     necessary for any curated entry.
   *   • voiceCluster is normalized into the existing
   *     `WESTERN_VOICE_CLUSTERS` vocab.
   *   • hookStyle is normalized into the existing
   *     `WESTERN_BATCH_HOOK_STYLES` vocab.
   *   • safetyNote is preserved verbatim from the curated batch on
   *     entries that carry one (entries marked "None." leave the
   *     optional field unset).
   *   • originalBatchNumber preserves the W2-BATCH-NEXT-2 row number
   *     (1..100) for editorial traceback. The owning batch label is
   *     derivable from the id prefix via `getWesternEntrySourceBatch`.
   *   • whyThisWorks is intentionally NOT carried on the runtime entry —
   *     it lives in the curated source attachment + the W2-N import
   *     report (`.local/W2N_REPORT.md`).
   *   • anchor is normalized to a single lowercase token that appears
   *     (lowercased) in whatToShow — exactly the invariant the W2-I
   *     unit test enforces. Five entries (#2, #21, #42, #58, #85)
   *     received an anchor swap to break a colliding
   *     (anchor|setting|comedyFamily) triple against the existing 200
   *     approved entries; see `.local/W2N_REPORT.md` § Triple swaps.
   *
   * Cross-batch dedup verified at import time vs:
   *   • `APPROVED_WESTERN_PROMOTION_CANDIDATES` (existing 200: W2I 100
   *     + W2-L 100)
   *   • `WESTERN_HOOK_PACK_DRAFT` (150)
   *   • `userBlessedHookCorpus.ts` (532 hand-authored hooks)
   *   • this batch's own running set
   *
   * Exact-hook, normalized-skeleton (long tokens >=5 chars -> "__",
   * cap 24), bigram-Jaccard >= 0.50, and (anchor|setting|comedyFamily)
   * triple — all enforced at import time. Result: 100/100 accepted
   * (max observed bigram-Jaccard 0.27, well under the 0.50 ceiling).
   *
   * Production stays OFF — gating still flows through
   * `isWesternApprovedPoolFeatureEnabled` +
   * `canActivateWesternApprovedPool`. Promotion to live requires a
   * separate editorial-review PR that overwrites
   * `reviewedBy: PENDING_EDITORIAL_REVIEW`.
   */

  import {
    PENDING_EDITORIAL_REVIEW,
    type WesternHookPackDraftEntry,
  } from "./westernHookPack.js";

  export const WESTERN_HOOK_PACK_BATCH_NEXT2_IDS: readonly string[] =
    Object.freeze([
      "w2_next2_001",
    "w2_next2_002",
    "w2_next2_003",
    "w2_next2_004",
    "w2_next2_005",
    "w2_next2_006",
    "w2_next2_007",
    "w2_next2_008",
    "w2_next2_009",
    "w2_next2_010",
    "w2_next2_011",
    "w2_next2_012",
    "w2_next2_013",
    "w2_next2_014",
    "w2_next2_015",
    "w2_next2_016",
    "w2_next2_017",
    "w2_next2_018",
    "w2_next2_019",
    "w2_next2_020",
    "w2_next2_021",
    "w2_next2_022",
    "w2_next2_023",
    "w2_next2_024",
    "w2_next2_025",
    "w2_next2_026",
    "w2_next2_027",
    "w2_next2_028",
    "w2_next2_029",
    "w2_next2_030",
    "w2_next2_031",
    "w2_next2_032",
    "w2_next2_033",
    "w2_next2_034",
    "w2_next2_035",
    "w2_next2_036",
    "w2_next2_037",
    "w2_next2_038",
    "w2_next2_039",
    "w2_next2_040",
    "w2_next2_041",
    "w2_next2_042",
    "w2_next2_043",
    "w2_next2_044",
    "w2_next2_045",
    "w2_next2_046",
    "w2_next2_047",
    "w2_next2_048",
    "w2_next2_049",
    "w2_next2_050",
    "w2_next2_051",
    "w2_next2_052",
    "w2_next2_053",
    "w2_next2_054",
    "w2_next2_055",
    "w2_next2_056",
    "w2_next2_057",
    "w2_next2_058",
    "w2_next2_059",
    "w2_next2_060",
    "w2_next2_061",
    "w2_next2_062",
    "w2_next2_063",
    "w2_next2_064",
    "w2_next2_065",
    "w2_next2_066",
    "w2_next2_067",
    "w2_next2_068",
    "w2_next2_069",
    "w2_next2_070",
    "w2_next2_071",
    "w2_next2_072",
    "w2_next2_073",
    "w2_next2_074",
    "w2_next2_075",
    "w2_next2_076",
    "w2_next2_077",
    "w2_next2_078",
    "w2_next2_079",
    "w2_next2_080",
    "w2_next2_081",
    "w2_next2_082",
    "w2_next2_083",
    "w2_next2_084",
    "w2_next2_085",
    "w2_next2_086",
    "w2_next2_087",
    "w2_next2_088",
    "w2_next2_089",
    "w2_next2_090",
    "w2_next2_091",
    "w2_next2_092",
    "w2_next2_093",
    "w2_next2_094",
    "w2_next2_095",
    "w2_next2_096",
    "w2_next2_097",
    "w2_next2_098",
    "w2_next2_099",
    "w2_next2_100",
    ]);

  export const WESTERN_HOOK_PACK_BATCH_NEXT2: readonly WesternHookPackDraftEntry[] =
    Object.freeze([
    {
    id: "w2_next2_001",
    hook: "My bank app made my face do a system update",
    whatToShow: "Creator opens a fake/blurred bank screen, eyebrows lift, jaw tightens, phone slowly turns face-down like the conversation is over.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator opens a fake/blurred bank screen, eyebrows lift, jaw tightens, phone slowly turns face-down like the conversation is over. Keep your face flat the whole time; let the silence land.",
    caption: "the update eyebrows won this round.",
    anchor: "eyebrows",
    comedyFamily: "adulting_panic",
    emotionalSpike: "panic",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Use fake or blurred banking screen only.",
    originalBatchNumber: 1,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_002",
    hook: "I started cleaning the fridge and found a second personality",
    whatToShow: "Creator sits on the kitchen floor surrounded by condiments, one sad vegetable, and a trash bag, staring like the fridge won.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator sits on the kitchen floor surrounded by condiments, one sad vegetable, and a trash bag, staring like the fridge won. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the personality condiments closed the meeting.",
    anchor: "condiments",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "quiet_defeat",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    originalBatchNumber: 2,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_003",
    hook: "This cilantro has been holding me emotionally hostage",
    whatToShow: "Close-up of wilted cilantro in the fridge, creator holds takeout bag nearby, then slowly closes the fridge without making eye contact.",
    howToFilm: "Phone on a tripod, one locked-off shot. close-up of wilted cilantro in the fridge, creator holds takeout bag nearby, then slowly closes the fridge without making eye contact. End on a held silent stare; let the realization sit.",
    caption: "i would like a moment with the hostage wilted in private.",
    anchor: "wilted",
    comedyFamily: "food_self_control",
    emotionalSpike: "quiet_guilt",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 3,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_004",
    hook: "My work-from-home bun became a structural hazard",
    whatToShow: "Creator adjusts a leaning work-from-home bun at the desk, the bun slowly collapses, and their glasses get knocked sideways.",
    howToFilm: "Shoot from desk height. Start with the bun already leaning, adjust it once, then let the collapse knock the glasses slightly out of place.",
    caption: "OSHA was not notified.",
    anchor: "bun",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "self_betrayal",
    setting: "desk",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "before_after_self",
    safetyNote: "Keep the physical gag gentle.",
    originalBatchNumber: 4,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_005",
    hook: "Mail looked at me. I chose fees.",
    whatToShow: "Creator walks past a stack of unopened mail, makes eye contact with the mail, places a coffee mug on top, and keeps walking like the mail started it.",
    howToFilm: "Frame the unopened mail stack on the hallway table. Walk past the mail, place the coffee mug on top, then keep walking without opening it.",
    caption: "mail blinked first.",
    anchor: "mail",
    comedyFamily: "task_avoidance",
    emotionalSpike: "dread",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "realization",
    safetyNote: "Hide names, addresses, and account details.",
    originalBatchNumber: 5,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_006",
    hook: "My phone waited until bedtime to choose violence",
    whatToShow: "Creator lying in bed setting an alarm, phone slips onto their face, creator freezes in betrayed silence.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator lying in bed setting an alarm, phone slips onto their face, creator freezes in betrayed silence. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the violence lying and i had an arrangement.",
    anchor: "lying",
    comedyFamily: "parasocial_object",
    emotionalSpike: "self_betrayal",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Keep the physical gag safe and staged.",
    originalBatchNumber: 6,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_007",
    hook: "LinkedIn me would not survive my kitchen",
    whatToShow: "Creator shows a staged LinkedIn profile posture at the laptop for one beat, then cuts to eating shredded cheese over the sink in a bathrobe.",
    howToFilm: "Use a quick two-shot contrast. Start with the staged LinkedIn laptop posture, then cut to the private sink-cheese version with no explanation.",
    caption: "LinkedIn has not been briefed.",
    anchor: "LinkedIn",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "shame",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Do not show real LinkedIn/profile details.",
    originalBatchNumber: 7,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_008",
    hook: "This email found me absolutely not well",
    whatToShow: "Creator is sorting a junk drawer by color when an email notification dings; they look at the laptop like the email interrupted private nonsense.",
    howToFilm: "Frame the weird drawer-sorting first. Let the email notification interrupt, then hold the stare like the message arrived at the worst possible time.",
    caption: "this email found a situation.",
    anchor: "email",
    comedyFamily: "work_school_panic",
    emotionalSpike: "dread",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Use staged email notification only.",
    originalBatchNumber: 8,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_009",
    hook: "One grocery trip, twelve bags, zero survival instincts",
    whatToShow: "Creator at their own front door overloaded with grocery bags, using their chin to reach the handle instead of putting anything down.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator at their own front door overloaded with grocery bags, using their chin to reach the handle instead of putting anything down. Punch the final beat with one theatrical reaction.",
    caption: "the instincts grocery won this round.",
    anchor: "grocery",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "panic",
    setting: "doorway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "fake_tutorial",
    safetyNote: "Avoid unsafe strain.",
    originalBatchNumber: 9,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_010",
    hook: "A new sponge should not have changed my whole week",
    whatToShow: "Creator unboxes a bright new sponge like luxury tech, then slowly holds it up to the sink with awe.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator unboxes a bright new sponge like luxury tech, then slowly holds it up to the sink with awe. Punch the final beat with one theatrical reaction.",
    caption: "and just like that, the week unboxes won.",
    anchor: "unboxes",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_realization",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Avoid visible brand if needed.",
    originalBatchNumber: 10,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_011",
    hook: "The laundry chair has officially become furniture",
    whatToShow: "Creator tries to sit on the only chair, realizes it is fully occupied by clean laundry, then gently places a laptop on top like accepting defeat.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator tries to sit on the only chair, realizes it is fully occupied by clean laundry, then gently places a laptop on top like accepting defeat. Keep your face flat the whole time; let the silence land.",
    caption: "the furniture laundry closed the meeting.",
    anchor: "laundry",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 11,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_012",
    hook: "A three-minute phone call somehow needs a launch sequence",
    whatToShow: "Creator stares at a fake phone number, stretches fingers, takes a breath, hovers over call, then sets the phone down.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator stares at a fake phone number, stretches fingers, takes a breath, hovers over call, then sets the phone down. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the sequence call won this round.",
    anchor: "call",
    comedyFamily: "task_avoidance",
    emotionalSpike: "panic",
    setting: "desk",
    voiceCluster: "chaotic_confession",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Use fake contact/number.",
    originalBatchNumber: 12,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_013",
    hook: "This $12 smoothie was supposed to install a new personality",
    whatToShow: "Creator takes a hopeful smoothie sip, waits for a new personality to arrive, checks the phone camera, and realizes nothing installed.",
    howToFilm: "Show the smoothie sip clearly. Take the hopeful smoothie sip, wait two beats, then check the phone camera like the personality update failed.",
    caption: "smoothie did not install the update.",
    anchor: "smoothie",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "self_betrayal",
    setting: "car",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Do not film while driving.",
    originalBatchNumber: 13,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_014",
    hook: "Circling back from a place of guilt",
    whatToShow: "Creator wears sunglasses at the desk, opens a staged email reply, types “just circling back,” and glances around like hiding from accountability.",
    howToFilm: "Use staged email text. Put on the sunglasses, type the corporate phrase slowly, then look over both shoulders before sending.",
    caption: "circling back from the scene.",
    anchor: "circling",
    comedyFamily: "work_school_panic",
    emotionalSpike: "shame",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Use staged email text.",
    originalBatchNumber: 14,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_015",
    hook: "Night routine is just switching screens horizontally",
    whatToShow: "Creator starts a night routine by turning off the TV, lies horizontally, then immediately opens the phone inches from their face.",
    howToFilm: "Show the night routine starting with the TV turning off. Then show the horizontal lie-down and the phone opening inches from the face, like the routine simply changed screens.",
    caption: "night routine changed devices.",
    anchor: "night",
    comedyFamily: "procrastination_theatre",
    emotionalSpike: "quiet_guilt",
    setting: "living_room",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 15,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_016",
    hook: "I said \"just looking\" and immediately started acting employed",
    whatToShow: "Creator says “just looking” to nobody in their own pantry, then starts inspecting a loaf of bread with fake employee-level seriousness.",
    howToFilm: "Simulate the store moment at home. Say “just looking,” pick up the bread from the pantry, and nod with fake employee seriousness.",
    caption: "just looking became a shift.",
    anchor: "looking",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Do not film strangers or store employees.",
    originalBatchNumber: 16,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_017",
    hook: "Software update has been asking for closure since last month",
    whatToShow: "Laptop update prompt appears, creator clicks \"remind me tomorrow\" with the calm of someone ending a relationship.",
    howToFilm: "Phone on a tripod, one locked-off shot. laptop update prompt appears, creator clicks \"remind me tomorrow\" with the calm of someone ending a relationship. Keep your face flat the whole time; let the silence land.",
    caption: "i would like a moment with the month update in private.",
    anchor: "update",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_guilt",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "calendar_task_betrayal",
    safetyNote: "Hide private desktop content.",
    originalBatchNumber: 17,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_018",
    hook: "Four-person dinner needs battery approval",
    whatToShow: "Creator counts dinner math on their fingers, recalculates silently on the couch, then lies face-down because the dinner math failed.",
    howToFilm: "Frame the dinner math on the couch. Count on your fingers, recalculate silently, then collapse face-down because the dinner math failed.",
    caption: "four people was not in the budget.",
    anchor: "dinner",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "panic",
    setting: "couch",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "overdramatic_diagnosis",
    originalBatchNumber: 18,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_019",
    hook: "My treat-yourself logic has entered the courtroom",
    whatToShow: "Creator presents the treat-yourself candle like courtroom evidence, silently pointing to it and then to the lights like the purchase is saving money.",
    howToFilm: "Frame the candle as evidence. Use hand gestures like a trial: candle, lights, receipt, final confident nod.",
    caption: "treat yourself submitted evidence.",
    anchor: "treat",
    comedyFamily: "self_betrayal",
    emotionalSpike: "self_betrayal",
    setting: "living_room",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    originalBatchNumber: 19,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_020",
    hook: "7:05am me is not the person 10pm me hired",
    whatToShow: "Creator sits on the bed at 7:05am with one sock on, staring at the wall like the person 10pm hired never showed up.",
    howToFilm: "Show the 7:05am time, the one sock, and the blank stare on the bed. Let it feel like the person 10pm hired never showed up.",
    caption: "10pm me lied on the résumé.",
    anchor: "person",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 20,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_021",
    hook: "Delivery tracking turned me into neighborhood surveillance",
    whatToShow: "Creator peeks through blinds, sees nothing, then dives back to couch before the delivery person arrives.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator peeks through blinds, sees nothing, then dives back to couch before the delivery person arrives. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the surveillance blinds won this round.",
    anchor: "blinds",
    comedyFamily: "food_self_control",
    emotionalSpike: "panic",
    setting: "living_room",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Do not film delivery person, address, or neighbors.",
    originalBatchNumber: 21,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_022",
    hook: "My inbox zero strategy is deleting everything with a tone",
    whatToShow: "Creator rhythmically taps delete on a staged inbox, looking calmer with each stressful-looking subject line.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator rhythmically taps delete on a staged inbox, looking calmer with each stressful-looking subject line. Keep your face flat the whole time; let the silence land.",
    caption: "looked productive. it was the tone inbox all along.",
    anchor: "inbox",
    comedyFamily: "self_betrayal",
    emotionalSpike: "false_productivity",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Use staged/blurred inbox.",
    originalBatchNumber: 22,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_023",
    hook: "This coffee is load-bearing",
    whatToShow: "Creator holds fancy coffee upright; when it gets set down, their posture and face immediately collapse.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator holds fancy coffee upright; when it gets set down, their posture and face immediately collapse. Punch the final beat with one theatrical reaction.",
    caption: "and just like that, the bearing coffee won.",
    anchor: "coffee",
    comedyFamily: "parasocial_object",
    emotionalSpike: "quiet_realization",
    setting: "car",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Do not film while driving.",
    originalBatchNumber: 23,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_024",
    hook: "The \"I understood that\" face has left the building",
    whatToShow: "Creator makes the “I understood that” face: aggressive nodding, wide panicked eyes, fake “ohhh okay,” then writes absolutely nothing down.",
    howToFilm: "Make the face the whole bit. Nod too hard, say the fake “okay,” then reveal the blank note page.",
    caption: "understood nothing. performed everything.",
    anchor: "face",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "panic",
    setting: "hallway",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    originalBatchNumber: 24,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_025",
    hook: "My junk drawer has started keeping secrets",
    whatToShow: "Creator opens drawer and pulls out an old remote, mystery key, rubber band ball, and one impossible random object.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator opens drawer and pulls out an old remote, mystery key, rubber band ball, and one impossible random object. End on a held silent stare; let the realization sit.",
    caption: "and just like that, the secrets drawer won.",
    anchor: "drawer",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "quiet_realization",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Avoid showing personal documents.",
    originalBatchNumber: 25,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_026",
    hook: "Add to cart me has never met bank app me",
    whatToShow: "Creator taps \"add to cart\" with royal confidence, then cuts to eating dry cereal from a mug.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator taps \"add to cart\" with royal confidence, then cuts to eating dry cereal from a mug. Punch the final beat with one theatrical reaction.",
    caption: "the bank royal and i had an arrangement.",
    anchor: "royal",
    comedyFamily: "self_betrayal",
    emotionalSpike: "self_betrayal",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "before_after_self",
    safetyNote: "Use fake cart/balance screens.",
    originalBatchNumber: 26,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_027",
    hook: "I just remembered breathing is supposed to happen automatically",
    whatToShow: "Creator sits at the desk, suddenly remembers breathing, lets out a huge exhale, slumps back, and blinks like the system rebooted.",
    howToFilm: "Hold still at the desk first. Then release the giant exhale all at once, slump back, and let the reboot blink land.",
    caption: "breathing had to be manually updated.",
    anchor: "breathing",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_realization",
    setting: "desk",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 27,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_028",
    hook: "I bought one seed packet and became unbearable",
    whatToShow: "Creator stares intensely at a damp paper towel with a bean/seed, labeling it like a scientific breakthrough.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator stares intensely at a damp paper towel with a bean/seed, labeling it like a scientific breakthrough. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the unbearable stares won this round.",
    anchor: "stares",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "overdramatic_diagnosis",
    originalBatchNumber: 28,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_029",
    hook: "Reading instructions is not part of my brand, apparently",
    whatToShow: "Creator holds the instructions upside down, pockets a mystery screw, and confidently tries to force two harmless pieces together.",
    howToFilm: "Show the upside-down instructions first. Then show the mystery screw and the wrong assembly attempt. Keep the confidence undeserved.",
    caption: "instructions were present. not involved.",
    anchor: "instructions",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "self_betrayal",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Use safe/light objects only.",
    originalBatchNumber: 29,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_030",
    hook: "Door-lock doubt has a subscription plan",
    whatToShow: "Creator lies in bed, has door-lock doubt, gets up to check the lock, returns to bed, then immediately doubts the lock again.",
    howToFilm: "Use quick cuts between bed and door. Make the loop feel like a subscription renewal: check, return, doubt, repeat.",
    caption: "door-lock doubt renewed automatically.",
    anchor: "lock",
    comedyFamily: "creator_anxiety",
    emotionalSpike: "panic",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Do not show exterior address details.",
    originalBatchNumber: 30,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_031",
    hook: "I promoted myself to Head of Tomorrow",
    whatToShow: "Creator promoted themself with a blazer over pajamas, opens the laptop, immediately closes it, and nods like tomorrow’s department handled it.",
    howToFilm: "Start with the blazer over pajamas like a promotion ceremony. Open the laptop, close it immediately, then nod like tomorrow’s department handled it.",
    caption: "promoted. postponed.",
    anchor: "promoted",
    comedyFamily: "self_betrayal",
    emotionalSpike: "shame",
    setting: "desk",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "confession",
    originalBatchNumber: 31,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_032",
    hook: "Gym outfit clocked in. I did not.",
    whatToShow: "Creator wears the gym outfit on an unrolled yoga mat, eats chips, and gives the mat a guilty look because the outfit clocked in alone.",
    howToFilm: "Frame the gym outfit, the unrolled yoga mat, and the chips together. Eat the chips calmly, then give the mat the guilty look.",
    caption: "outfit showed up for both of us.",
    anchor: "outfit",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "self_betrayal",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "before_after_self",
    originalBatchNumber: 32,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_033",
    hook: "I started protecting my last $20 like family property",
    whatToShow: "Creator places a single bill in a tiny jewelry box or envelope, then checks on it like a sleeping baby.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator places a single bill in a tiny jewelry box or envelope, then checks on it like a sleeping baby. Punch the final beat with one theatrical reaction.",
    caption: "the property places is doing the most.",
    anchor: "places",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "dread",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    safetyNote: "Use prop cash if preferred.",
    originalBatchNumber: 33,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_034",
    hook: "Five more minutes became a missing-person case",
    whatToShow: "Creator says “five more minutes,” hits snooze, then quick-cuts to messy hair, toast in hand, and total confusion at the clock.",
    howToFilm: "Show the “five more minutes” moment clearly. Then cut hard to the aftermath: hair, toast, clock, no explanation.",
    caption: "five minutes filed a report.",
    anchor: "five",
    comedyFamily: "self_betrayal",
    emotionalSpike: "time_loss",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    originalBatchNumber: 34,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_035",
    hook: "Avoiding someone in public turned me into a shelf inspector",
    whatToShow: "Creator recreates avoiding someone by crouching at pantry shelves, inspecting canned beans like public eye contact depends on it.",
    howToFilm: "Shoot the avoiding crouch at home. Crouch by the pantry shelves, inspect the canned beans like urgent research, and avoid imaginary eye contact.",
    caption: "avoiding became a full inspection.",
    anchor: "avoiding",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    safetyNote: "Do not film strangers.",
    originalBatchNumber: 35,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_036",
    hook: "My productivity hack was changing the font and leaving",
    whatToShow: "Creator adjusts a to-do list font, leans back proudly, then closes the laptop without completing anything.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator adjusts a to-do list font, leans back proudly, then closes the laptop without completing anything. Keep your face flat the whole time; let the silence land.",
    caption: "looked productive. it was the leaving adjusts all along.",
    anchor: "adjusts",
    comedyFamily: "self_betrayal",
    emotionalSpike: "false_productivity",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Use staged task list.",
    originalBatchNumber: 36,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_037",
    hook: "Hunger made me start negotiating with the microwave",
    whatToShow: "Creator watches the microwave spin, whispers \"please,\" and places both hands on the counter like waiting for medical news.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator watches the microwave spin, whispers \"please,\" and places both hands on the counter like waiting for medical news. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the negotiating microwave won this round.",
    anchor: "microwave",
    comedyFamily: "parasocial_object",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    originalBatchNumber: 37,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_038",
    hook: "One shoe on. Floor won.",
    whatToShow: "Creator puts on one shoe in the hallway, pauses, looks at the floor, then slowly lies down with the shoe still on.",
    howToFilm: "Frame the hallway and shoe. Show the going-out attempt, the pause, and the slow surrender to the floor.",
    caption: "floor had better terms.",
    anchor: "floor",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "quiet_realization",
    setting: "hallway",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 38,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_039",
    hook: "One chip was a beautiful theory",
    whatToShow: "Creator takes one chip delicately, then jump-cuts to the bag upside down over their mouth.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator takes one chip delicately, then jump-cuts to the bag upside down over their mouth. Talk-to-camera between beats; loose, a little frantic.",
    caption: "instant regret, sponsored by the theory delicately every time.",
    anchor: "delicately",
    comedyFamily: "food_self_control",
    emotionalSpike: "instant_regret",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    safetyNote: "Avoid unsafe eating; stage the gag.",
    originalBatchNumber: 39,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_040",
    hook: "Self-checkout accused me and I immediately looked guilty",
    whatToShow: "Creator recreates self-checkout at home, hears \"unexpected item,\" slowly raises hands like they've been caught.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator recreates self-checkout at home, hears \"unexpected item,\" slowly raises hands like they've been caught. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the guilty checkout won this round.",
    anchor: "checkout",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "panic",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Do not film in-store shoppers or employees.",
    originalBatchNumber: 40,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_041",
    hook: "Resetting the router has become a household ritual",
    whatToShow: "Creator kneels in front of router, unplugs it, waits like a ceremony is happening, then gives it a serious nod.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator kneels in front of router, unplugs it, waits like a ceremony is happening, then gives it a serious nod. Punch the final beat with one theatrical reaction.",
    caption: "the ritual router won this round.",
    anchor: "router",
    comedyFamily: "phone_distraction",
    emotionalSpike: "panic",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "fake_tutorial",
    safetyNote: "Avoid unsafe handling of outlets.",
    originalBatchNumber: 41,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_042",
    hook: "Zoom meeting smile got concerning",
    whatToShow: "Creator sits in a staged Zoom meeting on the laptop, frozen smile getting wider, leaning closer until only their eyes fill the camera.",
    howToFilm: "Use a fake Zoom meeting screen or laptop camera angle. Start normal, hold the frozen smile too long, then slowly lean into the camera.",
    caption: "Zoom face needed supervision.",
    anchor: "Zoom",
    comedyFamily: "work_school_panic",
    emotionalSpike: "dread",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Use staged meeting screen.",
    originalBatchNumber: 42,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_043",
    hook: "9pm bedtime became a documentary about staplers",
    whatToShow: "Creator brushes teeth at 9pm, then at 1am stands in bathroom scrolling a random deep-dive page.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator brushes teeth at 9pm, then at 1am stands in bathroom scrolling a random deep-dive page. End on a held silent stare; let the realization sit.",
    caption: "the staplers brushes ate the hour.",
    anchor: "brushes",
    comedyFamily: "procrastination_theatre",
    emotionalSpike: "time_loss",
    setting: "bathroom",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    safetyNote: "Use fake/neutral webpage.",
    originalBatchNumber: 43,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_044",
    hook: "Checking the weather by opening the door is my science",
    whatToShow: "Creator opens front door, feels the air, makes a face like they've been insulted, closes it immediately.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator opens front door, feels the air, makes a face like they've been insulted, closes it immediately. Keep your face flat the whole time; let the silence land.",
    caption: "the science front and i had an arrangement.",
    anchor: "front",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "self_betrayal",
    setting: "doorway",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Avoid showing street/address.",
    originalBatchNumber: 44,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_045",
    hook: "Entered the room. Purpose vanished.",
    whatToShow: "Creator walks into the room, stops with a system-error face, looks around the room, then walks back out without doing anything.",
    howToFilm: "Use a doorway shot into the room. Walk in with purpose, stop with the system-error face, look around the room, then walk back out.",
    caption: "brain disconnected in the doorway.",
    anchor: "room",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_realization",
    setting: "doorway",
    voiceCluster: "chaotic_confession",
    hookStyle: "realization",
    originalBatchNumber: 45,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_046",
    hook: "Tape edge chose war",
    whatToShow: "Creator rotates a roll of clear tape, scratches at the invisible edge, squints harder, then slowly loses composure.",
    howToFilm: "Frame the tape close-up. Show the rotation, the scratching, the squinting, then the tiny breakdown over an invisible edge.",
    caption: "tape chose psychological warfare.",
    anchor: "tape",
    comedyFamily: "task_avoidance",
    emotionalSpike: "polite_rage",
    setting: "kitchen",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    originalBatchNumber: 46,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_047",
    hook: "Nice sweater me did not last",
    whatToShow: "Creator starts at the desk in a nice sweater, reveals pajama pants, messy hair, and a coffee mug by 10am.",
    howToFilm: "Start at the desk in the nice sweater. Reveal the pajama pants, messy hair, and coffee mug so the 10am collapse is obvious.",
    caption: "sweater clocked out early.",
    anchor: "sweater",
    comedyFamily: "procrastination",
    emotionalSpike: "self_betrayal",
    setting: "desk",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 47,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_048",
    hook: "My budgeting plan is hoping the app declines me first",
    whatToShow: "Creator opens a staged budgeting note, then a fake app payment screen, clasps hands, and clearly hopes the app declines before they have to decide.",
    howToFilm: "Show the budgeting plan first, then the payment screen. The joke is praying for the app to be the responsible one.",
    caption: "budgeting outsourced to the app.",
    anchor: "budgeting",
    comedyFamily: "task_avoidance",
    emotionalSpike: "financial_dread",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "confession",
    safetyNote: "Use fake payment/subscription screen.",
    originalBatchNumber: 48,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_049",
    hook: "Self-help podcast on. Kitchen still losing.",
    whatToShow: "Creator calmly listens to a \"get your life together\" podcast while standing beside a pile of dirty dishes.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator calmly listens to a \"get your life together\" podcast while standing beside a pile of dirty dishes. End on a held silent stare; let the realization sit.",
    caption: "we do not speak of the losing calmly incident.",
    anchor: "calmly",
    comedyFamily: "self_betrayal",
    emotionalSpike: "shame",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    safetyNote: "Use staged podcast screen/audio.",
    originalBatchNumber: 49,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_050",
    hook: "Plant parenting became witness protection",
    whatToShow: "Creator over-waters a struggling plant, whispers an apology, then slides a fake plant in front of it like hiding a witness.",
    howToFilm: "Frame both plants. Show the overwatering, the apology, then the fake plant being moved in front like a coverup.",
    caption: "the plant has been relocated.",
    anchor: "plant",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "self_betrayal",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 50,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_051",
    hook: "Fine me built a sad sandwich",
    whatToShow: "Creator sits alone at the kitchen table with a dry sandwich, stares at the sandwich, then takes one silent bite like the sandwich knows too much.",
    howToFilm: "Frame the kitchen table and dry sandwich. Stare at the sandwich, take one silent bite, and keep it quiet and deadpan.",
    caption: "sandwich signed the NDA.",
    anchor: "sandwich",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Avoid framing mental-health distress as the joke.",
    originalBatchNumber: 51,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_052",
    hook: "My house fund is three coins and a powerful imagination",
    whatToShow: "Creator shakes a jar with a few coins, labels it \"future mansion,\" and nods with total seriousness.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator shakes a jar with a few coins, labels it \"future mansion,\" and nods with total seriousness. Punch the final beat with one theatrical reaction.",
    caption: "filed under: imagination shakes damage.",
    anchor: "shakes",
    comedyFamily: "self_betrayal",
    emotionalSpike: "financial_dread",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 52,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_053",
    hook: "Meal prep started with containers and ended with one egg",
    whatToShow: "Creator surrounded by empty containers, places one boiled egg in the middle, and closes the lid like the job is done.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator surrounded by empty containers, places one boiled egg in the middle, and closes the lid like the job is done. End on a held silent stare; let the realization sit.",
    caption: "the ended surrounded and i had an arrangement.",
    anchor: "surrounded",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "self_betrayal",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 53,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_054",
    hook: "My social media detox had a loading screen",
    whatToShow: "Creator starts a social media detox by putting the phone in a drawer, walks away, then immediately slides back into frame and opens the drawer.",
    howToFilm: "Show the detox decision with the phone going into the drawer. Walk away confidently, then return too fast and reopen it.",
    caption: "social media detox buffering.",
    anchor: "social",
    comedyFamily: "phone_distraction",
    emotionalSpike: "quiet_realization",
    setting: "hallway",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    originalBatchNumber: 54,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_055",
    hook: "Terms accepted by thumb alone",
    whatToShow: "Creator scrolls fake terms and conditions at light speed, squints like they are studying, then taps accept with fake confidence.",
    howToFilm: "Use a fake terms screen. Scroll way too fast, perform concentration with your face, then tap accept like you absorbed everything.",
    caption: "thumb understood enough.",
    anchor: "terms",
    comedyFamily: "phone_distraction",
    emotionalSpike: "shame",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "fake_tutorial",
    safetyNote: "Use fake terms screen.",
    originalBatchNumber: 55,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_056",
    hook: "Finding a sleep position became contact sport",
    whatToShow: "Creator tries finding a sleep position, wrestles the pillow and blanket, flips around safely, and ends upside down with one leg out of frame.",
    howToFilm: "Keep the movement safe and exaggerated. Show the failed position changes one after another until the final upside-down defeat.",
    caption: "sleep position fought back.",
    anchor: "finding",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "panic",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Keep movement safe.",
    originalBatchNumber: 56,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_057",
    hook: "Cleaning playlist: four hours. Cleaning: one crumb.",
    whatToShow: "Creator dances with broom, sweeps one crumb, sits down exhausted and checks phone.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator dances with broom, sweeps one crumb, sits down exhausted and checks phone. Punch the final beat with one theatrical reaction.",
    caption: "looked productive. it was the crumb dances all along.",
    anchor: "dances",
    comedyFamily: "self_betrayal",
    emotionalSpike: "false_productivity",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "before_after_self",
    originalBatchNumber: 57,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_058",
    hook: "Food at home was propaganda",
    whatToShow: "Creator opens the fridge, finds only a pickle jar or condiment, waits for more food to appear, then slowly closes the fridge door.",
    howToFilm: "Frame the fridge door opening. Show the pickle jar, wait for more food to appear, then close the fridge door with quiet defeat.",
    caption: "fridge said define food.",
    anchor: "food",
    comedyFamily: "food_self_control",
    emotionalSpike: "dread",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide delivery or address info if using phone later.",
    originalBatchNumber: 58,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_059",
    hook: "Low battery turned my living room into an action movie",
    whatToShow: "Creator sees a 1% battery warning in the living room, lunges safely across the couch toward a charger, misses once, then plugs in dramatically.",
    howToFilm: "Show the 1% battery warning in the living room, then lunge safely across the couch toward the charger. Miss once, plug in dramatically, and hold the relief.",
    caption: "1% brought out the stunt team.",
    anchor: "battery",
    comedyFamily: "creator_anxiety",
    emotionalSpike: "panic",
    setting: "living_room",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Keep movement safe.",
    originalBatchNumber: 59,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_060",
    hook: "This walk is just me fleeing my own to-do list",
    whatToShow: "Creator in hoodie and sunglasses slowly walks down hallway like a fugitive, while a to-do list sits ignored on table.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator in hoodie and sunglasses slowly walks down hallway like a fugitive, while a to-do list sits ignored on table. Keep your face flat the whole time; let the silence land.",
    caption: "we do not speak of the list hoodie incident.",
    anchor: "hoodie",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "shame",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "overdramatic_diagnosis",
    originalBatchNumber: 60,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_061",
    hook: "My draft response got promoted to emotional thesis",
    whatToShow: "Phone shows a short text draft, creator keeps adding lines, scrolls, then deletes it all and sends \"sure.\"",
    howToFilm: "Phone on a tripod, one locked-off shot. phone shows a short text draft, creator keeps adding lines, scrolls, then deletes it all and sends \"sure.\". Talk-to-camera between beats; loose, a little frantic.",
    caption: "the thesis shows did me dirty.",
    anchor: "shows",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "social_panic",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "tiny_documentary",
    safetyNote: "Use fake chat text.",
    originalBatchNumber: 61,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_062",
    hook: "I rehearsed the voicemail and still sounded surprised",
    whatToShow: "Creator rehearses the voicemail calmly, hears the beep, then instantly sounds surprised and says “hi??” like the phone called them.",
    howToFilm: "Show the calm voicemail rehearsal first. Let the beep interrupt, then switch into the surprised voice immediately.",
    caption: "rehearsed it. forgot the role.",
    anchor: "voicemail",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "panic",
    setting: "desk",
    voiceCluster: "chaotic_confession",
    hookStyle: "confession",
    safetyNote: "Use fake contact/number.",
    originalBatchNumber: 62,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_063",
    hook: "The group chat liked my message and I became suspicious",
    whatToShow: "Creator sees several reactions on a message, narrows eyes, rereads it like evidence, then locks phone.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator sees several reactions on a message, narrows eyes, rereads it like evidence, then locks phone. End on a held silent stare; let the realization sit.",
    caption: "the suspicious reaction did me dirty.",
    anchor: "reaction",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "self_doubt_spike",
    setting: "kitchen",
    voiceCluster: "quiet_realization",
    hookStyle: "accusation",
    safetyNote: "Use fake group chat.",
    originalBatchNumber: 63,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_064",
    hook: "My typing indicator disappeared into witness protection",
    whatToShow: "Phone shows typing dots, creator sits up, dots vanish, creator slowly lowers phone like receiving bad news.",
    howToFilm: "Phone on a tripod, one locked-off shot. phone shows typing dots, creator sits up, dots vanish, creator slowly lowers phone like receiving bad news. End on a held silent stare; let the realization sit.",
    caption: "the protection vanish closed the meeting.",
    anchor: "vanish",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    safetyNote: "Use fake chat text.",
    originalBatchNumber: 64,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_065",
    hook: "\"No worries\" was not written by my nervous system",
    whatToShow: "Creator types \"no worries,\" sends it, then immediately paces behind the phone like there are many worries.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator types \"no worries,\" sends it, then immediately paces behind the phone like there are many worries. Keep your face flat the whole time; let the silence land.",
    caption: "the system types did me dirty.",
    anchor: "types",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "social_panic",
    setting: "couch",
    voiceCluster: "dry_deadpan",
    hookStyle: "confession",
    safetyNote: "Use fake chat text.",
    originalBatchNumber: 65,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_066",
    hook: "Dating app remembered I have a face",
    whatToShow: "Creator opens a fake dating app profile, sees their own profile, turns the phone face-down, and sits extremely still.",
    howToFilm: "Use a fake dating app profile. Show the profile briefly, turn the phone face-down, and sit extremely still like being perceived was too much.",
    caption: "dating app asked me to exist publicly.",
    anchor: "dating",
    comedyFamily: "social_plans",
    emotionalSpike: "private_embarrassment",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    safetyNote: "Use fake or staged dating screen.",
    originalBatchNumber: 66,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_067",
    hook: "My \"wyd\" reply needed a legal department",
    whatToShow: "Creator types three different replies to \"wyd,\" deletes each, then sends the most boring possible answer.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator types three different replies to \"wyd,\" deletes each, then sends the most boring possible answer. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the department types won this round.",
    anchor: "types",
    comedyFamily: "texting_overthinking",
    emotionalSpike: "panic",
    setting: "couch",
    voiceCluster: "chaotic_confession",
    hookStyle: "overdramatic_diagnosis",
    safetyNote: "Use fake chat text.",
    originalBatchNumber: 67,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_068",
    hook: "Heart reaction felt legally binding",
    whatToShow: "Creator taps a heart reaction on a staged message or post, freezes, tries to undo it, then redoes it and tosses the phone onto the couch.",
    howToFilm: "Frame the staged reaction. Tap the heart, panic, undo and redo if needed, then toss the phone softly onto a cushion.",
    caption: "heart reaction had consequences.",
    anchor: "heart",
    comedyFamily: "tiny_public_private_awkwardness",
    emotionalSpike: "instant_regret",
    setting: "couch",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "confession",
    safetyNote: "Use fake or staged post/message.",
    originalBatchNumber: 68,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_069",
    hook: "The \"quick reply\" tab has been open since breakfast",
    whatToShow: "Laptop or phone shows a reply draft; creator walks past it at different times with different snacks.",
    howToFilm: "Phone on a tripod, one locked-off shot. laptop or phone shows a reply draft; creator walks past it at different times with different snacks. Keep your face flat the whole time; let the silence land.",
    caption: "i would like a moment with the breakfast reply in private.",
    anchor: "reply",
    comedyFamily: "task_avoidance",
    emotionalSpike: "quiet_guilt",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "calendar_task_betrayal",
    safetyNote: "Use staged email/message text.",
    originalBatchNumber: 69,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_070",
    hook: "Muted chat. Checked immediately.",
    whatToShow: "Creator toggles mute on a fake chat, sets the phone down with confidence, then immediately picks it back up to check the same chat.",
    howToFilm: "Use a fake chat screen. Show the mute toggle, set the phone down confidently, then pick it back up immediately.",
    caption: "muted chat, active clown.",
    anchor: "mute",
    comedyFamily: "self_betrayal",
    emotionalSpike: "shame",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "before_after_self",
    safetyNote: "Use fake chat text.",
    originalBatchNumber: 70,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_071",
    hook: "My subscription list is just a haunted house with prices",
    whatToShow: "Creator scrolls a fake subscription list, sees one they forgot, slowly backs away from laptop.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator scrolls a fake subscription list, sees one they forgot, slowly backs away from laptop. Keep your face flat the whole time; let the silence land.",
    caption: "filed under: prices forgot damage.",
    anchor: "forgot",
    comedyFamily: "task_avoidance",
    emotionalSpike: "financial_dread",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Use fake/blurred subscription list.",
    originalBatchNumber: 71,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_072",
    hook: "The free trial remembered me with interest",
    whatToShow: "Phone notification for a fake trial ending/charge, creator holds phone at arm's length like it's contaminated.",
    howToFilm: "Phone on a tripod, one locked-off shot. phone notification for a fake trial ending/charge, creator holds phone at arm's length like it's contaminated. End on a held silent stare; let the realization sit.",
    caption: "the interest trial did not warn me.",
    anchor: "trial",
    comedyFamily: "phone_distraction",
    emotionalSpike: "caught_off_guard",
    setting: "couch",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    safetyNote: "Use fake notification.",
    originalBatchNumber: 72,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_073",
    hook: "My cart total needed a moment of silence",
    whatToShow: "Creator reviews fake cart, slowly removes one item, pauses, then removes three more.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator reviews fake cart, slowly removes one item, pauses, then removes three more. Punch the final beat with one theatrical reaction.",
    caption: "instant regret, sponsored by the silence cart every time.",
    anchor: "cart",
    comedyFamily: "self_betrayal",
    emotionalSpike: "instant_regret",
    setting: "desk",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "tiny_documentary",
    safetyNote: "Use fake shopping cart.",
    originalBatchNumber: 73,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_074",
    hook: "My points showed up with no help",
    whatToShow: "Creator opens a fake rewards points screen, sees a tiny balance, then nods like a financial plan has been discovered.",
    howToFilm: "Frame the rewards screen safely. Show the tiny points balance, then hold on the serious nod that pretends this helps.",
    caption: "rewards points had a meeting with hope.",
    anchor: "rewards",
    comedyFamily: "self_betrayal",
    emotionalSpike: "false_productivity",
    setting: "kitchen",
    voiceCluster: "dry_deadpan",
    hookStyle: "realization",
    safetyNote: "Use fake rewards screen.",
    originalBatchNumber: 74,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_075",
    hook: "Splitwise turned brunch into a courtroom",
    whatToShow: "Creator opens a fake Splitwise brunch expense, points at one suspicious line item, then silently opens a calculator like evidence is being reviewed.",
    howToFilm: "Use a fake shared-expense screen. Point at the brunch line item, open the calculator, and let the silence feel like court.",
    caption: "Splitwise called the witness.",
    anchor: "Splitwise",
    comedyFamily: "self_betrayal",
    emotionalSpike: "polite_rage",
    setting: "couch",
    voiceCluster: "quiet_realization",
    hookStyle: "accusation",
    safetyNote: "Use fake expense names and amounts.",
    originalBatchNumber: 75,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_076",
    hook: "I bought the \"budget planner\" and immediately blew the budget",
    whatToShow: "Creator places a new budget planner on the desk, then adds the matching pen, candle, and coffee beside it until the planner is surrounded by purchases.",
    howToFilm: "Start with the budget planner alone on the desk. Add the matching pen, candle, and coffee one at a time until the budget setup looks expensive.",
    caption: "budgeting had startup costs.",
    anchor: "budget",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "self_betrayal",
    setting: "desk",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "before_after_self",
    originalBatchNumber: 76,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_077",
    hook: "My receipt folder is just a museum of poor decisions",
    whatToShow: "Creator opens a folder/drawer full of receipts, picks one up, winces, and places it back carefully.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator opens a folder/drawer full of receipts, picks one up, winces, and places it back carefully. Keep your face flat the whole time; let the silence land.",
    caption: "i would like a moment with the decisions folder in private.",
    anchor: "folder",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_guilt",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    safetyNote: "Hide store/payment details.",
    originalBatchNumber: 77,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_078",
    hook: "I rounded the price down and called it budgeting",
    whatToShow: "Creator sees fake price $47.99, writes \"$40-ish\" on a note, then looks proud.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator sees fake price $47.99, writes \"$40-ish\" on a note, then looks proud. Talk-to-camera between beats; loose, a little frantic.",
    caption: "looked productive. it was the budgeting price all along.",
    anchor: "price",
    comedyFamily: "self_betrayal",
    emotionalSpike: "false_productivity",
    setting: "kitchen",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    safetyNote: "Use fake price/receipt.",
    originalBatchNumber: 78,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_079",
    hook: "My wallet made a noise I have never heard before",
    whatToShow: "Creator opens wallet, one lonely card/receipt shifts, creator listens like the wallet is speaking.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator opens wallet, one lonely card/receipt shifts, creator listens like the wallet is speaking. End on a held silent stare; let the realization sit.",
    caption: "the before wallet won this round.",
    anchor: "wallet",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "panic",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    safetyNote: "Do not show card numbers.",
    originalBatchNumber: 79,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_080",
    hook: "The coupon expired and took my dignity with it",
    whatToShow: "Creator holds coupon/phone code, tries it, sees fake \"expired,\" then slowly sets item back down.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator holds coupon/phone code, tries it, sees fake \"expired,\" then slowly sets item back down. Keep your face flat the whole time; let the silence land.",
    caption: "the dignity coupon closed the meeting.",
    anchor: "coupon",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_defeat",
    setting: "kitchen",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    safetyNote: "Use fake coupon/code.",
    originalBatchNumber: 80,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_081",
    hook: "My alarm is now just a suggestion with sound",
    whatToShow: "Alarm rings, creator pats around for phone, taps snooze without opening eyes, then gives a thumbs-up to nobody.",
    howToFilm: "Phone on a tripod, one locked-off shot. alarm rings, creator pats around for phone, taps snooze without opening eyes, then gives a thumbs-up to nobody. Keep your face flat the whole time; let the silence land.",
    caption: "the sound alarm closed the meeting.",
    anchor: "alarm",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "quiet_defeat",
    setting: "bedroom",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    originalBatchNumber: 81,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_082",
    hook: "I woke up early and immediately used it wrong",
    whatToShow: "Creator wakes early, looks proud, then spends the extra time scrolling under blanket.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator wakes early, looks proud, then spends the extra time scrolling under blanket. End on a held silent stare; let the realization sit.",
    caption: "looked productive. it was the wrong early all along.",
    anchor: "early",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "false_productivity",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "before_after_self",
    originalBatchNumber: 82,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_083",
    hook: "My nighttime water became a bedside art installation",
    whatToShow: "Creator places one water cup on nightstand; cut to several half-full cups arranged like a gallery.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator places one water cup on nightstand; cut to several half-full cups arranged like a gallery. End on a held silent stare; let the realization sit.",
    caption: "and just like that, the installation water won.",
    anchor: "water",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "quiet_realization",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 83,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_084",
    hook: "Toothbrush waited through an entire podcast",
    whatToShow: "Creator stands at the bathroom mirror holding a toothbrush, podcast playing, not brushing, just staring like the bathroom became a waiting room.",
    howToFilm: "Frame the mirror and toothbrush. Let the podcast play or show it staged on the phone, then hold on the non-brushing stare.",
    caption: "toothbrush was present for moral support.",
    anchor: "brushing",
    comedyFamily: "procrastination_theatre",
    emotionalSpike: "time_loss",
    setting: "mirror",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    originalBatchNumber: 84,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_085",
    hook: "My sleep mask is just a decorative surrender flag",
    whatToShow: "Creator puts on sleep mask, then lifts it immediately to check phone.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator puts on sleep mask, then lifts it immediately to check phone. End on a held silent stare; let the realization sit.",
    caption: "the flag mask and i had an arrangement.",
    anchor: "mask",
    comedyFamily: "self_improvement_attempt",
    emotionalSpike: "self_betrayal",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "object_betrayal",
    originalBatchNumber: 85,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_086",
    hook: "Morning stretch made one sound and I cancelled fitness",
    whatToShow: "Creator does one small stretch, hears/acts out a tiny creak, then carefully sits back down.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator does one small stretch, hears/acts out a tiny creak, then carefully sits back down. Punch the final beat with one theatrical reaction.",
    caption: "the fitness small did not warn me.",
    anchor: "small",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "caught_off_guard",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "fake_tutorial",
    safetyNote: "Keep movement safe.",
    originalBatchNumber: 86,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_087",
    hook: "My breakfast plan lost to standing over the sink",
    whatToShow: "Creator opens cabinet, looks at bowl, then eats something directly over the sink with quiet acceptance.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator opens cabinet, looks at bowl, then eats something directly over the sink with quiet acceptance. Keep your face flat the whole time; let the silence land.",
    caption: "the sink cabinet closed the meeting.",
    anchor: "cabinet",
    comedyFamily: "leaving_house_delay",
    emotionalSpike: "quiet_defeat",
    setting: "kitchen",
    voiceCluster: "dry_deadpan",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 87,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_088",
    hook: "I made the bed and immediately needed emotional proof",
    whatToShow: "Creator smooths blanket, steps back proudly, takes a photo, then sits on bed and ruins one corner.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator smooths blanket, steps back proudly, takes a photo, then sits on bed and ruins one corner. Punch the final beat with one theatrical reaction.",
    caption: "looked productive. it was the proof smooths all along.",
    anchor: "smooths",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "false_productivity",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "before_after_self",
    originalBatchNumber: 88,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_089",
    hook: "My lunch break became a meeting with my pillow",
    whatToShow: "Creator starts lunch break with food on the desk, glances at the pillow, then lies on the couch holding the lunch container like the meeting moved.",
    howToFilm: "Show the lunch first. Then show the pillow pulling focus, and end with the lunch container joining you on the couch.",
    caption: "lunch break had a chairperson.",
    anchor: "break",
    comedyFamily: "procrastination",
    emotionalSpike: "quiet_defeat",
    setting: "couch",
    voiceCluster: "quiet_realization",
    hookStyle: "realization",
    originalBatchNumber: 89,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_090",
    hook: "Pajamas ended my public life",
    whatToShow: "Creator walks into the hallway in normal clothes, cuts to pajamas, then gives the camera a formal clock-out nod.",
    howToFilm: "Use a simple before/after hallway cut. Normal clothes first, pajamas second, then the formal nod like society has been dismissed.",
    caption: "society shift ended.",
    anchor: "pajamas",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "excuse_found",
    setting: "hallway",
    voiceCluster: "dry_deadpan",
    hookStyle: "overdramatic_diagnosis",
    originalBatchNumber: 90,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_091",
    hook: "The tape measure just attacked my confidence",
    whatToShow: "Creator measures a small space, tape snaps back loudly, creator freezes like the room insulted them.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator measures a small space, tape snaps back loudly, creator freezes like the room insulted them. Talk-to-camera between beats; loose, a little frantic.",
    caption: "the confidence measures and i had an arrangement.",
    anchor: "measures",
    comedyFamily: "parasocial_object",
    emotionalSpike: "self_betrayal",
    setting: "living_room",
    voiceCluster: "chaotic_confession",
    hookStyle: "object_betrayal",
    safetyNote: "Use tape measure safely.",
    originalBatchNumber: 91,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_092",
    hook: "My reusable bag collection has become a personality test",
    whatToShow: "Creator opens a closet and reveals reusable bags inside reusable bags, then pulls out one tote and finds another tote folded inside it.",
    howToFilm: "Start with the closet reveal. Pull one reusable bag out, then reveal another bag inside like the collection is multiplying.",
    caption: "reusable bags discovered recursion.",
    anchor: "reusable",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "quiet_realization",
    setting: "bedroom",
    voiceCluster: "quiet_realization",
    hookStyle: "domestic_crime_scene",
    originalBatchNumber: 92,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_093",
    hook: "One junk email changed my algorithm",
    whatToShow: "Creator opens a fake junk email, then staged promo notifications begin appearing, and they slowly back away from the laptop.",
    howToFilm: "Use fake inbox/promos. Show the accidental click, then a quick sequence of promo notifications. End with backing away.",
    caption: "junk email told the whole internet.",
    anchor: "email",
    comedyFamily: "phone_distraction",
    emotionalSpike: "instant_regret",
    setting: "desk",
    voiceCluster: "chaotic_confession",
    hookStyle: "accusation",
    safetyNote: "Use staged inbox and notifications.",
    originalBatchNumber: 93,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_094",
    hook: "My reusable water bottle is just a loud metal pet",
    whatToShow: "Bottle rolls off couch/table, clanks loudly, creator rushes to stop it like it caused trouble.",
    howToFilm: "Phone on a tripod, one locked-off shot. bottle rolls off couch/table, clanks loudly, creator rushes to stop it like it caused trouble. Keep your face flat the whole time; let the silence land.",
    caption: "respectfully, the metal bottle is a problem.",
    anchor: "bottle",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "living_room",
    voiceCluster: "dry_deadpan",
    hookStyle: "object_betrayal",
    safetyNote: "Avoid breaking objects/floor.",
    originalBatchNumber: 94,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_095",
    hook: "I bought storage bins and created more things to store",
    whatToShow: "Creator stacks empty bins, then fills one with other bags/boxes from the bin purchase.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator stacks empty bins, then fills one with other bags/boxes from the bin purchase. Punch the final beat with one theatrical reaction.",
    caption: "we do not speak of the store stacks incident.",
    anchor: "stacks",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "shame",
    setting: "bedroom",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "realization",
    originalBatchNumber: 95,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_096",
    hook: "The fitted sheet asked for combat",
    whatToShow: "Creator tries folding a fitted sheet, gets trapped in corners, then sets it down folded terribly.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator tries folding a fitted sheet, gets trapped in corners, then sets it down folded terribly. Talk-to-camera between beats; loose, a little frantic.",
    caption: "respectfully, the combat fitted is a problem.",
    anchor: "fitted",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "polite_rage",
    setting: "bedroom",
    voiceCluster: "chaotic_confession",
    hookStyle: "fake_tutorial",
    safetyNote: "Keep movement safe.",
    originalBatchNumber: 96,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_097",
    hook: "My calendar reminder arrived after my motivation left",
    whatToShow: "Creator gets a calendar reminder on the phone, then camera reveals they are already under a blanket with motivation fully gone.",
    howToFilm: "Show the calendar reminder first. Then reveal the blanket situation slowly, like the reminder arrived at an abandoned office.",
    caption: "calendar reminder missed the meeting.",
    anchor: "calendar",
    comedyFamily: "task_avoidance",
    emotionalSpike: "quiet_defeat",
    setting: "couch",
    voiceCluster: "quiet_realization",
    hookStyle: "calendar_task_betrayal",
    safetyNote: "Use generic reminder text.",
    originalBatchNumber: 97,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_098",
    hook: "Drawer cleaning became a time capsule",
    whatToShow: "Creator opens a drawer to clean it, pulls out old receipts, a random charger, and an expired coupon, then pauses because the drawer remembered too much.",
    howToFilm: "Shoot the drawer from above. Pull out the old receipts, random charger, and expired coupon, then pause because the drawer becomes a time capsule.",
    caption: "drawer had archival footage.",
    anchor: "receipts",
    comedyFamily: "anxious_optimism",
    emotionalSpike: "quiet_realization",
    setting: "desk",
    voiceCluster: "dry_deadpan",
    hookStyle: "tiny_documentary",
    safetyNote: "Hide personal documents.",
    originalBatchNumber: 98,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_099",
    hook: "The smoke detector chirp chose psychological warfare",
    whatToShow: "Creator stands still in hallway listening, chirp happens, creator turns the wrong direction, chirp stops.",
    howToFilm: "Phone on a tripod, one locked-off shot. creator stands still in hallway listening, chirp happens, creator turns the wrong direction, chirp stops. Punch the final beat with one theatrical reaction.",
    caption: "respectfully, the warfare chirp is a problem.",
    anchor: "chirp",
    comedyFamily: "parasocial_object",
    emotionalSpike: "polite_rage",
    setting: "hallway",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "object_betrayal",
    safetyNote: "Do not disable safety devices improperly; stage sound if needed.",
    originalBatchNumber: 99,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
  {
    id: "w2_next2_100",
    hook: "Vacuum light revealed the truth",
    whatToShow: "Creator turns on a vacuum with a light, sees dust appear on the floor, then stares at the light like adulthood just made sense.",
    howToFilm: "Dim the room slightly if possible. Turn on the vacuum light, reveal the dust, then hold on the amazed adult realization.",
    caption: "vacuum light changed the room.",
    anchor: "vacuum",
    comedyFamily: "tiny_humiliation",
    emotionalSpike: "quiet_realization",
    setting: "living_room",
    voiceCluster: "overdramatic_reframe",
    hookStyle: "realization",
    originalBatchNumber: 100,
    reviewedBy: PENDING_EDITORIAL_REVIEW,
  },
    ]);
  